import { z } from "zod";
import type { NodeResult } from "../../../../../core/types/tax-node.ts";
import { TaxNode } from "../../../../../core/types/tax-node.ts";
import { OutputNodes } from "../../../../../core/types/output-nodes.ts";
import type { NodeContext } from "../../../../../core/types/node-context.ts";

// Form 8594 — Asset Acquisition Statement Under Section 1060
// Both buyer and seller must file when assets constituting a trade or business
// are sold/purchased. Assets allocated to 7 classes under the residual method.
// (IRS Form 8594 Instructions; IRC §1060)
// This node is informational — gain/loss routing to Schedule D / Form 4797
// occurs through the seller's other return schedules, not this node.

export enum PartyType {
  Seller = "seller",
  Buyer = "buyer",
}

export const inputSchema = z.object({
  party_type: z.nativeEnum(PartyType),
  sale_date: z.string(),
  total_sale_price: z.number().nonnegative(),
  allocation_class_i: z.number().nonnegative().optional(),
  allocation_class_ii: z.number().nonnegative().optional(),
  allocation_class_iii: z.number().nonnegative().optional(),
  allocation_class_iv: z.number().nonnegative().optional(),
  allocation_class_v: z.number().nonnegative().optional(),
  allocation_class_vi: z.number().nonnegative().optional(),
  allocation_class_vii: z.number().nonnegative().optional(),
});

class F8594Node extends TaxNode<typeof inputSchema> {
  readonly nodeType = "f8594";
  readonly inputSchema = inputSchema;
  readonly outputNodes = new OutputNodes([]);

  compute(_ctx: NodeContext, input: z.infer<typeof inputSchema>): NodeResult {
    inputSchema.parse(input);
    // Informational statement — no tax outputs generated by this node
    return { outputs: [] };
  }
}

export const f8594 = new F8594Node();
