/**
 * MeF Business Rules: F1040
 * Auto-generated from 1040_Business_Rules_2025v3.0.csv
 * 118 rules (93 implemented, 25 stubs)
 */

import type { RuleDef } from "../../../../core/validation/types.ts";
import {
  rule,
  all,
  alwaysPass,
  any,
  eqField,
  eqNum,
  eqStr,
  eqSum,
  filingStatusIs,
  filingStatusNot,
  formAbsent,
  formCountAtMost,
  formPresent,
  gt,
  hasNonZero,
  hasValue,
  ifThen,
  ifThenUnless,
  isZero,
  not,
  noValue,
  notGtNum,
  isITIN,
  ssnNotEqual,
  sumOfAll,
  validSSN,
} from "../../../../core/validation/mod.ts";

export const F1040_RULES: readonly RuleDef[] = [
  rule(
    "F1040-003-02",
    "reject",
    "missing_data",
    ifThen(filingStatusIs(4), any(gt("ChldWhoLivedWithYouCnt", 0), gt("OtherDependentsListedCnt", 0), all(hasValue("QualifyingHOHNm"), hasValue("QualifyingHOHSSN")))),
    "If the filing status of the return is head of household, then at least one of the following must be true: (1) [ 'ChldWhoLivedWithYouCnt' or 'OtherDependentsListedCnt'] has a value greater than zero or (2) both 'QualifyingHOHNm' and 'QualifyingHOHSSN' have values.",
  ),
  rule(
    "F1040-004-02",
    "reject",
    "missing_data",
    ifThen(hasValue("QualifyingHOHNm"), hasValue("QualifyingHOHSSN")),
    "If the filing status of the return is head of household and Form 1040, 'QualifyingHOHNm' has a value, then 'QualifyingHOHSSN' must have a value.",
  ),
  rule(
    "F1040-005-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("QualifyingHOHSSN"), all(ssnNotEqual("QualifyingHOHSSN", "PrimarySSN"), ssnNotEqual("QualifyingHOHSSN", "SpouseSSN"))),
    "If Form 1040, 'QualifyingHOHSSN' has a value, then it must not be the same as ['PrimarySSN' or 'SpouseSSN' ] in the Return Header.",
  ),
  rule(
    "F1040-006-03",
    "reject",
    "incorrect_data",
    ifThen(hasValue("QualifyingHOHSSN"), validSSN("QualifyingHOHSSN")),
    "If Form 1040, 'QualifyingHOHSSN' has a value, then it must be within the valid range of SSN/ITIN/ATIN.",
  ),
  rule(
    "F1040-007-01",
    "reject",
    "missing_data",
    ifThen(filingStatusIs(2), hasValue("SpouseSSN")),
    "If the filing status of the return is married filing jointly, then 'SpouseSSN' in the Return Header must have a value.",
  ),
  rule(
    "F1040-013-02",
    "reject",
    "incorrect_data",
    ifThen(eqStr("EICEligibilityLiteralCd", "NO"), isZero("EarnedIncomeCreditAmt")),
    "If Form 1040, 'EICEligibilityLiteralCd' has the value \"NO\", then 'EarnedIncomeCreditAmt' must be zero if an amount is entered.",
  ),
  rule(
    "F1040-014-02",
    "reject",
    "incorrect_data",
    ifThen(formPresent("schedule_eic"), hasNonZero("EarnedIncomeCreditAmt")),
    "If Schedule EIC (Form 1040) is present in the return, then Form 1040, 'EarnedIncomeCreditAmt' must have a non-zero value.",
  ),
  rule(
    "F1040-016-08",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("EarnedIncomeCreditAmt"), any(gt("HouseholdEmployeeWagesAmt", 0), gt("TipIncomeAmt", 0), gt("MedicaidWaiverPymtNotRptW2Amt", 0), gt("TaxableBenefitsAmt", 0), gt("TaxableBenefitsForm8839Amt", 0), gt("TotalWagesWithNoWithholdingAmt", 0), gt("OtherEarnedIncomeAmt", 0), gt("NontxCombatPayElectionAmt", 0), hasValue("WagesNotShownSchedule"), eqStr("PartnershipSCorpCd", "P"), all(formPresent("fec_record"), eqStr("WagesLiteralCd", "FEC"), gt("WagesNotShownAmt", 0)), formPresent("w2"), formPresent("f1099r"), formPresent("schedule_c"), formPresent("schedule_f"), formPresent("form8919"), formPresent("form4137"))),
    "If Form 1040, 'EarnedIncomeCreditAmt' has a non-zero value, then one of the following must be true: (1) 'HouseholdEmployeeWagesAmt', or 'TipIncomeAmt', or 'MedicaidWaiverPymtNotRptW2Amt', or 'TaxableBenefitsAmt', or 'TaxableBenefitsForm8839Amt', or 'TotalWagesWithNoWithholdingAmt', or 'OtherEarnedIncomeAmt' or 'NontxCombatPayElectionAmt' having a value greater than zero; (2) WagesNotShownSchedule is present in the return; (3) Schedule E (Form 1040), 'PartnershipSCorpCd' has the value \"P\"; (4) [FECRecord] is present in the return and 'WagesLiteralCd' in [WagesNotShownSchedule] has the value \"FEC\" with corresponding 'WagesNotShownAmt' having a value greater than zero; (5) Form W-2 or Form 1099-R or Schedule C (Form 1040) or Schedule F (Form 1040) or Form 8919 or Form 4137 is present in the return.",
  ),
  rule(
    "F1040-017-01",
    "reject",
    "data_mismatch",
    ifThen(hasValue("TaxableInterestAmt"), eqField("TaxableInterestAmt", "CalculatedTotalTaxableIntAmt")),
    "If Form 1040, 'TaxableInterestAmt' has a value greater than 1500, then it must be equal to Schedule B (Form 1040), 'CalculatedTotalTaxableIntAmt' unless Form 8958 is present in the return.",
  ),
  rule(
    "F1040-018-01",
    "reject",
    "data_mismatch",
    ifThen(hasValue("OrdinaryDividendsAmt"), eqField("OrdinaryDividendsAmt", "TotalOrdinaryDividendsAmt")),
    "If Form 1040, 'OrdinaryDividendsAmt' has a value greater than 1500, then it must be equal to Schedule B (Form 1040), 'TotalOrdinaryDividendsAmt' unless Form 8958 is present in the return.",
  ),
  rule(
    "F1040-021-03",
    "reject",
    "data_mismatch",
    ifThen(hasValue("TotalItemizedOrStandardDedAmt"), eqField("TotalItemizedOrStandardDedAmt", "TotalItemizedDeductionsAmt")),
    "If Schedule A (Form 1040) is present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must be equal to Schedule A (Form 1040), 'TotalItemizedDeductionsAmt'.",
  ),
  rule(
    "F1040-034-08",
    "reject",
    "math_error",
    alwaysPass,
    "Form 1040, 'WithholdingTaxAmt' must be equal to the sum of the following: [(1) all Forms 1099-R, 'FederalIncomeTaxWithheldAmt' and (2) all 'WithholdingAmt' in [OtherWithholdingStatement] and (3) all Forms W-2, 'WithholdingAmt' and (4) all Forms W-2G, 'FederalIncomeTaxWithheldAmt' and (5) Form 8959, 'AddlMedcrRRTTaxWithholdingAmt' and (6) 'TotalAmt' in [BackupWhSchedulesK1Statement] and (7) all Forms RRB 1042-S, 'FederalIncomeTaxWithheldAmt' and (8) all Forms SSA 1042-S, ('NetTaxWithheldAmt' if it has a non-zero value, otherwise 'FederalIncomeTaxWithheldAmt')] unless Form 8958 is present in the return. When evaluating this, a tolerance of $5.00 is allowed.",
  ),
  rule(
    "F1040-037-04",
    "reject",
    "incorrect_data",
    ifThen(isITIN("PrimarySSN"), isZero("EarnedIncomeCreditAmt")),
    "If 'PrimarySSN' in the Return Header is an ITIN, then Form 1040, 'EarnedIncomeCreditAmt' must be zero if an amount is entered.",
  ),
  rule(
    "F1040-038-03",
    "reject",
    "incorrect_data",
    ifThen(isITIN("PrimarySSN"), formAbsent("schedule_eic")),
    "If 'PrimarySSN' in the Return Header is an ITIN, then Schedule EIC (Form 1040) must not be present in the return.",
  ),
  rule(
    "F1040-039-05",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(2), isITIN("SpouseSSN")), isZero("EarnedIncomeCreditAmt")),
    "If the filing status of the return is married filing jointly and 'SpouseSSN' in the Return Header is an ITIN, then Form 1040, 'EarnedIncomeCreditAmt' must be zero if an amount is entered.",
  ),
  rule(
    "F1040-040-04",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(2), isITIN("SpouseSSN")), formAbsent("schedule_eic")),
    "If the filing status of the return is married filing jointly and 'SpouseSSN' in the Return Header is an ITIN, then Schedule EIC (Form 1040) must not be present in the return.",
  ),
  rule(
    "F1040-041-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("MustItemizeInd"), filingStatusIs(3)),
    "If Form 1040, 'MustItemizeInd' is checked, then the filing status of the return must be married filing separately.",
  ),
  rule(
    "F1040-042-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("TaxableSocSecAmt"), hasNonZero("SocSecBnftAmt")),
    "If Form 1040, 'TaxableSocSecAmt' has a non-zero value, then 'SocSecBnftAmt' must have a non-zero value.",
  ),
  rule(
    "F1040-064-06",
    "reject",
    "math_error",
    eqSum("TotalCreditsAmt", "CTCODCAmt", "ForeignTaxCreditAmt", "CreditForChildAndDepdCareAmt", "EducationCreditAmt", "RtrSavingsContributionsCrAmt", "ResidentialCleanEnergyCrAmt", "EgyEffcntHmImprvCrAmt", "OtherCreditsAmt"),
    "Form 1040, 'TotalCreditsAmt' must be equal to the sum of the following: 'CTCODCAmt' and Schedule 3 (Form 1040), [ 'ForeignTaxCreditAmt' and 'CreditForChildAndDepdCareAmt' and 'EducationCreditAmt' and 'RtrSavingsContributionsCrAmt' and 'ResidentialCleanEnergyCrAmt' and 'EgyEffcntHmImprvCrAmt' and 'OtherCreditsAmt' ].",
  ),
  rule(
    "F1040-065-05",
    "reject",
    "missing_data",
    any(hasNonZero("TotalIncomeAmt"), hasNonZero("AdjustedGrossIncomeAmt"), hasNonZero("TaxAmt"), hasNonZero("TotalTaxBeforeCrAndOthTaxesAmt"), hasNonZero("TotalCreditsAmt"), hasNonZero("TotalTaxAmt"), hasNonZero("TotalPaymentsAmt"), hasNonZero("TaxExemptInterestAmt"), hasNonZero("QualifiedDividendsAmt"), hasNonZero("IRADistributionsAmt"), hasNonZero("PensionsAnnuitiesAmt"), hasNonZero("SocSecBnftAmt")),
    "At least one of the following must have a non-zero value on Form 1040: 'TotalIncomeAmt' or 'AdjustedGrossIncomeAmt' or 'TaxAmt' or 'TotalTaxBeforeCrAndOthTaxesAmt' or 'TotalCreditsAmt' or 'TotalTaxAmt' or 'TotalPaymentsAmt' or 'TaxExemptInterestAmt' or 'QualifiedDividendsAmt' or 'IRADistributionsAmt' or 'PensionsAnnuitiesAmt' or 'SocSecBnftAmt'.",
  ),
  rule(
    "F1040-066-09",
    "reject",
    "math_error",
    eqSum("TotalPaymentsAmt", "WithholdingTaxAmt", "EstimatedTaxPaymentsAmt", "EarnedIncomeCreditAmt", "AdditionalChildTaxCreditAmt", "RefundableAmerOppCreditAmt", "form8689Amt", "ReconciledPremiumTaxCreditAmt", "RequestForExtensionAmt", "ExcessSocSecAndTier1RRTATaxAmt", "TotalFuelTaxCreditAmt", "OtherPaymentsAmt"),
    "Form 1040, 'TotalPaymentsAmt' must be equal to the sum of the following: 'WithholdingTaxAmt' and 'EstimatedTaxPaymentsAmt' and 'EarnedIncomeCreditAmt' and 'AdditionalChildTaxCreditAmt' and 'RefundableAmerOppCreditAmt' and 'form8689Amt' and Schedule 3 (Form 1040), [ 'ReconciledPremiumTaxCreditAmt' and 'RequestForExtensionAmt' and 'ExcessSocSecAndTier1RRTATaxAmt' and 'TotalFuelTaxCreditAmt' and 'OtherPaymentsAmt' ].",
  ),
  rule(
    "F1040-067-13",
    "reject",
    "missing_document",
    ifThen(gt("EarnedIncomeCreditAmt", 649), formPresent("schedule_eic")),
    "If Form 1040, 'EarnedIncomeCreditAmt' has a value greater than 649, then Schedule EIC (Form 1040) must be present in the return.",
  ),
  rule(
    "F1040-068-03",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 1040, 'EarnedIncomeCreditAmt' has a non-zero value and Schedule EIC (Form 1040) is not present, then the Primary or Spouse must be at least 25 years old but less than 65 years old.",
  ),
  rule(
    "F1040-070-03",
    "reject",
    "incorrect_data",
    ifThenUnless(hasValue("MustItemizeInd"), isZero("TotalItemizedOrStandardDedAmt"), formPresent("schedule_a")),
    "If Form 1040, 'MustItemizeInd' is checked, then 'TotalItemizedOrStandardDedAmt' must be zero if an amount is entered unless Schedule A (Form 1040) is present.",
  ),
  rule(
    "F1040-071-07",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Form 1040, 'WithholdingTaxAmt' must be less than the sum of the following: ['WagesSalariesAndTipsAmt' and 'TaxableInterestAmt' and 'OrdinaryDividendsAmt' and ('IRADistributionsAmt' or 'TaxableIRAAmt') and ( 'PensionsAnnuitiesAmt' or 'TotalTaxablePensionsAmt' ) and 'SocSecBnftAmt' and Schedule 1 (Form 1040), ( 'UnemploymentCompAmt' and 'TotalOtherIncomeAmt' ) and ( all Schedule C (Form 1040), 'TotalGrossReceiptsAmt' )] unless one of the following is true: (1) Form 1040, 'CapitalGainLossAmt' has a non-zero value; (2) Schedule 1 (Form 1040), 'OtherGainLossAmt' or 'RentalRealEstateIncomeLossAmt' or 'NetFarmProfitLossAmt' has a non-zero value; (3) Combat Pay has been excluded from wages.",
  ),
  rule(
    "F1040-087-02",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Form 1040, 'EarnedIncomeCreditAmt' must be zero if an amount is entered. The e-File database indicates the taxpayer is not allowed to claim the Earned Income Credit.",
  ),
  rule(
    "F1040-088-02",
    "reject",
    "incorrect_data",
    ifThen(any(eqStr("StateAbbreviationCd", "PR"), hasValue("ForeignAddress")), isZero("EarnedIncomeCreditAmt")),
    "If [ the Filer's address in the Return Header is a U.S. address and 'StateAbbreviationCd' has the value \"PR\" ] or [ the Filer's address in the Return Header is a foreign address ], then Form 1040, 'EarnedIncomeCreditAmt' in the return must be zero if an amount is entered.",
  ),
  rule(
    "F1040-097-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("PrimaryDeathDt"), noValue("ForeignAddress")),
    "If Form 1040, 'PrimaryDeathDt' has a value, then the Filer's address in the Return Header must not be a foreign address.",
  ),
  rule(
    "F1040-098-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("SpouseDeathDt"), noValue("ForeignAddress")),
    "If Form 1040, 'SpouseDeathDt' has a value, then the Filer's address in the Return Header must not be a foreign address.",
  ),
  rule(
    "F1040-111-02",
    "reject",
    "data_mismatch",
    eqSum("DependentCount", "ChldWhoLivedWithYouCnt", "OtherDependentsListedCnt"),
    "The total number of dependents in 'DependentDetail' on Form 1040 with 'DependentNameControlTxt' having a value must be equal to the sum of the following: 'ChldWhoLivedWithYouCnt' and 'OtherDependentsListedCnt'.",
  ),
  rule(
    "F1040-118-02",
    "reject",
    "unsupported",
    all(not(eqStr("StateAbbreviationCd", "AS")), not(eqStr("StateAbbreviationCd", "GU")), not(eqStr("StateAbbreviationCd", "VI")), not(eqStr("StateAbbreviationCd", "MP"))),
    "Tax returns from the U.S. Possessions of American Samoa, Guam, U.S. Virgin Islands and the Commonwealth of the Northern Mariana Islands may not be electronically filed.",
  ),
  rule(
    "F1040-126-02",
    "reject",
    "missing_document",
    ifThen(eqStr("WagesLiteralCd", "FEC"), formPresent("fec_record")),
    "If 'WagesLiteralCd' in [WagesNotShownSchedule] has the value  \"FEC\", then [FECRecord] must be present in the return.",
  ),
  rule(
    "F1040-129-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("EmployeeTIN"), any(all(eqField("EmployeeTIN", "PrimarySSN"), eqField("EmployeeNameControlTxt", "PrimaryNameControlTxt")), all(eqField("EmployeeTIN", "SpouseSSN"), eqField("EmployeeNameControlTxt", "SpouseNameControlTxt")))),
    "[ 'EmployeeTIN' and 'EmployeeNameControlTxt' ] in [FECRecord] must be the same as ( [ 'PrimarySSN' and 'PrimaryNameControlTxt' ] or ['SpouseSSN' and 'SpouseNameControlTxt' ] ) in the Return Header.",
  ),
  rule(
    "F1040-145-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("PowerOfAttorneySignedByInd"), noValue("SpouseDeathDt")),
    "If Form 1040, 'PowerOfAttorneySignedByInd' is checked, then 'SpouseDeathDt' must not have a value.",
  ),
  rule(
    "F1040-155-01",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("TaxableForeignPensionsTotalAmt"), eqStr("ForeignEmployerPensionCd", "FEP")),
    "If Form 1040, 'TaxableForeignPensionsTotalAmt' has a non-zero value, then 'ForeignEmployerPensionCd' must have the value \"FEP\".",
  ),
  rule(
    "F1040-156-01",
    "reject",
    "data_mismatch",
    sumOfAll("TaxableForeignPensionsTotalAmt", "ForeignPensionTaxableAmt"),
    "Form 1040, 'TaxableForeignPensionsTotalAmt' must be equal to the sum of 'ForeignPensionTaxableAmt' in all [FECRecord] present in the return.",
  ),
  rule(
    "F1040-157-05",
    "reject",
    "data_mismatch",
    ifThen(hasValue("RefundableAmerOppCreditAmt"), eqField("RefundableAmerOppCreditAmt", "RefundableAmerOppCreditAmt")),
    "Form 1040, 'RefundableAmerOppCreditAmt' must be equal to Form 8863, 'RefundableAmerOppCreditAmt'.",
  ),
  rule(
    "F1040-164-01",
    "reject",
    "missing_data",
    alwaysPass,
    "Form 8862 must be present in the return with Earned Income Credit Claimed Indicator checked. The e-File database indicates the taxpayer must file Form 8862 to claim Earned Income Credit after disallowance.",
  ),
  rule(
    "F1040-174-03",
    "reject",
    "incorrect_data",
    ifThen(hasValue("CommPropStateRtnInd"), all(filingStatusIs(1, 3, 4), formPresent("form8958"))),
    "If Form 1040, 'CommPropStateRtnInd' is checked, then [the filing status of the return must be single or married filing separately or head of household] and Form 8958 must be present.",
  ),
  rule(
    "F1040-175-02",
    "reject",
    "missing_data",
    ifThen(all(filingStatusIs(1, 3, 4), formPresent("form8958")), hasValue("CommPropStateRtnInd")),
    "If the filing status of the return is [single or married filing separately or head of household] and Form 8958 is present, then Form 1040, 'CommPropStateRtnInd' must be checked.",
  ),
  rule(
    "F1040-206-11",
    "reject",
    "incorrect_data",
    notGtNum("EarnedIncomeCreditAmt", 11950),
    "If Form 1040, 'EarnedIncomeCreditAmt' has a non-zero value and both Schedule E (Form 1040) and Form 4797 are not present in the return, then the sum of the following on Form 1040 must not be greater than 11950: 'TaxableInterestAmt' and 'TaxExemptInterestAmt' and 'OrdinaryDividendsAmt' and [CapitalGainLossAmt', if greater than zero].",
  ),
  rule(
    "F1040-231-01",
    "reject",
    "missing_data",
    ifThen(formPresent("form8814"), hasNonZero("childInterestAndDividendTaxAmt")),
    "If Form 8814 is present in the return, then Form 1040, 'childInterestAndDividendTaxAmt' must have a non-zero value.",
  ),
  rule(
    "F1040-240-01",
    "reject",
    "incorrect_data",
    ifThen(filingStatusIs(3), formAbsent("form8815")),
    "If the filing status of the return is married filing separately, then Form 8815 must not be present in the return.",
  ),
  rule(
    "F1040-263-01",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("EarnedIncomeCreditAmt"), formAbsent("form2555")),
    "If Form 1040, 'EarnedIncomeCreditAmt' has a non-zero value, then Form 2555 must not be present in the return.",
  ),
  rule(
    "F1040-278-03",
    "reject",
    "missing_document",
    ifThen(hasNonZero("form8689Amt"), formPresent("form8689")),
    "If Form 1040, 'form8689Amt' has a non-zero value, then Form 8689 must be present in the return.",
  ),
  rule(
    "F1040-310-03",
    "reject",
    "missing_data",
    ifThen(all(filingStatusIs(2), noValue("SpecialProcessingLiteralCd"), noValue("CombatZoneCd"), noValue("SpecialProcessingCodeTxt"), noValue("PrimaryDeathDt")), hasValue("PrimarySignaturePIN")),
    "If the filing status of the return is married filing jointly and each of the following does not have a value: ['SpecialProcessingLiteralCd' and 'CombatZoneCd' and 'SpecialProcessingCodeTxt' and 'PrimaryDeathDt'], then 'PrimarySignaturePIN' in the Return Header must have a value.",
  ),
  rule(
    "F1040-311-03",
    "reject",
    "missing_data",
    ifThen(all(filingStatusIs(2), noValue("SpecialProcessingLiteralCd"), noValue("CombatZoneCd"), noValue("SpecialProcessingCodeTxt"), noValue("SpouseDeathDt")), hasValue("SpouseSignaturePIN")),
    "If the filing status of the return is married filing jointly and each of the following does not have a value: ['SpecialProcessingLiteralCd' and 'CombatZoneCd' and 'SpecialProcessingCodeTxt' and 'SpouseDeathDt'], then 'SpouseSignaturePIN' in the Return Header must have a value.",
  ),
  rule(
    "F1040-312-03",
    "reject",
    "missing_data",
    ifThen(all(filingStatusIs(2), noValue("SpecialProcessingLiteralCd"), noValue("CombatZoneCd"), noValue("SpecialProcessingCodeTxt"), hasValue("PrimaryDeathDt"), hasValue("SpouseDeathDt")), hasValue("PrimarySignaturePIN")),
    "If the filing status of the return is married filing jointly and ['SpecialProcessingLiteralCd' and 'CombatZoneCd' and 'SpecialProcessingCodeTxt'] do not have values and both 'PrimaryDeathDt' and 'SpouseDeathDt' have values, then 'PrimarySignaturePIN' in the Return Header must have a value.",
  ),
  rule(
    "F1040-313-02",
    "reject",
    "missing_data",
    ifThen(all(filingStatusIs(2), hasValue("SpecialProcessingLiteralCd"), noValue("SpouseSignaturePIN")), hasValue("PrimarySignaturePIN")),
    "If the filing status of the return is married filing jointly and Form 1040, 'SpecialProcessingLiteralCd' has a value and 'SpouseSignaturePIN' in the Return Header does not have a value, then 'PrimarySignaturePIN' in the Return Header must have a value.",
  ),
  rule(
    "F1040-314-02",
    "reject",
    "missing_data",
    ifThen(all(filingStatusIs(2), hasValue("SpecialProcessingLiteralCd"), noValue("PrimarySignaturePIN")), hasValue("SpouseSignaturePIN")),
    "If the filing status of the return is married filing jointly and Form 1040, 'SpecialProcessingLiteralCd' has a value and 'PrimarySignaturePIN' in the Return Header does not have a value, then 'SpouseSignaturePIN' in the Return Header must have a value.",
  ),
  rule(
    "F1040-315-03",
    "reject",
    "missing_data",
    ifThen(all(filingStatusIs(2), hasValue("CombatZoneCd"), noValue("SpouseSignaturePIN")), hasValue("PrimarySignaturePIN")),
    "If the filing status of the return is married filing jointly and Form 1040, 'CombatZoneCd' has value and 'SpouseSignaturePIN' in the Return Header does not have a value, then 'PrimarySignaturePIN' in the Return Header must have a value.",
  ),
  rule(
    "F1040-316-03",
    "reject",
    "missing_data",
    ifThen(all(filingStatusIs(2), hasValue("CombatZoneCd"), noValue("PrimarySignaturePIN")), hasValue("SpouseSignaturePIN")),
    "If the filing status of the return is married filing jointly and Form 1040, 'CombatZoneCd' has value and 'PrimarySignaturePIN' in the Return Header does not have a value, then 'SpouseSignaturePIN' in the Return Header must have a value.",
  ),
  rule(
    "F1040-317-02",
    "reject",
    "missing_data",
    ifThen(all(filingStatusIs(2), hasValue("SpecialProcessingCodeTxt"), noValue("SpouseSignaturePIN")), hasValue("PrimarySignaturePIN")),
    "If the filing status of the return is married filing jointly and Form 1040, 'SpecialProcessingCodeTxt' has a value and 'SpouseSignaturePIN' in the Return Header does not have a value, then 'PrimarySignaturePIN' in the Return Header must have a value.",
  ),
  rule(
    "F1040-318-02",
    "reject",
    "missing_data",
    ifThen(all(filingStatusIs(2), hasValue("SpecialProcessingCodeTxt"), noValue("PrimarySignaturePIN")), hasValue("SpouseSignaturePIN")),
    "If the filing status of the return is married filing jointly and Form 1040, 'SpecialProcessingCodeTxt' has a value and 'PrimarySignaturePIN' in the Return Header does not have a value, then 'SpouseSignaturePIN' in the Return Header must have a value.",
  ),
  rule(
    "F1040-327-02",
    "reject",
    "incorrect_data",
    notGtNum("RefundableAmerOppCreditAmt", 89999),
    "If the filing status of the return is single or head of household or Qualifying Surviving Spouse and Form 1040, 'RefundableAmerOppCreditAmt' has a non-zero value, then 'AdjustedGrossIncomeAmt' must not be greater than 89999.",
  ),
  rule(
    "F1040-328-02",
    "reject",
    "incorrect_data",
    notGtNum("RefundableAmerOppCreditAmt", 179999),
    "If the filing status of the return is married filing jointly and Form 1040, 'RefundableAmerOppCreditAmt' has a non-zero value, then 'AdjustedGrossIncomeAmt' must not be greater than 179999.",
  ),
  rule(
    "F1040-339-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(1), noValue("PrimaryClaimAsDependentInd"), noValue("TotalBoxesCheckedCnt"), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 15000)),
    "If the filing status of the return is single and Form 1040, 'PrimaryClaimAsDependentInd' is not checked and 'TotalBoxesCheckedCnt' does not have a value and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 15000.",
  ),
  rule(
    "F1040-340-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(1), noValue("PrimaryClaimAsDependentInd"), eqNum("TotalBoxesCheckedCnt", 1), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 17000)),
    "If the filing status of the return is single and Form 1040, 'PrimaryClaimAsDependentInd' is not checked and 'TotalBoxesCheckedCnt' has the value 1 and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 17000.",
  ),
  rule(
    "F1040-341-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(1), noValue("PrimaryClaimAsDependentInd"), eqNum("TotalBoxesCheckedCnt", 2), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 19000)),
    "If the filing status of the return is single and Form 1040, 'PrimaryClaimAsDependentInd' is not checked and 'TotalBoxesCheckedCnt' has the value 2 and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 19000.",
  ),
  rule(
    "F1040-342-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(2), noValue("PrimaryClaimAsDependentInd"), noValue("SpouseClaimAsDependentInd"), noValue("TotalBoxesCheckedCnt"), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 30000)),
    "If the filing status of the return is married filing jointly and Form 1040, 'PrimaryClaimAsDependentInd' and 'SpouseClaimAsDependentInd' are both not checked and 'TotalBoxesCheckedCnt' does not have a value and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 30000.",
  ),
  rule(
    "F1040-343-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(2), noValue("PrimaryClaimAsDependentInd"), noValue("SpouseClaimAsDependentInd"), eqNum("TotalBoxesCheckedCnt", 1), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 31600)),
    "If the filing status of the return is married filing jointly and Form 1040, 'PrimaryClaimAsDependentInd' and 'SpouseClaimAsDependentInd' are both not checked and 'TotalBoxesCheckedCnt' has the value 1 and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 31600.",
  ),
  rule(
    "F1040-344-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(2), noValue("PrimaryClaimAsDependentInd"), noValue("SpouseClaimAsDependentInd"), eqNum("TotalBoxesCheckedCnt", 2), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 33200)),
    "If the filing status of the return is married filing jointly and Form 1040, 'PrimaryClaimAsDependentInd' and 'SpouseClaimAsDependentInd' are both not checked and 'TotalBoxesCheckedCnt' has the value 2 and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 33200.",
  ),
  rule(
    "F1040-345-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(2), noValue("PrimaryClaimAsDependentInd"), noValue("SpouseClaimAsDependentInd"), eqNum("TotalBoxesCheckedCnt", 3), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 34800)),
    "If the filing status of the return is married filing jointly and Form 1040, 'PrimaryClaimAsDependentInd' and 'SpouseClaimAsDependentInd' are both not checked and 'TotalBoxesCheckedCnt' has the value 3 and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 34800.",
  ),
  rule(
    "F1040-346-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(2), noValue("PrimaryClaimAsDependentInd"), noValue("SpouseClaimAsDependentInd"), eqNum("TotalBoxesCheckedCnt", 4), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 36400)),
    "If the filing status of the return is married filing jointly and Form 1040, 'PrimaryClaimAsDependentInd' and 'SpouseClaimAsDependentInd' are both not checked and 'TotalBoxesCheckedCnt' has the value 4 and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 36400.",
  ),
  rule(
    "F1040-347-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(3), noValue("PrimaryClaimAsDependentInd"), noValue("TotalBoxesCheckedCnt"), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 15000)),
    "If the filing status of the return is married filing separately and Form 1040, 'PrimaryClaimAsDependentInd' is not checked and 'TotalBoxesCheckedCnt' does not have a value and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 15000.",
  ),
  rule(
    "F1040-348-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(3), noValue("PrimaryClaimAsDependentInd"), eqNum("TotalBoxesCheckedCnt", 1), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 16600)),
    "If the filing status of the return is married filing separately and Form 1040, 'PrimaryClaimAsDependentInd' is not checked and 'TotalBoxesCheckedCnt' has the value 1 and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 16600.",
  ),
  rule(
    "F1040-349-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(3), noValue("PrimaryClaimAsDependentInd"), eqNum("TotalBoxesCheckedCnt", 2), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 18200)),
    "If the filing status of the return is married filing separately and Form 1040, 'PrimaryClaimAsDependentInd' is not checked and 'TotalBoxesCheckedCnt' has the value 2 and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 18200.",
  ),
  rule(
    "F1040-350-12",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(4), noValue("PrimaryClaimAsDependentInd"), noValue("TotalBoxesCheckedCnt"), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 22500)),
    "If the filing status of the return is head of household and Form 1040, 'PrimaryClaimAsDependentInd' is not checked and 'TotalBoxesCheckedCnt' does not have a value and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 22500.",
  ),
  rule(
    "F1040-351-12",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(4), noValue("PrimaryClaimAsDependentInd"), eqNum("TotalBoxesCheckedCnt", 1), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 24500)),
    "If the filing status of the return is head of household and Form 1040, 'PrimaryClaimAsDependentInd' is not checked and 'TotalBoxesCheckedCnt' has the value 1 and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 24500.",
  ),
  rule(
    "F1040-352-12",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(4), noValue("PrimaryClaimAsDependentInd"), eqNum("TotalBoxesCheckedCnt", 2), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 26500)),
    "If the filing status of the return is head of household and Form 1040, 'PrimaryClaimAsDependentInd' is not checked and 'TotalBoxesCheckedCnt' has the value 2 and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 26500.",
  ),
  rule(
    "F1040-353-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(5), noValue("PrimaryClaimAsDependentInd"), noValue("TotalBoxesCheckedCnt"), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 30000)),
    "If the filing status of the return is Qualifying Surviving Spouse and Form 1040, 'PrimaryClaimAsDependentInd' is not checked and 'TotalBoxesCheckedCnt' does not have a value and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 30000.",
  ),
  rule(
    "F1040-354-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(5), noValue("PrimaryClaimAsDependentInd"), eqNum("TotalBoxesCheckedCnt", 1), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 31600)),
    "If the filing status of the return is Qualifying Surviving Spouse and Form 1040, 'PrimaryClaimAsDependentInd' is not checked and 'TotalBoxesCheckedCnt' has the value 1 and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 31600.",
  ),
  rule(
    "F1040-355-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(5), noValue("PrimaryClaimAsDependentInd"), eqNum("TotalBoxesCheckedCnt", 2), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 33200)),
    "If the filing status of the return is Qualifying Surviving Spouse and Form 1040, 'PrimaryClaimAsDependentInd' is not checked and 'TotalBoxesCheckedCnt' has the value 2 and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 33200.",
  ),
  rule(
    "F1040-360-02",
    "reject",
    "math_error",
    alwaysPass,
    "If 'OtherAdjustmentsLitCd' in [OtherAdjustmentsStatement] has the value \"FORM 2555\", then the corresponding 'OtherAdjustmentsAmt' must be equal to the sum of all Forms 2555, 'HousingDeductionAmt'.",
  ),
  rule(
    "F1040-362-01",
    "reject",
    "multiple_documents",
    ifThen(filingStatusNot(2), formCountAtMost("form4563", 1)),
    "If the filing status of the return is not married filing jointly, then no more than one Form 4563 must be present.",
  ),
  rule(
    "F1040-366-02",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(3), eqStr("NRALiteralCd", "NRA")), noValue("ExemptSpouseNm")),
    "If the filing status of the return is married filing separately and Form 1040, 'NRALiteralCd' has the value \"NRA\", then 'ExemptSpouseNm' must not have a value.",
  ),
  rule(
    "F1040-367-02",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(3), eqStr("NRALiteralCd", "NRA")), noValue("ExemptSpouseNameControlTxt")),
    "If the filing status of the return is married filing separately and Form 1040, 'NRALiteralCd' has the value \"NRA\", then 'ExemptSpouseNameControlTxt' must not have a value.",
  ),
  rule(
    "F1040-377-12",
    "reject",
    "incorrect_data",
    notGtNum("AdjustedGrossIncomeAmt", 50434),
    "If the filing status of the return is not married filing jointly and the number of qualifying children on Schedule EIC (Form 1040) is one, then Form 1040, 'AdjustedGrossIncomeAmt' must not be greater than 50434.",
  ),
  rule(
    "F1040-378-12",
    "reject",
    "incorrect_data",
    notGtNum("AdjustedGrossIncomeAmt", 57554),
    "If the filing status of the return is married filing jointly and the number of qualifying children on Schedule EIC (Form 1040) is one, then Form 1040, 'AdjustedGrossIncomeAmt' must not be greater than 57554.",
  ),
  rule(
    "F1040-379-12",
    "reject",
    "incorrect_data",
    notGtNum("AdjustedGrossIncomeAmt", 57310),
    "If the filing status of the return is not married filing jointly and the number of qualifying children on Schedule EIC (Form 1040) is two, then Form 1040, 'AdjustedGrossIncomeAmt' must not be greater than 57310.",
  ),
  rule(
    "F1040-380-12",
    "reject",
    "incorrect_data",
    notGtNum("AdjustedGrossIncomeAmt", 64430),
    "If the filing status of the return is married filing jointly and the number of qualifying children on Schedule EIC (Form 1040) is two, then Form 1040, 'AdjustedGrossIncomeAmt' must not be greater than 64430.",
  ),
  rule(
    "F1040-381-12",
    "reject",
    "incorrect_data",
    notGtNum("AdjustedGrossIncomeAmt", 61555),
    "If the filing status of the return is not married filing jointly and the number of qualifying children on Schedule EIC (Form 1040) is three, then Form 1040, 'AdjustedGrossIncomeAmt' must not be greater than 61555.",
  ),
  rule(
    "F1040-382-12",
    "reject",
    "incorrect_data",
    notGtNum("AdjustedGrossIncomeAmt", 68675),
    "If the filing status of the return is married filing jointly and the number of qualifying children on Schedule EIC (Form 1040) is three, then Form 1040, 'AdjustedGrossIncomeAmt' must not be greater than 68675.",
  ),
  rule(
    "F1040-383-12",
    "reject",
    "incorrect_data",
    notGtNum("EarnedIncomeCreditAmt", 4328),
    "If the number of qualifying children on Schedule EIC (Form 1040) is one, then Form 1040, 'EarnedIncomeCreditAmt' must not be greater than 4328.",
  ),
  rule(
    "F1040-384-12",
    "reject",
    "incorrect_data",
    notGtNum("EarnedIncomeCreditAmt", 7152),
    "If the number of qualifying children on Schedule EIC (Form 1040) is two, then Form 1040, 'EarnedIncomeCreditAmt' must not be greater than 7152.",
  ),
  rule(
    "F1040-385-12",
    "reject",
    "incorrect_data",
    notGtNum("EarnedIncomeCreditAmt", 8046),
    "If the number of qualifying children on Schedule EIC (Form 1040) is three, then Form 1040, 'EarnedIncomeCreditAmt' must not be greater than 8046.",
  ),
  rule(
    "F1040-386-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(3), noValue("PrimaryClaimAsDependentInd"), eqNum("TotalBoxesCheckedCnt", 3), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 19800)),
    "If the filing status of the return is married filing separately and Form 1040, 'PrimaryClaimAsDependentInd' is not checked and 'TotalBoxesCheckedCnt' has the value 3 and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 19800.",
  ),
  rule(
    "F1040-387-11",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(3), noValue("PrimaryClaimAsDependentInd"), eqNum("TotalBoxesCheckedCnt", 4), noValue("MustItemizeInd"), noValue("modifiedStandardDeductionInd"), formAbsent("schedule_a")), eqNum("TotalItemizedOrStandardDedAmt", 21400)),
    "If the filing status of the return is married filing separately and Form 1040, 'PrimaryClaimAsDependentInd' is not checked and 'TotalBoxesCheckedCnt' has the value 4 and 'MustItemizeInd' is not checked and 'modifiedStandardDeductionInd' does not have a value and Schedule A (Form 1040) is not present in the return, then Form 1040, 'TotalItemizedOrStandardDedAmt' must equal 21400.",
  ),
  rule(
    "F1040-389-01",
    "reject",
    "incorrect_data",
    ifThen(filingStatusIs(3), formAbsent("form8863")),
    "If the filing status of the return is married filing separately, then Form 8863 must not be present.",
  ),
  rule(
    "F1040-395-01",
    "reject",
    "data_mismatch",
    eqSum("TotalBoxesCheckedCnt", "Primary65OrOlderInd", "PrimaryBlindInd", "Spouse65OrOlderInd", "SpouseBlindInd"),
    "Form 1040, 'TotalBoxesCheckedCnt' must be equal to the count of the following checkboxes which are checked: 'Primary65OrOlderInd' and 'PrimaryBlindInd' and 'Spouse65OrOlderInd' and 'SpouseBlindInd'.",
  ),
  rule(
    "F1040-402-02",
    "reject",
    "missing_data",
    ifThen(formPresent("fec_record"), any(eqStr("WagesLiteralCd", "FEC"), eqStr("ForeignEmployerPensionCd", "FEP"), hasNonZero("TaxableForeignPensionsTotalAmt"))),
    "If [FECRecord] is present in the return, then at least one of the following must be true: (1) [WagesNotShownSchedule] is present in the return with 'WagesLiteralCd' having the value \"FEC\" or (2) Form 1040, 'ForeignEmployerPensionCd' has the value \"FEP\" or (3) Form 1040, 'TaxableForeignPensionsTotalAmt' has a non-zero value.",
  ),
  rule(
    "F1040-405-02",
    "reject",
    "incorrect_data",
    ifThen(filingStatusIs(4), noValue("SpouseSignaturePIN")),
    "If the filing status of the return is head of household, then 'SpouseSignaturePIN' in the Return Header must not have a value.",
  ),
  rule(
    "F1040-406-02",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If the filing status of the return is married filing separately or head of household, then the Spouse must have no income (or loss).",
  ),
  rule(
    "F1040-446",
    "reject",
    "incorrect_data",
    ifThen(filingStatusIs(1, 4, 5), noValue("Spouse65OrOlderInd")),
    "If the filing status of the return is single or head of household or Qualifying Surviving Spouse, then Form 1040, 'Spouse65OrOlderInd' must not be checked.",
  ),
  rule(
    "F1040-447",
    "reject",
    "incorrect_data",
    ifThen(filingStatusIs(1, 4, 5), noValue("SpouseBlindInd")),
    "If the filing status of the return is single or head of household or Qualifying Surviving Spouse, then Form 1040, 'SpouseBlindInd' must not be checked.",
  ),
  rule(
    "F1040-448",
    "reject",
    "missing_data",
    alwaysPass,
    "Form 8862 must be present in the return with American Opportunity Tax Credit Claimed Indicator checked. The e-File database indicates the taxpayer must file Form 8862 to claim American Opportunity Tax Credit after disallowance.",
  ),
  rule(
    "F1040-455",
    "reject",
    "math_error",
    alwaysPass,
    "If 'NontxCombatPayElectionAmt' in the return has a non-zero value, then it must be equal to the sum of all Forms W-2, 'EmployersUseAmt' with corresponding 'EmployersUseCd' having the value \"Q\".",
  ),
  rule(
    "F1040-459",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(3), not(hasValue("SepdSpsFilingSepRetMeetsRqrInd"))), isZero("EarnedIncomeCreditAmt")),
    "If the filing status of the return is Married filing separately, and Schedule EIC (Form 1040), 'SepdSpsFilingSepRetMeetsRqrInd' is not checked, then 'EarnedIncomeCreditAmt' must be zero if an amount is entered.",
  ),
  rule(
    "F1040-461",
    "reject",
    "incorrect_data",
    ifThen(hasValue("SpouseClaimAsDependentInd"), filingStatusIs(2)),
    "If Form 1040, 'SpouseClaimAsDependentInd' is checked, then the filing status of the return must be married filing jointly.",
  ),
  rule(
    "F1040-462",
    "reject",
    "incorrect_data",
    noValue("RecoveryRebateCreditAmt"),
    "Form 1040, 'RecoveryRebateCreditAmt' must not have a value.",
  ),
  rule(
    "F1040-463",
    "reject",
    "incorrect_data",
    ifThen(hasValue("LumpSumElectionMethodInd"), hasNonZero("SocSecBnftAmt")),
    "If Form 1040, 'LumpSumElectionMethodInd' is checked, then 'SocSecBnftAmt' must have a non-zero value.",
  ),
  rule(
    "F1040-464",
    "reject",
    "incorrect_data",
    alwaysPass,
    "The [ sum of all 'WagesNotShownAmt' in [WagesNotShownSchedule] with the corresponding 'WagesLiteralCd' having the value \"FEC\" ] must be equal to [ the sum of 'ForeignEmployerCompensationAmt' in all [FECRecord] ].",
  ),
  rule(
    "F1040-466",
    "reject",
    "incorrect_data",
    ifThen(hasValue("QualifyingPersonSSN"), all(ssnNotEqual("QualifyingPersonSSN", "PrimarySSN"), ssnNotEqual("QualifyingPersonSSN", "SpouseSSN"))),
    "If Form 1040, 'QualifyingPersonSSN' has a value, then it must not be the same as [ 'PrimarySSN' or 'SpouseSSN' ] in the Return Header.",
  ),
  rule(
    "F1040-468",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Form 1040, 'RefundableAmerOppCreditAmt' must be zero if an amount is entered. The e-File database indicates the taxpayer is not allowed to claim the American Opportunity Tax Credit.",
  ),
  rule(
    "F1040-469",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form RRB 1042-S, 'SSN' or Form SSA 1042-S, 'SSN' is the same as 'PrimarySSN' in the Return Header, then a binary attachment with Description \"Signed Declaration\" must be present in the return.",
  ),
  rule(
    "F1040-470",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form RRB 1042-S, 'SSN' or Form SSA 1042-S, 'SSN' is the same as 'PrimarySSN' in the Return Header, then a binary attachment with Description \"Green Card\" must be present in the return.",
  ),
  rule(
    "F1040-471-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 8995, 'TotQlfyBusinessIncomeOrLossAmt' has a non-zero value, then Form 1040, 'AdjustedGrossIncomeAmt' minus (-) 'TotalItemizedOrStandardDedAmt' must not be greater than [383900, if the filing status of the return is married filing jointly] or [191950, for all other filing status].",
  ),
  rule(
    "F1040-472",
    "reject",
    "incorrect_data",
    ifThen(hasValue("NRASpouseTreatedAsResidentInd"), filingStatusIs(2)),
    "If checkbox 'NRASpouseTreatedAsResidentInd' is checked in the return, then the filing status of the return must be married filing jointly.",
  ),
  rule(
    "F1040-473",
    "alert",
    "missing_data",
    alwaysPass,
    "On your return, a claim for Other Forms Withholding, line 25c, did not have an EIN present on the Other Withholding Statement. The IRS may contact you for validation of the requested Other Withholding claim. Please visit https://www.irs.gov/newsroom/misleading-social-media-advice-leads-to-false-claims-for-fuel-tax-credit-sick-and-family-leave-credit-household-employment-taxes-faqs-help-address-common-questions-next-steps-for-those-receiving-irs and the line 25c form instructions for additional information.",
  ),
  rule(
    "F1040-474",
    "alert",
    "information",
    alwaysPass,
    "A high claim for Other Forms Withholding, line 25c, was claimed on your return. The IRS may contact you for validation of the requested Other Withholding claim. Please visit https://www.irs.gov/newsroom/misleading-social-media-advice-leads-to-false-claims-for-fuel-tax-credit-sick-and-family-leave-credit-household-employment-taxes-faqs-help-address-common-questions-next-steps-for-those-receiving-irs and the line 25c form instructions for additional information.",
  ),
  rule(
    "F1040-516-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 1040, 'PrimaryClaimAsDependentInd' is not checked, then 'PrimarySSN' must not be the same as a Dependent SSN on another return filed for the same tax year. Visit www.irs.gov/identity-theft-fraud-scams/identity-theft-dependents for additional information. To electronically file with this duplicate condition, an Identity Protection Personal Identification Number (IP PIN) will be required. If you wish to get an IP PIN and you don't already have an account on IRS.gov, then you must register to validate your identity. Please visit www.irs.gov/getanippin for further information and resubmit your return with an IP PIN.",
  ),
  rule(
    "F1040-518-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 1040, 'SpouseClaimAsDependentInd' is not checked, then 'SpouseSSN' must not be the same as a Dependent SSN on another return filed for the same tax year. Visit www.irs.gov/identity-theft-fraud-scams/identity-theft-dependents for additional information. To electronically file with this duplicate condition, an Identity Protection Personal Identification Number (IP PIN) will be required. If you wish to get an IP PIN and you don't already have an account on IRS.gov, then you must register to validate your identity. Please visit www.irs.gov/getanippin for further information and resubmit your return with an IP PIN.",
  ),
  rule(
    "F1040-525-03",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "If 'PINTypeCd' in the Return Header has the value \"Self-Select On-Line\" and the filing status of the return is married filing jointly and Form 1040, [ 'SpecialProcessingLiteralCd' and 'CombatZoneCd' and 'SpecialProcessingCodeTxt' and 'PrimaryDeathDt' ] do not have values, then 'PrimaryBirthDt' in the Return Header must match the e-File database.",
  ),
  rule(
    "F1040-526-03",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "If 'PINTypeCd' in the Return Header has the value \"Self-Select On-Line\" and the filing status of the return is married filing jointly and Form 1040, [ 'SpecialProcessingLiteralCd' and 'CombatZoneCd' and 'SpecialProcessingCodeTxt' and 'SpouseDeathDt' ] do not have values, then 'SpouseBirthDt' in the Return Header must match the e-File database.",
  ),
  rule(
    "F1040-616",
    "alert",
    "information",
    alwaysPass,
    "The primary filer on the return was previously claimed as a dependent on another accepted return for the same tax year. Visit www.irs.gov/identity-theft-fraud-scams/identity-theft-dependents for additional information.",
  ),
  rule(
    "F1040-618",
    "alert",
    "information",
    alwaysPass,
    "The spouse filer on the return was previously claimed as a dependent on another accepted return for the same tax year. Visit www.irs.gov/identity-theft-fraud-scams/identity-theft-dependents for additional information.",
  ),
  rule(
    "F1040-900",
    "reject_and_stop",
    "database",
    alwaysPass,
    "A Qualifying Child SSN on Schedule EIC (Form 1040) has been systemically locked because the IRS does not accept a replaced SSN as valid for tax filing.",
  ),
  rule(
    "F1040-901",
    "reject_and_stop",
    "database",
    alwaysPass,
    "A Student SSN on Form 8863 has been systemically locked because the IRS does not accept a replaced SSN as valid for tax filing.",
  ),
];
