/**
 * MeF Business Rules: F5695
 * Auto-generated from 1040_Business_Rules_2025v3.0.csv
 * 76 rules (76 implemented, 0 stubs)
 */

import type { RuleDef } from "../../../../core/validation/types.ts";
import { rule, all, alwaysPass, any, eqField, eqMin, eqMinNum, eqProduct, eqStr, eqSum, filingStatusIs, formCountAtMost, gt, hasNonZero, hasValue, ifThen, isZero, lt, matchesHeaderSSN, noValue, not, notGtNum, } from "../../../../core/validation/mod.ts";

export const F5695_RULES: readonly RuleDef[] = [
  rule(
    "F5695-001",
    "reject",
    "incorrect_data",
    matchesHeaderSSN("SSN"),
    "Form 5695, 'SSN' must be equal to 'PrimarySSN' or 'SpouseSSN' in the Return Header.",
  ),
  rule(
    "F5695-002",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If two Forms 5695 are present in the return, then their SSN's must not be equal.",
  ),
  rule(
    "F5695-003-05",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If there are two Forms 5695 in the return and their SSNs are not equal, then one of the forms must not have values in the 'ResidentialCleanEnergyCrGrp'.",
  ),
  rule(
    "F5695-007-04",
    "reject",
    "missing_data",
    ifThen(hasValue("HomeAddress"), all(eqStr("HomeLocatedInUSAInd", "Yes"), eqStr("OriginalUserInd", "Yes"), eqStr("FiveYearUseExpectationInd", "Yes"))),
    "If Form 5695, 'HomeAddress' has a value, then 'HomeLocatedInUSAInd' and 'OriginalUserInd' and 'FiveYearUseExpectationInd' must have a choice of \"Yes\" indicated.",
  ),
  rule(
    "F5695-015-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("QlfyFuelCellPropertyInUSInd", "No"), all(noValue("QlfyFuelCellPropertyHmAddress"), noValue("FuelCellPropKWCapNum"))),
    "If Form 5695, 'QlfyFuelCellPropertyInUSInd' has a choice of \"No\" indicated, then 'QlfyFuelCellPropertyHmAddress' and 'FuelCellPropKWCapNum' must not have a value and [ 'FuelCellPropCostAmt' and 'FuelCellPropStdPctCrAmt' and 'FuelCellPropKWCapAmt' and 'FuelCellPropAllwblCostAmt'] must have a zero value if an amount is entered.",
  ),
  rule(
    "F5695-016-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("QlfyFuelCellPropertyInUSInd", "Yes"), hasValue("QlfyFuelCellPropertyHmAddress")),
    "If Form 5695, 'QlfyFuelCellPropertyInUSInd' has a choice of \"Yes\" indicated, then 'QlfyFuelCellPropertyHmAddress' must have a value.",
  ),
  rule(
    "F5695-029-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("TotalEnergyCreditsStdPctCrAmt"), eqField("TotalEnergyCreditsStdPctCrAmt", "TotalEnergyCreditsAmt")),
    "Form 5695, 'TotalEnergyCreditsStdPctCrAmt' must be equal to 30% (0.30) of 'TotalEnergyCreditsAmt'.",
  ),
  rule(
    "F5695-030-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("FuelCellPropStdPctCrAmt"), eqField("FuelCellPropStdPctCrAmt", "FuelCellPropCostAmt")),
    "Form 5695, 'FuelCellPropStdPctCrAmt' must be equal to 30% (0.30) of 'FuelCellPropCostAmt'.",
  ),
  rule(
    "F5695-032",
    "reject",
    "incorrect_data",
    ifThen(gt("QlfyBatteryStorageTechCostAmt", 0), eqStr("QlfyBatteryStorageTechInd", "Yes")),
    "If Form 5695, 'QlfyBatteryStorageTechCostAmt' has an amount greater than zero, then 'QlfyBatteryStorageTechInd' must have a choice of \"Yes\" indicated.",
  ),
  rule(
    "F5695-033",
    "reject",
    "incorrect_data",
    ifThen(eqStr("QlfyBatteryStorageTechInd", "No"), isZero("QlfyBatteryStorageTechCostsAmt")),
    "If Form 5695, 'QlfyBatteryStorageTechInd' has a choice of \"No\" indicated, then 'QlfyBatteryStorageTechCostsAmt' must have a zero value if an amount is entered.",
  ),
  rule(
    "F5695-034-01",
    "reject",
    "incorrect_data",
    ifThen(any(eqStr("HomeLocatedInUSAInd", "No"), eqStr("OriginalUserInd", "No"), eqStr("FiveYearUseExpectationInd", "No")), all(noValue("InsulationOrSysHtStdPctCrAmt"), noValue("TotalExtrDoorsCreditAmt"), noValue("ExtrWndwSkylightStdPctCrAmt"))),
    "If Form 5695, [ 'HomeLocatedInUSAInd' or 'OriginalUserInd' or 'FiveYearUseExpectationInd' in 'EgyEffcntHmImprvCrGrp' ] have a choice of \"No\" indicated, then ['InsulationOrSysHtStdPctCrAmt' in 'EgyEffcntHmImprvCrGrp' ] and [ 'TotalExtrDoorsCreditAmt' in 'ExteriorDoorEgyStarRqrGrp' in 'EgyEffcntHmImprvCrGrp' ] and ['ExtrWndwSkylightStdPctCrAmt' in 'ExtrWndwSkyltEgyStarRqrGrp' in 'EgyEffcntHmImprvCrGrp' ] must not have a value.",
  ),
  rule(
    "F5695-035",
    "reject",
    "incorrect_data",
    ifThen(all(eqStr("HomeLocatedInUSAInd", "Yes"), eqStr("OriginalUserInd", "Yes"), eqStr("FiveYearUseExpectationInd", "Yes")), hasValue("HomeAddress")),
    "If Form 5695, 'HomeLocatedInUSAInd' and 'OriginalUserInd' and 'FiveYearUseExpectationInd' have a choice of \"Yes\" indicated, then 'HomeAddress' must have a value.",
  ),
  rule(
    "F5695-036",
    "reject",
    "incorrect_data",
    ifThen(any(eqStr("HomeLocatedInUSAInd", "No"), eqStr("OriginalUserInd", "No"), eqStr("FiveYearUseExpectationInd", "No")), noValue("HomeAddress")),
    "If Form 5695, 'HomeLocatedInUSAInd' or 'OriginalUserInd' or 'FiveYearUseExpectationInd' have a choice of \"No\" indicated, then 'HomeAddress' must not have a value.",
  ),
  rule(
    "F5695-037-01",
    "reject",
    "incorrect_data",
    ifThen(any(gt("InsulationOrSysHtStdPctCrAmt", 0), gt("TotalExtrDoorsCreditAmt", 0), gt("ExtrWndwSkylightStdPctCrAmt", 0)), all(eqStr("HomeLocatedInUSAInd", "Yes"), eqStr("OriginalUserInd", "Yes"), eqStr("FiveYearUseExpectationInd", "Yes"), eqStr("ImprvRltdToConstMainHomeInd", "No"))),
    "If Form 5695, [ 'InsulationOrSysHtStdPctCrAmt' in 'EgyEffcntHmImprvCrGrp' ] or [ 'TotalExtrDoorsCreditAmt' in 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] or  ['ExtrWndwSkylightStdPctCrAmt' in 'ExtrWndwSkyltEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] has a value greater than zero, then [ 'HomeLocatedInUSAInd' and 'OriginalUserInd' and 'FiveYearUseExpectationInd' in 'EgyEffcntHmImprvCrGrp' ] must all have a choice of \"Yes\" indicated and [ 'ImprvRltdToConstMainHomeInd' in 'EgyEffcntHmImprvCrGrp' ] must have a choice of \"No\".",
  ),
  rule(
    "F5695-038-01",
    "reject",
    "incorrect_data",
    ifThen(noValue("JointOccupancyInd"), eqProduct("InsulationOrSysHtStdPctCrAmt", "InsulationOrSysHtGnLossCostAmt", 0.30)),
    "If Form 5695, ['JointOccupancyInd' in 'EgyEffcntHmImprvCrGrp'] is not checked, then 'InsulationOrSysHtStdPctCrAmt' must be equal to 30% (0.30) of 'InsulationOrSysHtGnLossCostAmt'.",
  ),
  rule(
    "F5695-039-02",
    "reject",
    "incorrect_data",
    ifThen(noValue("JointOccupancyInd"), eqProduct("MostExpnsExtrDoorsStdPctCrAmt", "MostExpnsExtrDoorCostAmt", 0.30)),
    "If Form 5695, [ 'JointOccupancyInd' in 'EgyEffcntHmImprvCrGrp' ] is not checked, then [ 'MostExpnsExtrDoorsStdPctCrAmt' in 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] must be equal to 30% (0.30) of [ 'MostExpnsExtrDoorCostAmt' in 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-040-02",
    "reject",
    "incorrect_data",
    ifThen(noValue("JointOccupancyInd"), eqProduct("OtherQlfyExtrDoorsStdPctCrAmt", "OtherQlfyExtrDoorsCostAmt", 0.30)),
    "If Form 5695, [ 'JointOccupancyInd' in 'EgyEffcntHmImprvCrGrp' ] is not checked, then [ 'OtherQlfyExtrDoorsStdPctCrAmt' in 'OthExteriorDoorEgyStarRqrGrp' from 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] must be equal to 30% (0.30) of [ 'OtherQlfyExtrDoorsCostAmt' in 'OthExteriorDoorEgyStarRqrGrp' from 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-041-02",
    "reject",
    "incorrect_data",
    ifThen(noValue("JointOccupancyInd"), eqProduct("ExtrWndwSkylightStdPctCrAmt", "ExteriorWndwOrSkylightCostAmt", 0.30)),
    "If Form 5695, [ 'JointOccupancyInd' in 'EgyEffcntHmImprvCrGrp' ] is not checked, then [ 'ExtrWndwSkylightStdPctCrAmt' in 'ExtrWndwSkyltEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] must be equal to 30% (0.30) of [ 'ExteriorWndwOrSkylightCostAmt' in 'ExtrWndwSkyltEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-042",
    "reject",
    "missing_data",
    ifThen(all(eqStr("QlfyEnergyPropCostsUSHomeInd", "Yes"), eqStr("OriginallyPlacedInServiceInd", "Yes")), hasValue("QualifiedEnergyPropertyAddress")),
    "If Form 5695, 'QlfyEnergyPropCostsUSHomeInd' and 'OriginallyPlacedInServiceInd' have a choice of \"Yes\" indicated, then 'QualifiedEnergyPropertyAddress' must have a value.",
  ),
  rule(
    "F5695-043",
    "reject",
    "missing_data",
    ifThen(hasValue("QualifiedEnergyPropertyAddress"), all(eqStr("QlfyEnergyPropCostsUSHomeInd", "Yes"), eqStr("OriginallyPlacedInServiceInd", "Yes"))),
    "If Form 5695, 'QualifiedEnergyPropertyAddress' has a value, then 'QlfyEnergyPropCostsUSHomeInd' and 'OriginallyPlacedInServiceInd' must have a choice of \"Yes\" indicated.",
  ),
  rule(
    "F5695-044-01",
    "reject",
    "incorrect_data",
    ifThen(any(eqStr("QlfyEnergyPropCostsUSHomeInd", "No"), eqStr("OriginallyPlacedInServiceInd", "No")), all(noValue("QualifiedEnergyPropertyAddress"), noValue("CentralAirCondCostStdPctCrAmt"), noValue("NatGasPrpnOilWtrHtrStdPctCrAmt"), noValue("NatGasPrpnOilHotWtrBlrPctAmt"), noValue("PanelboardCktFeederStdPctCrAmt"), noValue("HtPumpWtrHeaterBmssStdPctCrAmt"))),
    "If Form 5695, [ 'QlfyEnergyPropCostsUSHomeInd' or 'OriginallyPlacedInServiceInd' in 'EgyEffcntHmImprvCrGrp' ] have a choice of \"No\" indicated, then  ['QualifiedEnergyPropertyAddress' in 'EgyEffcntHmImprvCrGrp' ] and ['CentralAirCondCostStdPctCrAmt' in 'CentralAirConditionerGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'NatGasPrpnOilWtrHtrStdPctCrAmt' in 'WaterHeaterGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'NatGasPrpnOilHotWtrBlrPctAmt' in 'FrncHotWtrBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'PanelboardCktFeederStdPctCrAmt' in 'EnablingPropertyGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'HtPumpWtrHeaterBmssStdPctCrAmt' in 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] must not have a value greater than zero or blank.",
  ),
  rule(
    "F5695-045-01",
    "reject",
    "incorrect_data",
    ifThen(any(hasValue("QualifiedEnergyPropertyAddress"), gt("CentralAirCondCostStdPctCrAmt", 0), gt("NatGasPrpnOilWtrHtrStdPctCrAmt", 0), gt("NatGasPrpnOilHotWtrBlrPctAmt", 0), gt("PanelboardCktFeederStdPctCrAmt", 0), gt("HtPumpWtrHeaterBmssStdPctCrAmt", 0)), all(eqStr("QlfyEnergyPropCostsUSHomeInd", "Yes"), eqStr("OriginallyPlacedInServiceInd", "Yes"))),
    "If Form 5695, [ 'QualifiedEnergyPropertyAddress' in 'EgyEffcntHmImprvCrGrp' ] or [ 'CentralAirCondCostStdPctCrAmt' in 'CentralAirConditionerGrp' from 'EgyEffcntHmImprvCrGrp'] or [ 'NatGasPrpnOilWtrHtrStdPctCrAmt' in 'WaterHeaterGrp' from 'EgyEffcntHmImprvCrGrp' ] or [ 'NatGasPrpnOilHotWtrBlrPctAmt' in 'FrncHotWtrBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] or [ 'PanelboardCktFeederStdPctCrAmt' in 'EnablingPropertyGrp' from 'EgyEffcntHmImprvCrGrp' ] or [ 'HtPumpWtrHeaterBmssStdPctCrAmt' in 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] has an entry or a value greater than zero, then [ 'QlfyEnergyPropCostsUSHomeInd' and 'OriginallyPlacedInServiceInd' in 'EgyEffcntHmImprvCrGrp' ] must have a choice of \"Yes\" indicated.",
  ),
  rule(
    "F5695-046-02",
    "reject",
    "incorrect_data",
    ifThen(noValue("JointOccupancyInd"), eqProduct("CentralAirCondCostStdPctCrAmt", "CentralAirCondCostAmt", 0.30)),
    "If Form 5695, [ 'JointOccupancyInd' in 'EgyEffcntHmImprvCrGrp' ] is not checked, then [ 'CentralAirCondCostStdPctCrAmt' in 'CentralAirConditionerGrp' from 'EgyEffcntHmImprvCrGrp' ] must be equal to 30% (0.30) of  [ 'CentralAirCondCostAmt' in 'CentralAirConditionerGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-047-02",
    "reject",
    "incorrect_data",
    ifThen(noValue("JointOccupancyInd"), eqProduct("NatGasPrpnOilWtrHtrStdPctCrAmt", "NatGasPrpnOilWtrHtrCostAmt", 0.30)),
    "If Form 5695, [ 'JointOccupancyInd' in 'EgyEffcntHmImprvCrGrp' ] is not checked, then [ 'NatGasPrpnOilWtrHtrStdPctCrAmt' in 'WaterHeaterGrp' from 'EgyEffcntHmImprvCrGrp' ] must be equal to 30% (0.30) of [ 'NatGasPrpnOilWtrHtrCostAmt' in 'WaterHeaterGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-048-02",
    "reject",
    "incorrect_data",
    ifThen(noValue("JointOccupancyInd"), eqProduct("NatGasPrpnOilHotWtrBlrPctAmt", "NatGasPrpnOilHotWtrBlrCostAmt", 0.30)),
    "If Form 5695, [ 'JointOccupancyInd' in 'EgyEffcntHmImprvCrGrp' ] is not checked, then [ 'NatGasPrpnOilHotWtrBlrPctAmt' in 'FrncHotWtrBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] must be equal to 30% (0.30) of [ 'NatGasPrpnOilHotWtrBlrCostAmt' in 'FrncHotWtrBlrGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-049-02",
    "reject",
    "incorrect_data",
    ifThen(noValue("JointOccupancyInd"), eqProduct("PanelboardCktFeederStdPctCrAmt", "PanelboardCktFeederCostAmt", 0.30)),
    "If Form 5695, [ 'JointOccupancyInd' in 'EgyEffcntHmImprvCrGrp' ] is not checked, then [ 'PanelboardCktFeederStdPctCrAmt' in 'EnablingPropertyGrp' from 'EgyEffcntHmImprvCrGrp' ] must be equal to 30% (0.30) of [ 'PanelboardCktFeederCostAmt' in 'EnablingPropertyGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-050-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("MainHomeEgyAuditCostInd", "No"), all(isZero("MainHomeEgyAuditCostAmt"), isZero("MainHomeEgyAuditStdPctCrAmt"))),
    "If Form 5695 'MainHomeEgyAuditCostInd' has a choice of \"No\" indicated, then 'MainHomeEgyAuditCostAmt' and 'MainHomeEgyAuditStdPctCrAmt' must not have a value other than zero.",
  ),
  rule(
    "F5695-051-01",
    "reject",
    "incorrect_data",
    ifThen(noValue("JointOccupancyInd"), eqProduct("MainHomeEgyAuditStdPctCrAmt", "MainHomeEgyAuditCostAmt", 0.30)),
    "If Form 5695, ['JointOccupancyInd' in 'EgyEffcntHmImprvCrGrp'] is not checked, then 'MainHomeEgyAuditStdPctCrAmt' must be equal to 30% (0.30) of 'MainHomeEgyAuditCostAmt'.",
  ),
  rule(
    "F5695-052",
    "reject",
    "incorrect_data",
    ifThen(any(gt("MainHomeEgyAuditCostAmt", 0), gt("MainHomeEgyAuditStdPctCrAmt", 0)), eqStr("MainHomeEgyAuditCostInd", "Yes")),
    "If Form 5695, 'MainHomeEgyAuditCostAmt' or 'MainHomeEgyAuditStdPctCrAmt' has a value greater than zero, then 'MainHomeEgyAuditCostInd' must have a choice of \"Yes\" indicated.",
  ),
  rule(
    "F5695-053-01",
    "reject",
    "math_error",
    eqSum("EgyEffcntImprvCreditSubtlAmt", "InsulationOrSysHtStdPctCrAmt", "TotalExtrDoorsCreditAmt", "ExtrWndwSkylightStdPctCrAmt", "CentralAirCondCostStdPctCrAmt", "NatGasPrpnOilWtrHtrStdPctCrAmt", "NatGasPrpnOilHotWtrBlrPctAmt", "PanelboardCktFeederStdPctCrAmt", "MainHomeEgyAuditStdPctCrAmt"),
    "Form 5695, [ 'EgyEffcntImprvCreditSubtlAmt' in 'EgyEffcntHmImprvCrGrp' ] must equal the sum of [ 'InsulationOrSysHtStdPctCrAmt' in 'EgyEffcntHmImprvCrGrp' ] and  ['TotalExtrDoorsCreditAmt' in 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'ExtrWndwSkylightStdPctCrAmt' in 'ExtrWndwSkyltEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'CentralAirCondCostStdPctCrAmt' in 'CentralAirConditionerGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'NatGasPrpnOilWtrHtrStdPctCrAmt' in 'WaterHeaterGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'NatGasPrpnOilHotWtrBlrPctAmt' in 'FrncHotWtrBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] and  ['PanelboardCktFeederStdPctCrAmt' in 'EnablingPropertyGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'MainHomeEgyAuditStdPctCrAmt' in 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-054-02",
    "reject",
    "incorrect_data",
    ifThen(noValue("JointOccupancyInd"), eqProduct("HtPumpWtrHeaterBmssStdPctCrAmt", "HtPumpWtrHeaterBmssCostAmt", 0.30)),
    "If Form 5695, [ 'JointOccupancyInd' in 'EgyEffcntHmImprvCrGrp' ] is not checked, then [ 'HtPumpWtrHeaterBmssStdPctCrAmt' in 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] must be equal to 30% (0.30) of [ 'HtPumpWtrHeaterBmssCostAmt' in 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-056",
    "reject",
    "data_mismatch",
    ifThen(eqStr("AdjustedCreditLimitCd", "MORE THAN ONE MAIN HOME"), filingStatusIs(2)),
    "If Form 5695, 'AdjustedCreditLimitCd' has the value \"MORE THAN ONE MAIN HOME\", then the filing status of the return must be married filing jointly.",
  ),
  rule(
    "F5695-057",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 5695, 'AdjustedCreditLimitCd' has the value \"MORE THAN ONE MAIN HOME\", then there must be two instances of Form 5695 present in the return.",
  ),
  rule(
    "F5695-058",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Form 5695, 'AdjustedCreditLimitCd' must only have the value \"MORE THAN ONE MAIN HOME\" on one instance of Form 5695.",
  ),
  rule(
    "F5695-059",
    "reject",
    "incorrect_data",
    ifThen(gt("AdjustedCreditLimitAmt", 3200), eqStr("AdjustedCreditLimitCd", "MORE THAN ONE MAIN HOME")),
    "If Form 5695, [ 'AdjustedCreditLimitAmt' in 'EgyEffcntHmImprvCrGrp' ] has a value greater than 3200, then 'AdjustedCreditLimitCd' must have the value \"MORE THAN ONE MAIN HOME\".",
  ),
  rule(
    "F5695-061",
    "reject",
    "incorrect_data",
    notGtNum("AdjustedCreditLimitAmt", 6400),
    "Form 5695, [ 'AdjustedCreditLimitAmt' and 'EgyEffcntHmImprvCrAmt' in 'EgyEffcntHmImprvCrGrp' ] must not be greater than 6400.",
  ),
  rule(
    "F5695-062",
    "reject",
    "incorrect_data",
    ifThen(gt("AdjustedCreditLimitAmt", 3200), filingStatusIs(2)),
    "If Form 5695 ['AdjustedCreditLimitAmt' or 'EgyEffcntHmImprvCrAmt' in 'EgyEffcntHmImprvCrGrp'] is greater than 3200, then the filing status of the return must be married filing jointly.",
  ),
  rule(
    "F5695-064",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 5695, [ 'JointOccupancyInd' in 'ResidentialCleanEnergyCrGrp' ] is checked, then at least one instance of [JointOccupancyStatement] must be attached to 'JointOccupancyInd'.",
  ),
  rule(
    "F5695-065",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 5695, [ 'JointOccupancyInd' in 'EgyEffcntHmImprvCrGrp' ] is checked, then at least one instance of [JointOccupancyStatement] must be attached to 'JointOccupancyInd'.",
  ),
  rule(
    "F5695-066",
    "reject",
    "incorrect_data",
    ifThen(lt("FuelCellPropKWCapNum", 0.50), isZero("FuelCellPropKWCapNum")),
    "If Form 5695, [ 'FuelCellPropKWCapNum' in 'ResidentialCleanEnergyCrGrp' ] has a value less than 0.50, then [ 'FuelCellPropKWCapNum' in 'ResidentialCleanEnergyCrGrp' ] must be equal to zero if an amount is entered.",
  ),
  rule(
    "F5695-067",
    "reject",
    "math_error",
    ifThen(hasNonZero("FuelCellPropKWCapAmt"), eqProduct("FuelCellPropKWCapAmt", "FuelCellPropKWCapNum", 1000)),
    "If Form 5695, [ 'FuelCellPropKWCapAmt' in 'ResidentialCleanEnergyCrGrp' ] has a non-zero value, then it must be equal to [ 'FuelCellPropKWCapNum' in 'ResidentialCleanEnergyCrGrp' ] multiplied by 1000.",
  ),
  rule(
    "F5695-068",
    "reject",
    "incorrect_data",
    notGtNum("InsulationOrSysHtStdPctCrAmt", 1200),
    "Form 5695, [ 'InsulationOrSysHtStdPctCrAmt' in 'EgyEffcntHmImprvCrGrp' ] must not be greater than 1200.",
  ),
  rule(
    "F5695-069",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 5695, [ 'MostExpnsExtrDoorCostAmt' in 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then [ 'MostExpnsExtrDoorQMID' in 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] must be present unless a binary attachment or [GeneralDependencySmall] with description beginning with \"Substantiate QMID\" is present in the return.",
  ),
  rule(
    "F5695-070",
    "reject",
    "incorrect_data",
    notGtNum("MostExpnsExtrDoorsStdPctCrAmt", 250),
    "Form 5695, [ 'MostExpnsExtrDoorsStdPctCrAmt' in 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] must not be greater than 250.",
  ),
  rule(
    "F5695-071",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 5695, [ 'CostAmt' in 'NextMostExpnsExtrDoorGrp from 'OthExteriorDoorEgyStarRqrGrp' from 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then [ 'QMID' in 'NextMostExpnsExtrDoorGrp from 'OthExteriorDoorEgyStarRqrGrp' from 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] must be present unless a binary attachment or [GeneralDependencySmall] with description beginning with \"Substantiate QMID\" is present in the return.",
  ),
  rule(
    "F5695-072",
    "reject",
    "math_error",
    alwaysPass,
    "If Form 5695, [ 'NextMostExpnsExtrDoorCostAmt' in 'OthExteriorDoorEgyStarRqrGrp' from 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then it must equal the sum of all instances of [ 'CostAmt' in 'NextMostExpnsExtrDoorGrp' from 'OthExteriorDoorEgyStarRqrGrp' from 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-073",
    "reject",
    "math_error",
    ifThen(hasNonZero("TotalOtherQlfyExtrDoorsCostAmt"), eqSum("TotalOtherQlfyExtrDoorsCostAmt", "NextMostExpnsExtrDoorCostAmt", "OtherQlfyExtrDoorsCostAmt")),
    "If [ 'TotalOtherQlfyExtrDoorsCostAmt' in 'OthExteriorDoorEgyStarRqrGrp' from 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then it must be equal to the sum of [ 'NextMostExpnsExtrDoorCostAmt' in 'OthExteriorDoorEgyStarRqrGrp' from 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'OtherQlfyExtrDoorsCostAmt' in 'OthExteriorDoorEgyStarRqrGrp' from 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-074",
    "reject",
    "math_error",
    notGtNum("TotalExtrDoorsCreditAmt", 500),
    "If Form 5695, [ 'TotalExtrDoorsCreditAmt' in 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then it must be equal to the sum of [ 'MostExpnsExtrDoorsStdPctCrAmt' in 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'OtherQlfyExtrDoorsStdPctCrAmt' in 'OthExteriorDoorEgyStarRqrGrp' from 'ExteriorDoorEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ], but must not be greater than 500.",
  ),
  rule(
    "F5695-075",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 5695, [ 'CostAmt' in 'MostExpnsExtrWndwSkyltGrp' from 'ExtrWndwSkyltEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then [ 'QMID' in 'MostExpnsExtrWndwSkyltGrp' from 'ExtrWndwSkyltEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] must be present unless a binary attachment or [GeneralDependencySmall] with description beginning with \"Substantiate QMID\" is present in the return.",
  ),
  rule(
    "F5695-076",
    "reject",
    "math_error",
    alwaysPass,
    "If Form 5695, [ 'MostExpnsExtrWndwSkyltCostAmt' in 'ExtrWndwSkyltEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then it must equal the sum of all instances of [ 'CostAmt' in 'MostExpnsExtrWndwSkyltGrp' from 'ExtrWndwSkyltEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-077",
    "reject",
    "math_error",
    ifThen(hasNonZero("ExteriorWndwOrSkylightCostAmt"), eqSum("ExteriorWndwOrSkylightCostAmt", "MostExpnsExtrWndwSkyltCostAmt", "OthQlfyExtrWndwSkyltCostAmt")),
    "If Form 5695, [ 'ExteriorWndwOrSkylightCostAmt' in 'ExtrWndwSkyltEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then it must be equal to the sum of [ 'MostExpnsExtrWndwSkyltCostAmt' in 'ExtrWndwSkyltEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'OthQlfyExtrWndwSkyltCostAmt' in 'ExtrWndwSkyltEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-078",
    "reject",
    "incorrect_data",
    notGtNum("ExtrWndwSkylightStdPctCrAmt", 600),
    "Form 5695, [ 'ExtrWndwSkylightStdPctCrAmt' in 'ExtrWndwSkyltEgyStarRqrGrp' from 'EgyEffcntHmImprvCrGrp' ] must not be greater than 600.",
  ),
  rule(
    "F5695-079",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 5695, [ 'MostExpnsCentralAirCondCostAmt' in 'CentralAirConditionerGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then [ 'MostExpnsCentralAirCondQMID' in 'CentralAirConditionerGrp' from 'EgyEffcntHmImprvCrGrp' ] must be present unless a binary attachment or [GeneralDependencySmall] with description beginning with \"Substantiate QMID\" is present in the return.",
  ),
  rule(
    "F5695-080",
    "reject",
    "math_error",
    ifThen(hasNonZero("CentralAirCondCostAmt"), eqSum("CentralAirCondCostAmt", "MostExpnsCentralAirCondCostAmt", "OthCentralAirCondCostAmt")),
    "If [ 'CentralAirCondCostAmt' in 'CentralAirConditionerGrp' from 'EgyEffcntHmImprvCrGrp ] has a non-zero value, then it must be equal to the sum of  ['MostExpnsCentralAirCondCostAmt' in 'CentralAirConditionerGrp' from 'EgyEffcntHmImprvCrGrp ] and [ 'OthCentralAirCondCostAmt' in 'CentralAirConditionerGrp' from 'EgyEffcntHmImprvCrGrp ].",
  ),
  rule(
    "F5695-081",
    "reject",
    "incorrect_data",
    notGtNum("CentralAirCondCostStdPctCrAmt", 600),
    "Form 5695, [ 'CentralAirCondCostStdPctCrAmt' in 'CentralAirConditionerGrp' from 'EgyEffcntHmImprvCrGrp' ] must not be greater than 600.",
  ),
  rule(
    "F5695-082",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 5695, [ 'CostAmt' in 'MostExpnsWaterHtrGrp' from 'WaterHeaterGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then [ 'QMID' in 'MostExpnsWaterHtrGrp' from 'WaterHeaterGrp' from 'EgyEffcntHmImprvCrGrp' ] must be present unless a binary attachment or [GeneralDependencySmall] with description beginning with \"Substantiate QMID\" is present in the return.",
  ),
  rule(
    "F5695-083",
    "reject",
    "math_error",
    alwaysPass,
    "If Form 5695, [ 'MostExpnsWaterHtCostAmt' in 'WaterHeaterGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then it must equal the sum of all instances of [ 'CostAmt' in 'MostExpnsWaterHtrGrp' from 'WaterHeaterGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-084",
    "reject",
    "math_error",
    ifThen(hasNonZero("NatGasPrpnOilWtrHtrCostAmt"), eqSum("NatGasPrpnOilWtrHtrCostAmt", "MostExpnsWaterHtCostAmt", "OthNatGasPrpnOilWtrHtrCostAmt")),
    "If [ 'NatGasPrpnOilWtrHtrCostAmt' in 'WaterHeaterGrp' from 'EgyEffcntHmImprvCrGrp ] has a non-zero value, then it must be equal to the sum of [ 'MostExpnsWaterHtCostAmt' in 'WaterHeaterGrp' from 'EgyEffcntHmImprvCrGrp ] and [ 'OthNatGasPrpnOilWtrHtrCostAmt' in 'WaterHeaterGrp' from 'EgyEffcntHmImprvCrGrp ].",
  ),
  rule(
    "F5695-085",
    "reject",
    "incorrect_data",
    notGtNum("NatGasPrpnOilWtrHtrStdPctCrAmt", 600),
    "Form 5695, [ 'NatGasPrpnOilWtrHtrStdPctCrAmt' in 'WaterHeaterGrp' from 'EgyEffcntHmImprvCrGrp' ] must not be greater than 600.",
  ),
  rule(
    "F5695-086",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 5695, [ 'MostExpnsFrncHotWtrBlrCostAmt' in 'FrncHotWtrBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then [ 'MostExpnsFrncHotWtrBlrQMID' in 'FrncHotWtrBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] must be present unless a binary attachment or [GeneralDependencySmall] with description beginning with \"Substantiate QMID\" is present in the return.",
  ),
  rule(
    "F5695-087",
    "reject",
    "math_error",
    ifThen(hasNonZero("NatGasPrpnOilHotWtrBlrCostAmt"), eqSum("NatGasPrpnOilHotWtrBlrCostAmt", "MostExpnsFrncHotWtrBlrCostAmt", "OthFrncHotWtrBlrCostAmt")),
    "If Form 5695, [ 'NatGasPrpnOilHotWtrBlrCostAmt' in 'FrncHotWtrBlrGrp' from 'EgyEffcntHmImprvCrGrp ] has a non-zero value, then it must be equal to the sum of  ['MostExpnsFrncHotWtrBlrCostAmt' in 'FrncHotWtrBlrGrp' from 'EgyEffcntHmImprvCrGrp ] and [ 'OthFrncHotWtrBlrCostAmt' in 'FrncHotWtrBlrGrp' from 'EgyEffcntHmImprvCrGrp ].",
  ),
  rule(
    "F5695-088",
    "reject",
    "incorrect_data",
    notGtNum("NatGasPrpnOilHotWtrBlrPctAmt", 600),
    "Form 5695, [ 'NatGasPrpnOilHotWtrBlrPctAmt' in 'FrncHotWtrBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] must not be greater than 600.",
  ),
  rule(
    "F5695-089",
    "reject",
    "incorrect_data",
    ifThen(hasValue("EnablingPropertyGrp"), eqStr("PanelboardCktFeederInd", "Yes")),
    "If Form 5695, [ 'EnablingPropertyGrp' in 'EgyEffcntHmImprvCrGrp' ] is present, then [ 'PanelboardCktFeederInd' in 'EgyEffcntHmImprvCrGrp' ] must have a choice of \"Yes\" indicated.",
  ),
  rule(
    "F5695-090",
    "reject",
    "incorrect_data",
    ifThen(eqStr("PanelboardCktFeederInd", "No"), noValue("EnablingPropertyGrp")),
    "If Form 5695, [ 'PanelboardCktFeederInd' in 'EgyEffcntHmImprvCrGrp' ] has a choice of \"No\" indicated, then [ 'EnablingPropertyGrp' in 'EgyEffcntHmImprvCrGrp' ] must not be present.",
  ),
  rule(
    "F5695-091",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 5695, [ 'PanelboardCktFeederCostAmt' in 'EnablingPropertyGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then at least one instance of [ 'QMID' in 'EnablingPropertyGrp' from 'EgyEffcntHmImprvCrGrp' ] must be present unless a binary attachment or [GeneralDependencySmall] with description beginning with \"Substantiate QMID\" is present in the return.",
  ),
  rule(
    "F5695-092",
    "reject",
    "incorrect_data",
    notGtNum("PanelboardCktFeederStdPctCrAmt", 600),
    "Form 5695, [ 'PanelboardCktFeederStdPctCrAmt' in 'EnablingPropertyGrp' from 'EgyEffcntHmImprvCrGrp' ] must not be greater than 600.",
  ),
  rule(
    "F5695-093",
    "reject",
    "incorrect_data",
    notGtNum("MainHomeEgyAuditStdPctCrAmt", 150),
    "Form 5695, [ 'MainHomeEgyAuditStdPctCrAmt' in 'EgyEffcntHmImprvCrGrp' ] must not be greater than 150.",
  ),
  rule(
    "F5695-094",
    "reject",
    "incorrect_data",
    notGtNum("EnergyEffcntImprvAllwblCostAmt", 1200),
    "Form 5695, [ 'EnergyEffcntImprvAllwblCostAmt' in 'EgyEffcntHmImprvCrGrp' ] must not be greater than 1200.",
  ),
  rule(
    "F5695-095",
    "reject",
    "incorrect_data",
    ifThen(all(noValue("JointOccupancyInd"), hasNonZero("EnergyEffcntImprvAllwblCostAmt")), eqMinNum("EnergyEffcntImprvAllwblCostAmt", "EgyEffcntImprvCreditSubtlAmt", 1200)),
    "If Form 5695, [ 'JointOccupancyInd' in 'EgyEffcntHmImprvCrGrp' ] is not checked and [ 'EnergyEffcntImprvAllwblCostAmt' in 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then [ 'EnergyEffcntImprvAllwblCostAmt' in 'EgyEffcntHmImprvCrGrp' ] must be equal to the smaller of [ 'EgyEffcntImprvCreditSubtlAmt' in 'EgyEffcntHmImprvCrGrp' ] or 1200.",
  ),
  rule(
    "F5695-096",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 5695, [ 'CostAmt' in 'MostExpnsElecGasHtPumpGrp' from 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then [ 'QMID' in 'MostExpnsElecGasHtPumpGrp' from 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] must be present unless a binary attachment or [GeneralDependencySmall] with description beginning with \"Substantiate QMID\" is present in the return.",
  ),
  rule(
    "F5695-097",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 5695, [ 'CostAmt' in 'MostExpnsHtPumpWtrHtrGrp' from 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then [ 'QMID' in 'MostExpnsHtPumpWtrHtrGrp' from 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] must be present unless a binary attachment or [GeneralDependencySmall] with description beginning with \"Substantiate QMID\" is present in the return.",
  ),
  rule(
    "F5695-098",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 5695, [ 'CostAmt' in 'MostExpnsBmssStoveBlrGrp' from 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then [ 'QMID' in 'MostExpnsBmssStoveBlrGrp' from 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] must be present unless a binary attachment or [GeneralDependencySmall] with description beginning with \"Substantiate QMID\" is present in the return.",
  ),
  rule(
    "F5695-099",
    "reject",
    "math_error",
    alwaysPass,
    "If Form 5695, [ 'HtPumpWtrHeaterBmssCostAmt' in 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then it must be equal to the sum of [ 'CostAmt' in 'MostExpnsElecGasHtPumpGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'OthElecGasHtPumpCostAmt' in 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'CostAmt' in 'MostExpnsHtPumpWtrHtrGrp' from 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] and  ['OthElecGasHtPumpWtrHtCostAmt' in 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'CostAmt' in 'MostExpnsBmssStoveBlrGrp' from 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] and [ 'OthBmssStoveBlrCostAmt' in 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-100",
    "reject",
    "incorrect_data",
    notGtNum("HtPumpWtrHeaterBmssStdPctCrAmt", 2000),
    "Form 5695, [ 'HtPumpWtrHeaterBmssStdPctCrAmt' in 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ] must not be greater than 2000.",
  ),
  rule(
    "F5695-101",
    "reject",
    "math_error",
    ifThen(all(hasNonZero("AdjustedCreditLimitAmt"), not(eqStr("AdjustedCreditLimitCd", "MORE THAN ONE MAIN HOME"))), eqSum("AdjustedCreditLimitAmt", "EnergyEffcntImprvAllwblCostAmt", "HtPumpWtrHeaterBmssStdPctCrAmt")),
    "If Form 5695, [ 'AdjustedCreditLimitAmt' in 'EgyEffcntHmImprvCrGrp' ] has a non-zero value and [ 'AdjustedCreditLimitCd' in 'EgyEffcntHmImprvCrGrp' ] does not have the value \"MORE THAN ONE MAIN HOME\", then [ 'AdjustedCreditLimitAmt' in 'EgyEffcntHmImprvCrGrp' ] must be equal to the sum of [ 'EnergyEffcntImprvAllwblCostAmt' in 'EgyEffcntHmImprvCrGrp' ] and [ 'HtPumpWtrHeaterBmssStdPctCrAmt' in 'HtPumpWtrHeaterBmssStoveBlrGrp' from 'EgyEffcntHmImprvCrGrp' ].",
  ),
  rule(
    "F5695-102",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("EgyEffcntHmImprvCrAmt"), eqMin("EgyEffcntHmImprvCrAmt", "AdjustedCreditLimitAmt", "TaxesLessCreditsAmt")),
    "If Form 5695, [ 'EgyEffcntHmImprvCrAmt' in 'EgyEffcntHmImprvCrGrp' ] has a non-zero value, then it must be equal to the smaller of [ 'AdjustedCreditLimitAmt' or 'TaxesLessCreditsAmt' in 'EgyEffcntHmImprvCrGrp' ].",
  ),
];
