/**
 * MeF Business Rules: F8962
 * Auto-generated from 1040_Business_Rules_2025v3.0.csv
 * 85 rules (85 implemented, 0 stubs)
 */

import type { RuleDef } from "../../../../core/validation/types.ts";
import { rule, all, alwaysPass, any, eqDiff, eqDiffFloorZero, eqDiv, eqField, eqFieldProduct, eqMin, eqStr, eqSum, filingStatusIs, formPresent, hasNonZero, hasValue, ifThen, isZero, noValue, not, notGtNum, } from "../../../../core/validation/mod.ts";

export const F8962_RULES: readonly RuleDef[] = [
  rule(
    "F8962-001-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("TotalExemptionsCnt"), eqField("TotalExemptionsCnt", "TotalExemptionsCnt")),
    "If Form 8962, 'TotalExemptionsCnt' has a non-zero value, then it must be equal to 'TotalExemptionsCnt' in the return.",
  ),
  rule(
    "F8962-002-03",
    "reject",
    "math_error",
    alwaysPass,
    "If Form 8962, Line 1 'TotalExemptionsCnt' has a non-zero value, then Line 2a 'ModifiedAGIAmt' must be equal to the (sum of Form 1040, 'AdjustedGrossIncomeAmt' and 'TaxExemptInterestAmt' and 'SocSecBnftAmt' and Form 2555, Line 45 'TotalIncomeExclusionAmt' and Line 50 'HousingDeductionAmt' minus Form 1040, 'TaxableSocSecAmt'.",
  ),
  rule(
    "F8962-004-01",
    "reject",
    "math_error",
    ifThen(hasNonZero("TotalExemptionsCnt"), eqSum("HouseholdIncomeAmt", "ModifiedAGIAmt", "TotalDependentsModifiedAGIAmt")),
    "If Form 8962, Line 1 'TotalExemptionsCnt' has a non-zero value, then Line 3 'HouseholdIncomeAmt' must be equal to the sum of Line 2a 'ModifiedAGIAmt' and Line 2b 'TotalDependentsModifiedAGIAmt'.",
  ),
  rule(
    "F8962-005-02",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 8962, Line 1 'TotalExemptionsCnt' has a non-zero value, then Line 4 'PovertyLevelAmt' must be equal to the amount from the selected Federal Poverty Level Table (see Form 8962 instructions) based on the family size indicated on Line 1 'TotalExemptionsCnt'.",
  ),
  rule(
    "F8962-006-01",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("TotalExemptionsCnt"), eqDiv("FederalPovertyLevelPct", "HouseholdIncomeAmt", "PovertyLevelAmt")),
    "If Form 8962, Line 1 'TotalExemptionsCnt' has a non-zero value, then Line 5 'FederalPovertyLevelPct' must be equal to Line 3 'HouseholdIncomeAmt' divided by Line 4 'PovertyLevelAmt'.",
  ),
  rule(
    "F8962-007-02",
    "reject",
    "incorrect_data",
    ifThen(hasValue("ApplicableFigureRt"), eqField("ApplicableFigureRt", "FederalPovertyLevelPct")),
    "Form 8962, Line 7 'ApplicableFigureRt' must be equal to the figure from the Applicable Figure table (see Form 8962 instructions) based on Line 5 'FederalPovertyLevelPct'.",
  ),
  rule(
    "F8962-008",
    "reject",
    "math_error",
    ifThen(hasNonZero("TotalExemptionsCnt"), eqFieldProduct("AnnualContributionAmt", "HouseholdIncomeAmt", "ApplicableFigureRt")),
    "Form 8962, Line 8a 'AnnualContributionAmt' must be equal to Line 3 'HouseholdIncomeAmt' multiplied by Line 7 'ApplicableFigureRt'.",
  ),
  rule(
    "F8962-009-01",
    "reject",
    "math_error",
    ifThen(hasValue("MonthlyContriHealthCareCvrAmt"), eqField("MonthlyContriHealthCareCvrAmt", "AnnualContributionAmt")),
    "Form 8962, Line 8b 'MonthlyContriHealthCareCvrAmt' must be equal to Line 8a 'AnnualContributionAmt' divided by 12.",
  ),
  rule(
    "F8962-010",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Form 8962, Line 35b 'MonthlyContributionAmt' for the Primary must be equal to the amount computed using the Form 8962 instructions.",
  ),
  rule(
    "F8962-011",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Form 8962, Line 36b 'MonthlyContributionAmt' for the Spouse must be equal to the amount computed using the Form 8962 instructions.",
  ),
  rule(
    "F8962-012",
    "reject",
    "math_error",
    eqDiffFloorZero("AnnualMaxPremiumAssistanceAmt", "AnnualPremiumSLCSPAmt", "AnnualContributionAmt"),
    "Form 8962, Line 11D 'AnnualMaxPremiumAssistanceAmt' must be equal to Line 11B 'AnnualPremiumSLCSPAmt' minus (-) Line 11C 'AnnualContributionAmt'.",
  ),
  rule(
    "F8962-013",
    "reject",
    "math_error",
    ifThen(eqStr("MonthCd", "JANUARY"), eqDiffFloorZero("MonthlyMaxPremiumAssistanceAmt", "MonthlyPremiumSLCSPAmt", "MonthlyContributionAmt")),
    "If Form 8962, Line 12 'MonthCd' has the value \"JANUARY\", then Line 12D 'MonthlyMaxPremiumAssistanceAmt' must be equal to Line 12B 'MonthlyPremiumSLCSPAmt' minus (-) Line 12C 'MonthlyContributionAmt'.",
  ),
  rule(
    "F8962-014",
    "reject",
    "math_error",
    ifThen(eqStr("MonthCd", "FEBRUARY"), eqDiffFloorZero("MonthlyMaxPremiumAssistanceAmt", "MonthlyPremiumSLCSPAmt", "MonthlyContributionAmt")),
    "If Form 8962, Line 13 'MonthCd' has the value \"FEBRUARY\", then Line 13D 'MonthlyMaxPremiumAssistanceAmt' must be equal to Line 13B 'MonthlyPremiumSLCSPAmt' minus (-) Line 13C 'MonthlyContributionAmt'.",
  ),
  rule(
    "F8962-015",
    "reject",
    "math_error",
    ifThen(eqStr("MonthCd", "MARCH"), eqDiffFloorZero("MonthlyMaxPremiumAssistanceAmt", "MonthlyPremiumSLCSPAmt", "MonthlyContributionAmt")),
    "If Form 8962, Line 14 'MonthCd' has the value \"MARCH\", then Line 14D 'MonthlyMaxPremiumAssistanceAmt' must be equal to Line 14B 'MonthlyPremiumSLCSPAmt' minus (-) Line 14C 'MonthlyContributionAmt'.",
  ),
  rule(
    "F8962-016",
    "reject",
    "math_error",
    ifThen(eqStr("MonthCd", "APRIL"), eqDiffFloorZero("MonthlyMaxPremiumAssistanceAmt", "MonthlyPremiumSLCSPAmt", "MonthlyContributionAmt")),
    "If Form 8962, Line 15 'MonthCd' has the value \"APRIL\", then Line 15D 'MonthlyMaxPremiumAssistanceAmt' must be equal to Line 15B 'MonthlyPremiumSLCSPAmt' minus (-) Line 15C 'MonthlyContributionAmt'.",
  ),
  rule(
    "F8962-017",
    "reject",
    "math_error",
    ifThen(eqStr("MonthCd", "MAY"), eqDiffFloorZero("MonthlyMaxPremiumAssistanceAmt", "MonthlyPremiumSLCSPAmt", "MonthlyContributionAmt")),
    "If Form 8962, Line 16 'MonthCd' has the value \"MAY\", then Line 16D 'MonthlyMaxPremiumAssistanceAmt' must be equal to Line 16B 'MonthlyPremiumSLCSPAmt' minus (-) Line 16C 'MonthlyContributionAmt'.",
  ),
  rule(
    "F8962-018",
    "reject",
    "math_error",
    ifThen(eqStr("MonthCd", "JUNE"), eqDiffFloorZero("MonthlyMaxPremiumAssistanceAmt", "MonthlyPremiumSLCSPAmt", "MonthlyContributionAmt")),
    "If Form 8962, Line 17 'MonthCd' has the value \"JUNE\", then Line 17D 'MonthlyMaxPremiumAssistanceAmt' must be equal to Line 17B 'MonthlyPremiumSLCSPAmt' minus (-) Line 17C 'MonthlyContributionAmt'.",
  ),
  rule(
    "F8962-019",
    "reject",
    "math_error",
    ifThen(eqStr("MonthCd", "JULY"), eqDiffFloorZero("MonthlyMaxPremiumAssistanceAmt", "MonthlyPremiumSLCSPAmt", "MonthlyContributionAmt")),
    "If Form 8962, Line 18 'MonthCd' has the value \"JULY\", then Line 18D 'MonthlyMaxPremiumAssistanceAmt' must be equal to Line 18B 'MonthlyPremiumSLCSPAmt' minus (-) Line 18C 'MonthlyContributionAmt'.",
  ),
  rule(
    "F8962-020",
    "reject",
    "math_error",
    ifThen(eqStr("MonthCd", "AUGUST"), eqDiffFloorZero("MonthlyMaxPremiumAssistanceAmt", "MonthlyPremiumSLCSPAmt", "MonthlyContributionAmt")),
    "If Form 8962, Line 19 'MonthCd' has the value \"AUGUST\", then Line 19D 'MonthlyMaxPremiumAssistanceAmt' must be equal to Line 19B 'MonthlyPremiumSLCSPAmt' minus (-) Line 19C 'MonthlyContributionAmt'.",
  ),
  rule(
    "F8962-021",
    "reject",
    "math_error",
    ifThen(eqStr("MonthCd", "SEPTEMBER"), eqDiffFloorZero("MonthlyMaxPremiumAssistanceAmt", "MonthlyPremiumSLCSPAmt", "MonthlyContributionAmt")),
    "If Form 8962, Line 20 'MonthCd' has the value \"SEPTEMBER\", then Line 20D 'MonthlyMaxPremiumAssistanceAmt' must be equal to Line 20B 'MonthlyPremiumSLCSPAmt' minus (-) Line 20C 'MonthlyContributionAmt'.",
  ),
  rule(
    "F8962-022",
    "reject",
    "math_error",
    ifThen(eqStr("MonthCd", "OCTOBER"), eqDiffFloorZero("MonthlyMaxPremiumAssistanceAmt", "MonthlyPremiumSLCSPAmt", "MonthlyContributionAmt")),
    "If Form 8962, Line 21 'MonthCd' has the value \"OCTOBER\", then Line 21D 'MonthlyMaxPremiumAssistanceAmt' must be equal to Line 21B 'MonthlyPremiumSLCSPAmt' minus (-) Line 21C 'MonthlyContributionAmt'.",
  ),
  rule(
    "F8962-023",
    "reject",
    "math_error",
    ifThen(eqStr("MonthCd", "NOVEMBER"), eqDiffFloorZero("MonthlyMaxPremiumAssistanceAmt", "MonthlyPremiumSLCSPAmt", "MonthlyContributionAmt")),
    "If Form 8962, Line 22 'MonthCd' has the value \"NOVEMBER\", then Line 22D 'MonthlyMaxPremiumAssistanceAmt' must be equal to Line 22B 'MonthlyPremiumSLCSPAmt' minus (-) Line 22C 'MonthlyContributionAmt'.",
  ),
  rule(
    "F8962-024",
    "reject",
    "math_error",
    ifThen(eqStr("MonthCd", "DECEMBER"), eqDiffFloorZero("MonthlyMaxPremiumAssistanceAmt", "MonthlyPremiumSLCSPAmt", "MonthlyContributionAmt")),
    "If Form 8962, Line 23 'MonthCd' has the value \"DECEMBER\", then Line 23D 'MonthlyMaxPremiumAssistanceAmt' must be equal to Line 23B 'MonthlyPremiumSLCSPAmt' minus (-) Line 23C 'MonthlyContributionAmt'.",
  ),
  rule(
    "F8962-025",
    "reject",
    "incorrect_data",
    eqMin("AnnualPremiumTaxCreditAllwAmt", "AnnualPremiumAmt", "AnnualMaxPremiumAssistanceAmt"),
    "Form 8962, Line 11E 'AnnualPremiumTaxCreditAllwAmt' must be equal to the smaller of Line 11A 'AnnualPremiumAmt' or Line 11D 'AnnualMaxPremiumAssistanceAmt'.",
  ),
  rule(
    "F8962-026-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("MonthCd", "JANUARY"), eqMin("MonthlyPremiumTaxCreditAllwAmt", "MonthlyPremiumAmt", "MonthlyMaxPremiumAssistanceAmt")),
    "If Form 8962, Line 12 'MonthCd' has the value \"JANUARY\", then Line 12E 'MonthlyPremiumTaxCreditAllwAmt' must be equal to the smaller of Line 12A 'MonthlyPremiumAmt' or Line 12D 'MonthlyMaxPremiumAssistanceAmt'.",
  ),
  rule(
    "F8962-027-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("MonthCd", "FEBRUARY"), eqMin("MonthlyPremiumTaxCreditAllwAmt", "MonthlyPremiumAmt", "MonthlyMaxPremiumAssistanceAmt")),
    "If Form 8962, Line 13 'MonthCd' has the value \"FEBRUARY\", then Line 13E 'MonthlyPremiumTaxCreditAllwAmt' must be equal to the smaller of Line 13A 'MonthlyPremiumAmt' or Line 13D 'MonthlyMaxPremiumAssistanceAmt'.",
  ),
  rule(
    "F8962-028-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("MonthCd", "MARCH"), eqMin("MonthlyPremiumTaxCreditAllwAmt", "MonthlyPremiumAmt", "MonthlyMaxPremiumAssistanceAmt")),
    "If Form 8962, Line 14 'MonthCd' has the value \"MARCH\", then Line 14E 'MonthlyPremiumTaxCreditAllwAmt' must be equal to the smaller of Line 14A 'MonthlyPremiumAmt' or Line 14D 'MonthlyMaxPremiumAssistanceAmt'.",
  ),
  rule(
    "F8962-029-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("MonthCd", "APRIL"), eqMin("MonthlyPremiumTaxCreditAllwAmt", "MonthlyPremiumAmt", "MonthlyMaxPremiumAssistanceAmt")),
    "If Form 8962, Line 15 'MonthCd' has the value \"APRIL\", then Line 15E 'MonthlyPremiumTaxCreditAllwAmt' must be equal to the smaller of Line 15A 'MonthlyPremiumAmt' or Line 15D 'MonthlyMaxPremiumAssistanceAmt'.",
  ),
  rule(
    "F8962-030-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("MonthCd", "MAY"), eqMin("MonthlyPremiumTaxCreditAllwAmt", "MonthlyPremiumAmt", "MonthlyMaxPremiumAssistanceAmt")),
    "If Form 8962, Line 16 'MonthCd' has the value \"MAY\", then Line 16E 'MonthlyPremiumTaxCreditAllwAmt' must be equal to the smaller of Line 16A 'MonthlyPremiumAmt' or Line 16D 'MonthlyMaxPremiumAssistanceAmt'.",
  ),
  rule(
    "F8962-031-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("MonthCd", "JUNE"), eqMin("MonthlyPremiumTaxCreditAllwAmt", "MonthlyPremiumAmt", "MonthlyMaxPremiumAssistanceAmt")),
    "If Form 8962, Line 17 'MonthCd' has the value \"JUNE\", then Line 17E 'MonthlyPremiumTaxCreditAllwAmt' must be equal to the smaller of Line 17A 'MonthlyPremiumAmt' or Line 17D 'MonthlyMaxPremiumAssistanceAmt'.",
  ),
  rule(
    "F8962-032-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("MonthCd", "JULY"), eqMin("MonthlyPremiumTaxCreditAllwAmt", "MonthlyPremiumAmt", "MonthlyMaxPremiumAssistanceAmt")),
    "If Form 8962, Line 18 'MonthCd' has the value \"JULY\", then Line 18E 'MonthlyPremiumTaxCreditAllwAmt' must be equal to the smaller of Line 18A 'MonthlyPremiumAmt' or Line 18D 'MonthlyMaxPremiumAssistanceAmt'.",
  ),
  rule(
    "F8962-033-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("MonthCd", "AUGUST"), eqMin("MonthlyPremiumTaxCreditAllwAmt", "MonthlyPremiumAmt", "MonthlyMaxPremiumAssistanceAmt")),
    "If Form 8962, Line 19 'MonthCd' has the value \"AUGUST\", then Line 19E 'MonthlyPremiumTaxCreditAllwAmt' must be equal to the smaller of Line 19A 'MonthlyPremiumAmt' or Line 19D 'MonthlyMaxPremiumAssistanceAmt'.",
  ),
  rule(
    "F8962-034-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("MonthCd", "SEPTEMBER"), eqMin("MonthlyPremiumTaxCreditAllwAmt", "MonthlyPremiumAmt", "MonthlyMaxPremiumAssistanceAmt")),
    "If Form 8962, Line 20 'MonthCd' has the value \"SEPTEMBER\", then Line 20E 'MonthlyPremiumTaxCreditAllwAmt' must be equal to the smaller of Line 20A 'MonthlyPremiumAmt' or Line 20D 'MonthlyMaxPremiumAssistanceAmt'.",
  ),
  rule(
    "F8962-035-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("MonthCd", "OCTOBER"), eqMin("MonthlyPremiumTaxCreditAllwAmt", "MonthlyPremiumAmt", "MonthlyMaxPremiumAssistanceAmt")),
    "If Form 8962, Line 21 'MonthCd' has the value \"OCTOBER\", then Line 21E 'MonthlyPremiumTaxCreditAllwAmt' must be equal to the smaller of Line 21A 'MonthlyPremiumAmt' or Line 21D 'MonthlyMaxPremiumAssistanceAmt'.",
  ),
  rule(
    "F8962-036-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("MonthCd", "NOVEMBER"), eqMin("MonthlyPremiumTaxCreditAllwAmt", "MonthlyPremiumAmt", "MonthlyMaxPremiumAssistanceAmt")),
    "If Form 8962, Line 22 'MonthCd' has the value \"NOVEMBER\", then Line 22E 'MonthlyPremiumTaxCreditAllwAmt' must be equal to the smaller of Line 22A 'MonthlyPremiumAmt' or Line 22D 'MonthlyMaxPremiumAssistanceAmt'.",
  ),
  rule(
    "F8962-037-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("MonthCd", "DECEMBER"), eqMin("MonthlyPremiumTaxCreditAllwAmt", "MonthlyPremiumAmt", "MonthlyMaxPremiumAssistanceAmt")),
    "If Form 8962, Line 23 'MonthCd' has the value \"DECEMBER\", then Line 23E 'MonthlyPremiumTaxCreditAllwAmt' must be equal to the smaller of Line 23A 'MonthlyPremiumAmt' or Line 23D 'MonthlyMaxPremiumAssistanceAmt'.",
  ),
  rule(
    "F8962-038",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Form 8962, Line 24 'TotalPremiumTaxCreditAmt' must be equal to Line 11E 'AnnualPremiumTaxCreditAllwAmt' or (the sum of Lines 12E through 23E 'MonthlyPremiumTaxCreditAllwAmt').",
  ),
  rule(
    "F8962-039-02",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(3), not(hasValue("MarriedFilingSeparatelyExcInd"))), isZero("TotalPremiumTaxCreditAmt")),
    "Form 8962, Line 24 'TotalPremiumTaxCreditAmt' must be equal to zero if an amount is entered when Form 1040 checkbox \"Married filing separately\" is checked (element 'IndividualReturnFilingStatusCd' has the value 3) and Form 8962, checkbox 'MarriedFilingSeparatelyExcInd' is not checked.",
  ),
  rule(
    "F8962-040",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Form 8962, Line 25 'TotalAdvancedPTCAmt' must be equal to Line 11F 'AnnualAdvancedPTCAmt' or (the sum of Lines 12F through 23F 'MonthlyAdvancedPTCAmt').",
  ),
  rule(
    "F8962-042",
    "reject",
    "math_error",
    eqDiffFloorZero("ExcessAdvncPaymentAmt", "TotalAdvancedPTCAmt", "TotalPremiumTaxCreditAmt"),
    "Form 8962, Line 27 'ExcessAdvncPaymentAmt' must be equal to Line 25 'TotalAdvancedPTCAmt' minus (-) Line 24 'TotalPremiumTaxCreditAmt'.",
  ),
  rule(
    "F8962-043-02",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 8962, 'TotalExemptionsCnt' has a non-zero value, then 'AdditionalTaxLimitationAmt' must be equal to the tax limitation amount from the Repayment Limitation table (see Form 8962 instructions) based on 'FederalPovertyLevelPct' and the filing status on the return.",
  ),
  rule(
    "F8962-046",
    "reject",
    "incorrect_data",
    ifThen(any(hasNonZero("FamilySizeCnt")), hasNonZero("TotalAdvancedPTCAmt")),
    "If Form 8962, Line 35a or Line 36a 'FamilySizeCnt' has a non-zero value, then Line 25 'TotalAdvancedPTCAmt' must have a non-zero value.",
  ),
  rule(
    "F8962-047-01",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("FamilySizeCnt"), filingStatusIs(2)),
    "If Form 8962, Line 35a or Line 36a 'FamilySizeCnt' has a non-zero value, then Form 1040 checkbox \"Married filing jointly\" must be checked (element 'IndividualReturnFilingStatusCd' must have the value 2).",
  ),
  rule(
    "F8962-048",
    "reject",
    "missing_data",
    ifThen(hasValue("PolicyNum"), any(hasValue("MonthlyPremiumPct"), hasValue("MonthlyPremiumSLCSPPct"), hasValue("MonthlyAdvancedPTCPct"))),
    "If Form 8962, Part 4 \"Shared Policy Allocation\", 'PolicyNum' has a value, then at least one of the following must have a value: 'MonthlyPremiumPct' or 'MonthlyPremiumSLCSPPct' or 'MonthlyAdvancedPTCPct'.",
  ),
  rule(
    "F8962-049",
    "reject",
    "missing_data",
    ifThen(hasNonZero("TotalDependentsModifiedAGIAmt"), hasValue("DependentSSN")),
    "If Form 8962, 'TotalDependentsModifiedAGIAmt' has a non-zero value, then 'DependentSSN' in the return must have a value.",
  ),
  rule(
    "F8962-050-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 8962, Line 35a or Line 36a 'FamilySizeCnt' has a non-zero value, then it must be less than Form 1040, 'TotalExemptionsCnt'.",
  ),
  rule(
    "F8962-051-01",
    "reject",
    "math_error",
    alwaysPass,
    "If Form 8962, Line 35a 'FamilySizeCnt' and Line 36a 'FamilySizeCnt' both have non-zero values, then their sum must be equal to Form 1040, 'TotalExemptionsCnt'.",
  ),
  rule(
    "F8962-056",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("TotalPremiumTaxCreditAmt"), hasNonZero("TotalExemptionsCnt")),
    "If Form 8962, 'TotalPremiumTaxCreditAmt' has a non-zero value, then 'TotalExemptionsCnt' in the return must have a non-zero value.",
  ),
  rule(
    "F8962-057",
    "reject",
    "incorrect_data",
    ifThen(any(hasNonZero("AnnualPremiumAmt"), hasNonZero("AnnualPremiumSLCSPAmt"), hasNonZero("AnnualContributionAmt"), hasNonZero("AnnualMaxPremiumAssistanceAmt"), hasNonZero("AnnualPremiumTaxCreditAllwAmt"), hasNonZero("AnnualAdvancedPTCAmt")), all(noValue("SharedPolicyAllocationGrp"), noValue("AltCalcForMarriagePrimaryGrp"), noValue("AltCalcForMarriageSpouseGrp"))),
    "If Form 8962, Line 11A 'AnnualPremiumAmt' or Line 11B 'AnnualPremiumSLCSPAmt' or Line 11C 'AnnualContributionAmt' or Line 11D 'AnnualMaxPremiumAssistanceAmt' or Line 11E 'AnnualPremiumTaxCreditAllwAmt' or Line 11F 'AnnualAdvancedPTCAmt ' has a non-zero value, then the following must not have values: 'SharedPolicyAllocationGrp' and Line 35 'AltCalcForMarriagePrimaryGrp' and Line 36 'AltCalcForMarriageSpouseGrp'.",
  ),
  rule(
    "F8962-058",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("TotalPremiumTaxCreditAmt"), hasNonZero("TotalExemptionsCnt")),
    "If Form 8962, Line 24 'TotalPremiumTaxCreditAmt' has a non-zero value, then Line 1 'TotalExemptionsCnt' must have a non-zero value.",
  ),
  rule(
    "F8962-060",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 8962, 'StartMonthNumberCd' has a value in 'AltCalcForMarriagePrimaryGrp' or 'AltCalcForMarriageSpouseGrp', then 'MonthCd' in 'MonthlyPTCCalculationGrp' must not be prior to earliest 'StartMonthNumberCd'.",
  ),
  rule(
    "F8962-061",
    "reject",
    "incorrect_data",
    ifThen(isZero("TotalExemptionsCnt"), noValue("AdditionalTaxLimitationAmt")),
    "If Form 8962, Line 1 'TotalExemptionsCnt' is equal to zero, then Line 28 'AdditionalTaxLimitationAmt' must not have a value.",
  ),
  rule(
    "F8962-063",
    "reject",
    "missing_data",
    any(hasNonZero("AnnualPremiumAmt"), hasNonZero("AnnualPremiumSLCSPAmt"), hasNonZero("AnnualAdvancedPTCAmt"), hasNonZero("MonthlyPremiumAmt"), hasNonZero("MonthlyPremiumSLCSPAmt"), hasNonZero("MonthlyAdvancedPTCAmt")),
    "At least one of the following must have a non-zero value on Form 8962: 'AnnualPremiumAmt' or 'AnnualPremiumSLCSPAmt' or 'AnnualAdvancedPTCAmt' or 'MonthlyPremiumAmt' or 'MonthlyPremiumSLCSPAmt' or 'MonthlyAdvancedPTCAmt'.",
  ),
  rule(
    "F8962-064",
    "reject",
    "incorrect_data",
    notGtNum("AnnualPremiumAmt", 99999),
    "Form 8962, 'AnnualPremiumAmt' must not be greater than 99999.",
  ),
  rule(
    "F8962-065",
    "reject",
    "incorrect_data",
    notGtNum("AnnualPremiumSLCSPAmt", 99999),
    "Form 8962, 'AnnualPremiumSLCSPAmt' must not be greater than 99999.",
  ),
  rule(
    "F8962-066",
    "reject",
    "incorrect_data",
    notGtNum("AnnualAdvancedPTCAmt", 99999),
    "Form 8962, 'AnnualAdvancedPTCAmt' must not be greater than 99999.",
  ),
  rule(
    "F8962-067",
    "reject",
    "incorrect_data",
    notGtNum("MonthlyPremiumAmt", 99999),
    "The sum of all 'MonthlyPremiumAmt' on Form 8962 must not be greater than 99999.",
  ),
  rule(
    "F8962-068",
    "reject",
    "incorrect_data",
    notGtNum("MonthlyPremiumSLCSPAmt", 99999),
    "The sum of all 'MonthlyPremiumSLCSPAmt' on Form 8962 must not be greater than 99999.",
  ),
  rule(
    "F8962-069",
    "reject",
    "incorrect_data",
    notGtNum("MonthlyAdvancedPTCAmt", 99999),
    "The sum of all 'MonthlyAdvancedPTCAmt' on Form 8962 must not be greater than 99999.",
  ),
  rule(
    "F8962-070",
    "reject",
    "missing_document",
    alwaysPass,
    "The e-File database indicates Form 8962 must be submitted with the return. The taxpayer, the taxpayer's spouse if filing jointly, or a dependent claimed on the tax return was enrolled in health insurance coverage through a Health Insurance Marketplace and advance payments of the premium tax credit were made for the coverage. Please resubmit the return with the Form 8962 included using the information from your Form 1095-A. If you did not receive or have lost your 1095-A, you can get a copy from the Marketplace through which you obtained coverage. Alternatively, you can access your Form 1095-A through your individual taxpayer online account on https://www.irs.gov/your-account. If you think Form 8962 is not required, please resubmit the return with a binary attachment (PDF) containing the Description \"ACA Explanation\" and explaining why the Form 8962 is not required. Please visit: https://www.irs.gov/newsroom/how-to-correct-an-electronically-filed-return-rejected-for-a-missing-form-8962 for more information.",
  ),
  rule(
    "F8962-300",
    "reject",
    "missing_data",
    ifThen(hasNonZero("AnnualPremiumTaxCreditAllwAmt"), all(hasNonZero("AnnualPremiumAmt"), hasNonZero("AnnualPremiumSLCSPAmt"), hasNonZero("AnnualMaxPremiumAssistanceAmt"))),
    "If Form 8962, Line 11E 'AnnualPremiumTaxCreditAllwAmt' has a non-zero value, then Line 11A 'AnnualPremiumAmt' and Line 11B 'AnnualPremiumSLCSPAmt' and Line 11D 'AnnualMaxPremiumAssistanceAmt' must have non-zero values.",
  ),
  rule(
    "F8962-301",
    "reject",
    "missing_data",
    ifThen(all(eqStr("MonthCd", "JANUARY"), hasNonZero("MonthlyPremiumTaxCreditAllwAmt")), all(hasNonZero("MonthlyPremiumAmt"), hasNonZero("MonthlyPremiumSLCSPAmt"), hasNonZero("MonthlyMaxPremiumAssistanceAmt"))),
    "If Form 8962, Line 12 'MonthCd' has the value \"JANUARY\" and Line 12E 'MonthlyPremiumTaxCreditAllwAmt' has a non-zero value, then Line 12A 'MonthlyPremiumAmt' and Line 12B 'MonthlyPremiumSLCSPAmt' and Line 12D 'MonthlyMaxPremiumAssistanceAmt' must have non-zero values.",
  ),
  rule(
    "F8962-302",
    "reject",
    "missing_data",
    ifThen(all(eqStr("MonthCd", "FEBRUARY"), hasNonZero("MonthlyPremiumTaxCreditAllwAmt")), all(hasNonZero("MonthlyPremiumAmt"), hasNonZero("MonthlyPremiumSLCSPAmt"), hasNonZero("MonthlyMaxPremiumAssistanceAmt"))),
    "If Form 8962, Line 13 'MonthCd' has the value \"FEBRUARY\" and Line 13E 'MonthlyPremiumTaxCreditAllwAmt' has a non-zero value, then Line 13A 'MonthlyPremiumAmt' and Line 13B 'MonthlyPremiumSLCSPAmt' and Line 13D 'MonthlyMaxPremiumAssistanceAmt' must have non-zero values.",
  ),
  rule(
    "F8962-303",
    "reject",
    "missing_data",
    ifThen(all(eqStr("MonthCd", "MARCH"), hasNonZero("MonthlyPremiumTaxCreditAllwAmt")), all(hasNonZero("MonthlyPremiumAmt"), hasNonZero("MonthlyPremiumSLCSPAmt"), hasNonZero("MonthlyMaxPremiumAssistanceAmt"))),
    "If Form 8962, Line 14 'MonthCd' has the value \"MARCH\" and Line 14E 'MonthlyPremiumTaxCreditAllwAmt' has a non-zero value, then Line 14A 'MonthlyPremiumAmt' and Line 14B 'MonthlyPremiumSLCSPAmt' and Line 14D 'MonthlyMaxPremiumAssistanceAmt' must have non-zero values.",
  ),
  rule(
    "F8962-304",
    "reject",
    "missing_data",
    ifThen(all(eqStr("MonthCd", "APRIL"), hasNonZero("MonthlyPremiumTaxCreditAllwAmt")), all(hasNonZero("MonthlyPremiumAmt"), hasNonZero("MonthlyPremiumSLCSPAmt"), hasNonZero("MonthlyMaxPremiumAssistanceAmt"))),
    "If Form 8962, Line 15 'MonthCd' has the value \"APRIL\" and Line 15E 'MonthlyPremiumTaxCreditAllwAmt' has a non-zero value, then Line 15A 'MonthlyPremiumAmt' and Line 15B 'MonthlyPremiumSLCSPAmt' and Line 15D 'MonthlyMaxPremiumAssistanceAmt' must have non-zero values.",
  ),
  rule(
    "F8962-305",
    "reject",
    "missing_data",
    ifThen(all(eqStr("MonthCd", "MAY"), hasNonZero("MonthlyPremiumTaxCreditAllwAmt")), all(hasNonZero("MonthlyPremiumAmt"), hasNonZero("MonthlyPremiumSLCSPAmt"), hasNonZero("MonthlyMaxPremiumAssistanceAmt"))),
    "If Form 8962, Line 16 'MonthCd' has the value \"MAY\" and Line 16E 'MonthlyPremiumTaxCreditAllwAmt' has a non-zero value, then Line 16A 'MonthlyPremiumAmt' and Line 16B 'MonthlyPremiumSLCSPAmt' and Line 16D 'MonthlyMaxPremiumAssistanceAmt' must have non-zero values.",
  ),
  rule(
    "F8962-306",
    "reject",
    "missing_data",
    ifThen(all(eqStr("MonthCd", "JUNE"), hasNonZero("MonthlyPremiumTaxCreditAllwAmt")), all(hasNonZero("MonthlyPremiumAmt"), hasNonZero("MonthlyPremiumSLCSPAmt"), hasNonZero("MonthlyMaxPremiumAssistanceAmt"))),
    "If Form 8962, Line 17 'MonthCd' has the value \"JUNE\" and Line 17E 'MonthlyPremiumTaxCreditAllwAmt' has a non-zero value, then Line 17A 'MonthlyPremiumAmt' and Line 17B 'MonthlyPremiumSLCSPAmt' and Line 17D 'MonthlyMaxPremiumAssistanceAmt' must have non-zero values.",
  ),
  rule(
    "F8962-307",
    "reject",
    "missing_data",
    ifThen(all(eqStr("MonthCd", "JULY"), hasNonZero("MonthlyPremiumTaxCreditAllwAmt")), all(hasNonZero("MonthlyPremiumAmt"), hasNonZero("MonthlyPremiumSLCSPAmt"), hasNonZero("MonthlyMaxPremiumAssistanceAmt"))),
    "If Form 8962, Line 18 'MonthCd' has the value \"JULY\" and Line 18E 'MonthlyPremiumTaxCreditAllwAmt' has a non-zero value, then Line 18A 'MonthlyPremiumAmt' and Line 18B 'MonthlyPremiumSLCSPAmt' and Line 18D 'MonthlyMaxPremiumAssistanceAmt' must have non-zero values.",
  ),
  rule(
    "F8962-308",
    "reject",
    "missing_data",
    ifThen(all(eqStr("MonthCd", "AUGUST"), hasNonZero("MonthlyPremiumTaxCreditAllwAmt")), all(hasNonZero("MonthlyPremiumAmt"), hasNonZero("MonthlyPremiumSLCSPAmt"), hasNonZero("MonthlyMaxPremiumAssistanceAmt"))),
    "If Form 8962, Line 19 'MonthCd' has the value \"AUGUST\" and Line 19E 'MonthlyPremiumTaxCreditAllwAmt' has a non-zero value, then Line 19A 'MonthlyPremiumAmt' and Line 19B 'MonthlyPremiumSLCSPAmt' and Line 19D 'MonthlyMaxPremiumAssistanceAmt' must have non-zero values.",
  ),
  rule(
    "F8962-309",
    "reject",
    "missing_data",
    ifThen(all(eqStr("MonthCd", "SEPTEMBER"), hasNonZero("MonthlyPremiumTaxCreditAllwAmt")), all(hasNonZero("MonthlyPremiumAmt"), hasNonZero("MonthlyPremiumSLCSPAmt"), hasNonZero("MonthlyMaxPremiumAssistanceAmt"))),
    "If Form 8962, Line 20 'MonthCd' has the value \"SEPTEMBER\" and Line 20E 'MonthlyPremiumTaxCreditAllwAmt' has a non-zero value, then Line 20A 'MonthlyPremiumAmt' and Line 20B 'MonthlyPremiumSLCSPAmt' and Line 20D 'MonthlyMaxPremiumAssistanceAmt' must have non-zero values.",
  ),
  rule(
    "F8962-310",
    "reject",
    "missing_data",
    ifThen(all(eqStr("MonthCd", "OCTOBER"), hasNonZero("MonthlyPremiumTaxCreditAllwAmt")), all(hasNonZero("MonthlyPremiumAmt"), hasNonZero("MonthlyPremiumSLCSPAmt"), hasNonZero("MonthlyMaxPremiumAssistanceAmt"))),
    "If Form 8962, Line 21 'MonthCd' has the value \"OCTOBER\" and Line 21E 'MonthlyPremiumTaxCreditAllwAmt' has a non-zero value, then Line 21A 'MonthlyPremiumAmt' and Line 21B 'MonthlyPremiumSLCSPAmt' and Line 21D 'MonthlyMaxPremiumAssistanceAmt' must have non-zero values.",
  ),
  rule(
    "F8962-311",
    "reject",
    "missing_data",
    ifThen(all(eqStr("MonthCd", "NOVEMBER"), hasNonZero("MonthlyPremiumTaxCreditAllwAmt")), all(hasNonZero("MonthlyPremiumAmt"), hasNonZero("MonthlyPremiumSLCSPAmt"), hasNonZero("MonthlyMaxPremiumAssistanceAmt"))),
    "If Form 8962, Line 22 'MonthCd' has the value \"NOVEMBER\" and Line 22E 'MonthlyPremiumTaxCreditAllwAmt' has a non-zero value, then Line 22A 'MonthlyPremiumAmt' and Line 22B 'MonthlyPremiumSLCSPAmt' and Line 22D 'MonthlyMaxPremiumAssistanceAmt' must have non-zero values.",
  ),
  rule(
    "F8962-312",
    "reject",
    "missing_data",
    ifThen(all(eqStr("MonthCd", "DECEMBER"), hasNonZero("MonthlyPremiumTaxCreditAllwAmt")), all(hasNonZero("MonthlyPremiumAmt"), hasNonZero("MonthlyPremiumSLCSPAmt"), hasNonZero("MonthlyMaxPremiumAssistanceAmt"))),
    "If Form 8962, Line 23 'MonthCd' has the value \"DECEMBER\" and Line 23E 'MonthlyPremiumTaxCreditAllwAmt' has a non-zero value, then Line 23A 'MonthlyPremiumAmt' and Line 23B 'MonthlyPremiumSLCSPAmt' and Line 23D 'MonthlyMaxPremiumAssistanceAmt' must have non-zero values.",
  ),
  rule(
    "F8962-313",
    "reject",
    "missing_data",
    ifThen(eqStr("SharePolicyMarriedAltCalcInd", "Yes"), any(hasValue("PolicyNum"), hasNonZero("FamilySizeCnt"))),
    "If Form 8962, Line 9 'SharePolicyMarriedAltCalcInd' has a choice of \"Yes\" indicated, then Line 30a 'PolicyNum' must have a value or (Line 35a or Line 36a 'FamilySizeCnt') must have a value greater than zero.",
  ),
  rule(
    "F8962-314-01",
    "reject",
    "missing_data",
    ifThen(eqStr("SharePolicyMarriedAltCalcInd", "No"), hasValue("FullYrCoverage1095AInd")),
    "If Form 8962, Line 9 'SharePolicyMarriedAltCalcInd' has a choice of \"No\" indicated, then Line 10 'FullYrCoverage1095AInd' must have a choice of \"Yes\" or \"No\" indicated.",
  ),
  rule(
    "F8962-316-01",
    "reject",
    "missing_data",
    ifThen(eqStr("FullYrCoverage1095AInd", "No"), hasValue("MonthlyPTCCalculationGrp")),
    "If Form 8962, Line 10 'FullYrCoverage1095AInd' has a choice of \"No\" indicated, then 'MonthlyPTCCalculationGrp' must have a value.",
  ),
  rule(
    "F8962-317",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Form 8962, Line 35c 'StartMonthNumberCd' must not be after Line 35d 'EndMonthNumberCd'.",
  ),
  rule(
    "F8962-318",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Form 8962, Line 36c 'StartMonthNumberCd' must not be after Line 36d 'EndMonthNumberCd'.",
  ),
  rule(
    "F8962-319",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Form 8962, Part 4 \"Shared Policy Allocation\", 'StartMonthNumberCd' must not be after 'EndMonthNumberCd'.",
  ),
  rule(
    "F8962-320",
    "reject",
    "incorrect_data",
    alwaysPass,
    "'MonthCd' on Form 8962, Lines 12 through Line 23 must be unique.",
  ),
  rule(
    "F8962-321",
    "reject",
    "incorrect_data",
    ifThen(hasValue("AnnualContributionAmt"), eqField("AnnualContributionAmt", "AnnualContributionAmt")),
    "If Form 8962, Line 11C 'AnnualContributionAmt' has a non-zero value, then it must be equal to Line 8a 'AnnualContributionAmt'.",
  ),
  rule(
    "F8962-322",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Each 'MonthlyContributionAmt' on Form 8962, Lines 12C through 23C that has a non-zero value must be equal to the amount computed using the Form 8962 instructions.",
  ),
  rule(
    "F8962-330",
    "reject",
    "incorrect_data",
    noValue("FederalPovertyLevelPct401Ind"),
    "Form 8962, 'FederalPovertyLevelPct401Ind' must not have a value.",
  ),
  rule(
    "F8962-341",
    "reject",
    "math_error",
    eqDiff("ReconciledPremiumTaxCreditAmt", "TotalPremiumTaxCreditAmt", "TotalAdvancedPTCAmt"),
    "Form 8962, Line 26 'ReconciledPremiumTaxCreditAmt' must be equal to Line 24 'TotalPremiumTaxCreditAmt' minus (-) Line 25 'TotalAdvancedPTCAmt'.",
  ),
  rule(
    "F8962-344",
    "reject",
    "incorrect_data",
    eqMin("PremiumTaxCreditTaxLiabAmt", "ExcessAdvncPaymentAmt", "AdditionalTaxLimitationAmt"),
    "Form 8962, Line 29 'PremiumTaxCreditTaxLiabAmt' must be equal to the smaller of Line 27 'ExcessAdvncPaymentAmt' or Line 28 'AdditionalTaxLimitationAmt'.",
  ),
];
