/**
 * MeF Business Rules: IND
 * Auto-generated from 1040_Business_Rules_2025v3.0.csv
 * 201 rules (120 implemented, 81 stubs)
 *
 * Stubs kept as alwaysPass — all require runtime/external context:
 *   - e-File database lookups (prior-year AGI/PIN match, SSN lock status, duplicate
 *     SSN cross-instance checks, IP PIN verification, death-date cross-reference)
 *   - Per-item iteration over DependentDetail array (uniqueness, relationship codes,
 *     ITIN/ATIN checks, age checks, death-certificate attachments)
 *   - Dependent count operations (CTC × $2,000 / ODC × $500 cap, ACTC × $1,700 cap)
 *   - Server-side processing context (TaxPeriodEndDt vs. receipt date, prior-year
 *     acceptance status, post-original return count limits, processing-year signature)
 *   - Format validation without an available regex predicate (IP address, numeric PIN)
 *   - Pure informational / policy alerts (IND-067-10, IND-145-01, IND-162, IND-450,
 *     IND-607, IND-617, IND-644, IND-663)
 */

import type { RuleDef } from "../../../../core/validation/types.ts";
import {
  all,
  allDistinct,
  alwaysFail,
  alwaysPass,
  any,
  contains,
  dateYearGte,
  eqDiff,
  eqField,
  eqNum,
  eqStr,
  eqSum,
  filingStatusIs,
  filingStatusNot,
  formAbsent,
  formPresent,
  gt,
  hasNonZero,
  hasValue,
  ifThen,
  ifThenUnless,
  isZero,
  not,
  notGtField,
  noValue,
  ssnNotEqual,
  validSSN,
} from "../../../../core/validation/mod.ts";
import { rule } from "../../../../core/validation/mod.ts";

export const IND_RULES: readonly RuleDef[] = [
  rule(
    "IND-001-01",
    "reject",
    "incorrect_data",
    validSSN("PreparerSSN"),
    "'PreparerSSN' in the Return Header must not be all zeros or all nines.",
  ),
  rule(
    "IND-002",
    "reject",
    "incorrect_data",
    alwaysPass,
    "'TaxPeriodEndDt' in the Submission Manifest must be before the date the return was received.",
  ),
  rule(
    "IND-005-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("PaymentAmt"), eqField("PaymentAmt", "PaymentAmt")),
    "If Form 9465 and IRS Payment Record are present in the return, then Form 9465, 'PaymentAmt' must be equal to 'PaymentAmt' in IRS Payment Record.",
  ),
  rule(
    "IND-006",
    "reject",
    "incorrect_data",
    ssnNotEqual("PrimarySSN", "SpouseSSN"),
    "Spouse SSN in the return must not be the same as the Primary SSN.",
  ),
  rule(
    "IND-013-01",
    "reject",
    "missing_data",
    ifThen(
      any(
        hasValue("SelfEmployedInd"),
        hasValue("PreparerPersonNm"),
        hasValue("PreparerFirmName"),
        hasValue("PreparerUSAddress"),
        hasValue("PreparerForeignAddress"),
      ),
      any(
        hasValue("PreparerSSN"),
        hasValue("PTIN"),
        hasValue("STIN"),
        hasValue("PreparerFirmEIN"),
      ),
    ),
    "In the Return Header, 'PreparerSSN' or 'PTIN' or 'STIN' or 'PreparerFirmEIN' must have a value, if any one of the following is true: (1) checkbox 'SelfEmployedInd' is checked; (2) 'PreparerPersonNm' or 'PreparerFirmName' or 'PreparerUSAddress' or 'PreparerForeignAddress' has a value.",
  ),
  rule(
    "IND-015",
    "reject",
    "incorrect_data",
    ifThen(hasValue("WorkPerformedResidingInUSInd"), hasValue("USAddress")),
    "If checkbox 'WorkPerformedResidingInUSInd' is checked in [FECRecord], then 'USAddress' must have a value.",
  ),
  rule(
    "IND-016",
    "reject",
    "missing_data",
    ifThen(hasValue("USAddress"), hasValue("WorkPerformedResidingInUSInd")),
    "If 'USAddress' has a value in [FECRecord], then checkbox 'WorkPerformedResidingInUSInd' must be checked.",
  ),
  rule(
    "IND-018-02",
    "reject",
    "missing_data",
    ifThen(hasValue("PrimaryDeathDt"), hasValue("InCareOfNm")),
    "If 'PrimaryDeathDt' has a value in the return, then 'InCareOfNm' in the Filer address in the Return Header must have a value.",
  ),
  rule(
    "IND-019-02",
    "reject",
    "missing_data",
    ifThen(hasValue("SpouseDeathDt"), hasValue("InCareOfNm")),
    "If 'SpouseDeathDt' has a value in the return, then 'InCareOfNm' in the Filer address in the Return Header must have a value.",
  ),
  rule(
    "IND-020-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("PaidPreparerInformationGrp"), noValue("NonPaidPreparerCd")),
    "If 'PaidPreparerInformationGrp' is present in the Return Header, then 'NonPaidPreparerCd' must not have a value in the return.",
  ),
  rule(
    "IND-021-01",
    "reject",
    "missing_data",
    ifThen(
      all(eqStr("PINTypeCd", "Self-Select On-Line"), hasValue("PrimarySignaturePIN")),
      hasValue("PrimaryBirthDt"),
    ),
    "If 'PINTypeCd' in the Return Header has the value \"Self-Select On-Line\" and 'PrimarySignaturePIN' has a value, then 'PrimaryBirthDt' must have a value.",
  ),
  rule(
    "IND-022-01",
    "reject",
    "missing_data",
    ifThen(
      all(eqStr("PINTypeCd", "Self-Select On-Line"), hasValue("SpouseSignaturePIN")),
      hasValue("SpouseBirthDt"),
    ),
    "If 'PINTypeCd' in the Return Header has the value \"Self-Select On-Line\" and 'SpouseSignaturePIN' has a value, then 'SpouseBirthDt' must have a value.",
  ),
  rule(
    "IND-023-01",
    "reject",
    "missing_data",
    ifThen(
      all(eqStr("PINTypeCd", "Self-Select Practitioner"), hasValue("PrimarySignaturePIN")),
      hasValue("PrimaryBirthDt"),
    ),
    "If 'PINTypeCd' in the Return Header has the value \"Self-Select Practitioner\" and 'PrimarySignaturePIN' has a value, then 'PrimaryBirthDt' must have a value.",
  ),
  rule(
    "IND-024-01",
    "reject",
    "missing_data",
    ifThen(
      all(eqStr("PINTypeCd", "Self-Select Practitioner"), hasValue("SpouseSignaturePIN")),
      hasValue("SpouseBirthDt"),
    ),
    "If 'PINTypeCd' in the Return Header has the value \"Self-Select Practitioner\" and 'SpouseSignaturePIN' has a value, then 'SpouseBirthDt' must have a value.",
  ),
  rule(
    "IND-025-02",
    "reject",
    "missing_data",
    ifThen(
      all(eqStr("PINTypeCd", "Self-Select On-Line"), hasValue("PrimaryBirthDt")),
      any(hasValue("PrimaryPriorYearAGIAmt"), hasValue("PrimaryPriorYearPIN"), hasValue("IdentityProtectionPIN")),
    ),
    "If 'PINTypeCd' in the Return Header has the value \"Self-Select On-Line\" and 'PrimaryBirthDt' has a value, then 'PrimaryPriorYearAGIAmt' or 'PrimaryPriorYearPIN' or 'IdentityProtectionPIN' must have a value.",
  ),
  rule(
    "IND-026-02",
    "reject",
    "missing_data",
    ifThen(
      all(eqStr("PINTypeCd", "Self-Select Practitioner"), hasValue("PrimaryBirthDt")),
      any(hasValue("PrimaryPriorYearAGIAmt"), hasValue("PrimaryPriorYearPIN"), hasValue("IdentityProtectionPIN")),
    ),
    "If 'PINTypeCd' in the Return Header has the value \"Self-Select Practitioner\" and 'PrimaryBirthDt' has a value, then 'PrimaryPriorYearAGIAmt' or 'PrimaryPriorYearPIN' or 'IdentityProtectionPIN' must have a value.",
  ),
  rule(
    "IND-027-02",
    "reject",
    "missing_data",
    ifThen(
      all(eqStr("PINTypeCd", "Self-Select On-Line"), hasValue("SpouseBirthDt")),
      any(hasValue("SpousePriorYearAGIAmt"), hasValue("SpousePriorYearPIN"), hasValue("SpouseIdentityProtectionPIN")),
    ),
    "If 'PINTypeCd' in the Return Header has the value \"Self-Select On-Line\" and 'SpouseBirthDt' has a value, then 'SpousePriorYearAGIAmt' or 'SpousePriorYearPIN' or 'SpouseIdentityProtectionPIN' must have a value.",
  ),
  rule(
    "IND-028-02",
    "reject",
    "missing_data",
    ifThen(
      all(eqStr("PINTypeCd", "Self-Select Practitioner"), hasValue("SpouseBirthDt")),
      any(hasValue("SpousePriorYearAGIAmt"), hasValue("SpousePriorYearPIN"), hasValue("SpouseIdentityProtectionPIN")),
    ),
    "If 'PINTypeCd' in the Return Header has the value \"Self-Select Practitioner\" and 'SpouseBirthDt' has a value, then 'SpousePriorYearAGIAmt' or 'SpousePriorYearPIN' or 'SpouseIdentityProtectionPIN' must have a value.",
  ),
  rule(
    "IND-031-04",
    "reject",
    "incorrect_data",
    alwaysPass,
    "'PrimaryPriorYearPIN' or 'PrimaryPriorYearAGIAmt' in the Return Header must match the e-File database. If you are unable to provide a valid 'PrimaryPriorYearPIN' or 'PrimaryPriorYearAGIAmt', then you may instead provide an Identity Protection PIN (IP PIN) to electronically file your return. An IP PIN may not be used if you are filing Form 9465 standalone. If you wish to get an IP PIN and you don't already have an account on IRS.gov, then you must register to validate your identity. Please visit www.irs.gov/getanippin for further information and resubmit your return.",
  ),
  rule(
    "IND-032-04",
    "reject",
    "incorrect_data",
    alwaysPass,
    "'SpousePriorYearPIN' or 'SpousePriorYearAGIAmt' in the Return Header must match the e-File database. If you are unable to provide a valid 'SpousePriorYearPIN' or 'SpousePriorYearAGIAmt', then you may instead provide an Identity Protection PIN (IP PIN) to electronically file your return. An IP PIN may not be used if you are filing Form 9465 standalone. If you wish to get an IP PIN and you don't already have an account on IRS.gov, then you must register to validate your identity. Please visit www.irs.gov/getanippin for further information and resubmit your return.",
  ),
  rule(
    "IND-033-02",
    "reject",
    "incorrect_data",
    dateYearGte("PrimaryDeathDt", "TaxYr"),
    "The year of 'PrimaryDeathDt' must not be less than 'TaxYr' in the Return Header.",
  ),
  rule(
    "IND-034-02",
    "reject",
    "incorrect_data",
    dateYearGte("SpouseDeathDt", "TaxYr"),
    "The year of 'SpouseDeathDt' must not be less than 'TaxYr' in the Return Header.",
  ),
  rule(
    "IND-035-01",
    "reject",
    "database",
    alwaysPass,
    "'PrimaryDeathDt' in the return must match that in the e-File database.",
  ),
  rule(
    "IND-036-01",
    "reject",
    "database",
    alwaysPass,
    "'SpouseDeathDt' in the return must match that in the e-File database.",
  ),
  rule(
    "IND-039-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("ThirdPartyDesigneeInd", "Yes"), hasValue("ThirdPartyDesigneeNm")),
    "If 'ThirdPartyDesigneeInd' in the return has a choice of 'Yes' indicated, then 'ThirdPartyDesigneeNm' must have a value.",
  ),
  rule(
    "IND-040-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("ThirdPartyDesigneeInd", "Yes"), hasValue("ThirdPartyDesigneePhoneNum")),
    "If 'ThirdPartyDesigneeInd' in the return has a choice of \"Yes\" indicated, then Third Party Designee Phone Number must have a value.",
  ),
  rule(
    "IND-041",
    "reject",
    "incorrect_data",
    ifThen(eqStr("ThirdPartyDesigneeInd", "Yes"), hasValue("ThirdPartyDesigneePIN")),
    "If 'ThirdPartyDesigneeInd' in the return has a choice of 'Yes' indicated, then 'ThirdPartyDesigneePIN' must have a value.",
  ),
  rule(
    "IND-042-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("PowerOfAttorneySignedByInd"), noValue("SurvivingSpouseInd")),
    "If checkbox 'PowerOfAttorneySignedByInd' is checked in the return, then checkbox 'SurvivingSpouseInd' must not be checked.",
  ),
  rule(
    "IND-043-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("PowerOfAttorneySignedByInd"), noValue("PersonalRepresentativeInd")),
    "If checkbox 'PowerOfAttorneySignedByInd' is checked in the return, then checkbox 'PersonalRepresentativeInd' must not be checked.",
  ),
  rule(
    "IND-044-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("PowerOfAttorneySignedByInd"), noValue("PrimaryDeathDt")),
    "If checkbox 'PowerOfAttorneySignedByInd' is checked in the return, then 'PrimaryDeathDt' must not have a value.",
  ),
  rule(
    "IND-052",
    "reject_and_stop",
    "data_mismatch",
    eqField("ManifestTIN", "PrimarySSN"),
    "The TIN present in the IRS Submission Manifest must be equal to the Primary SSN in the Return Header.",
  ),
  rule(
    "IND-054-01",
    "reject",
    "incorrect_data",
    ifThen(filingStatusIs(3), noValue("SpouseSignaturePIN")),
    "If filing status is \"Married filing separately\" (element 'IndividualReturnFilingStatusCd' has the value 3), then 'SpouseSignaturePIN' must not have a value in the Return Header.",
  ),
  rule(
    "IND-055-02",
    "reject",
    "incorrect_data",
    noValue("AddressLine2Txt"),
    "'AddressLine2Txt' in the Return Header must not have a value.",
  ),
  rule(
    "IND-056-02",
    "reject",
    "missing_data",
    ifThen(
      hasValue("PrimarySignaturePIN"),
      any(hasValue("PrimaryPINEnteredByCd"), hasValue("ParentGrdnLegalResponsibleGrp")),
    ),
    "If 'PrimarySignaturePIN' in the Return Header has a value, then 'PrimaryPINEnteredByCd' or 'ParentGrdnLegalResponsibleGrp' must have a value.",
  ),
  rule(
    "IND-057-01",
    "reject",
    "missing_data",
    ifThen(hasValue("SpouseSignaturePIN"), hasValue("SpousePINEnteredByCd")),
    "If 'SpouseSignaturePIN' has a value in the Return Header, then 'SpousePINEnteredByCd' must have a value.",
  ),
  rule(
    "IND-058-01",
    "reject",
    "missing_data",
    ifThen(hasValue("PrimarySignaturePIN"), hasValue("PrimarySignatureDt")),
    "If 'PrimarySignaturePIN' has a value in the Return Header, then 'PrimarySignatureDt' must have a value.",
  ),
  rule(
    "IND-059-01",
    "reject",
    "missing_data",
    ifThen(hasValue("SpouseSignaturePIN"), hasValue("SpouseSignatureDt")),
    "If 'SpouseSignaturePIN' has a value in the Return Header, then 'SpouseSignatureDt' must have a value.",
  ),
  rule(
    "IND-060",
    "reject_and_stop",
    "incorrect_data",
    not(eqStr("IdentityProtectionPIN", "000000")),
    "Identity Protection PIN must not equal all zeroes.",
  ),
  rule(
    "IND-061",
    "reject",
    "incorrect_data",
    alwaysPass,
    "IRS ES Payment Record must not be present in a prior year return.",
  ),
  rule(
    "IND-062",
    "reject",
    "missing_data",
    hasValue("IPAddress"),
    "IP Address of the Transmitter must have a value.",
  ),
  rule(
    "IND-063",
    "reject",
    "missing_data",
    hasValue("Timestamp"),
    "Timestamp of the Transmitter must have a value.",
  ),
  rule(
    "IND-064",
    "reject",
    "incorrect_data",
    alwaysPass,
    "IP Address of the Transmitter must be a valid IP Address.",
  ),
  rule(
    "IND-067-10",
    "alert",
    "missing_data",
    alwaysPass,
    "As a paid tax preparer of a return (1) with filing status Head of household or (2) claiming Earned Income Tax Credit or American Opportunity Tax Credit or Child Tax Credit or Additional Child Tax Credit or Credit for Other Dependents, you must complete and submit Form 8867 to the IRS with the original submission of each return. Failure to submit Form 8867 is a violation of IRC Sec 6695(g) and a $650 penalty may be imposed per failure, with a maximum penalty amount of $2,600 per return. This alert is for your information only. Do not send us the missing Form 8867 or amend any returns to include the missing Form 8867. We will continue to monitor future returns you prepare that claim these benefits to ensure you meet your due diligence requirement.",
  ),
  rule(
    "IND-071",
    "reject",
    "incorrect_data",
    ifThen(
      all(hasNonZero("OverpaidAmt"), gt("EsPenaltyAmt", 0), not(notGtField("EsPenaltyAmt", "OverpaidAmt"))),
      hasNonZero("OwedAmt"),
    ),
    "If 'OverpaidAmt' in the return has a non-zero value and 'EsPenaltyAmt' is greater than 'OverpaidAmt', then 'OwedAmt' must have a non-zero value.",
  ),
  rule(
    "IND-072",
    "reject",
    "incorrect_data",
    ifThen(
      all(hasNonZero("OverpaidAmt"), notGtField("EsPenaltyAmt", "OverpaidAmt")),
      isZero("OwedAmt"),
    ),
    "If 'OverpaidAmt' in the return has a non-zero value and 'EsPenaltyAmt' is less than or equal to 'OverpaidAmt', then 'OwedAmt' must be equal to zero if an amount is entered.",
  ),
  rule(
    "IND-073",
    "reject",
    "math_error",
    ifThen(
      gt("OverpaidAmt", 0),
      eqSum("OverpaidAmt", "RefundAmt", "AppliedToEsTaxAmt", "EsPenaltyAmt"),
    ),
    "If 'OverpaidAmt' in the return is greater than 'EsPenaltyAmt', then the sum of ['RefundAmt' and 'AppliedToEsTaxAmt' and 'EsPenaltyAmt'] must be equal to 'OverpaidAmt'.",
  ),
  rule(
    "IND-074",
    "reject",
    "missing_data",
    ifThen(
      not(eqField("TotalPaymentsAmt", "TotalTaxAmt")),
      any(hasNonZero("OverpaidAmt"), hasNonZero("RefundAmt"), hasNonZero("AppliedToEsTaxAmt"), hasNonZero("OwedAmt")),
    ),
    "If 'TotalPaymentsAmt' in the return is not equal to 'TotalTaxAmt', then one of the following must have a non-zero value: 'OverpaidAmt' or 'RefundAmt' or 'AppliedToEsTaxAmt' or 'OwedAmt'.",
  ),
  rule(
    "IND-075",
    "reject",
    "incorrect_data",
    ifThen(
      hasNonZero("OverpaidAmt"),
      gt("TotalPaymentsAmt", 0),
    ),
    "If 'OverpaidAmt' in the return has a non-zero value, then 'TotalPaymentsAmt' must be greater than 'TotalTaxAmt'.",
  ),
  rule(
    "IND-076",
    "reject",
    "incorrect_data",
    ifThen(
      all(
        not(notGtField("TotalPaymentsAmt", "TotalTaxAmt")),
        eqSum("OverpaidAmt", "AppliedToEsTaxAmt", "EsPenaltyAmt"),
      ),
      isZero("RefundAmt"),
    ),
    "If 'TotalPaymentsAmt' in the return is greater than 'TotalTaxAmt' and [the sum of 'AppliedToEsTaxAmt' and 'EsPenaltyAmt' is equal to 'OverpaidAmt'], then 'RefundAmt' must be equal to zero if an amount is entered.",
  ),
  rule(
    "IND-077",
    "reject",
    "incorrect_data",
    ifThen(
      all(
        not(notGtField("TotalPaymentsAmt", "TotalTaxAmt")),
        not(eqSum("OverpaidAmt", "AppliedToEsTaxAmt", "EsPenaltyAmt")),
      ),
      hasNonZero("RefundAmt"),
    ),
    "If 'TotalPaymentsAmt' in the return is greater than 'TotalTaxAmt' and [the sum of 'AppliedToEsTaxAmt' and 'EsPenaltyAmt' is less than 'OverpaidAmt'], then 'RefundAmt' must have a non-zero value.",
  ),
  rule(
    "IND-078",
    "reject",
    "incorrect_data",
    ifThen(
      eqField("TotalPaymentsAmt", "TotalTaxAmt"),
      all(isZero("OverpaidAmt"), isZero("RefundAmt"), isZero("AppliedToEsTaxAmt")),
    ),
    "If 'TotalPaymentsAmt' in the return is equal to 'TotalTaxAmt', then the following must be equal to zero if an amount is entered: 'OverpaidAmt' and 'RefundAmt' and 'AppliedToEsTaxAmt'.",
  ),
  rule(
    "IND-079",
    "reject",
    "incorrect_data",
    ifThen(
      all(gt("OverpaidAmt", 0), not(notGtField("EsPenaltyAmt", "OverpaidAmt"))),
      isZero("AppliedToEsTaxAmt"),
    ),
    "If 'OverpaidAmt' in the return is greater than zero and less than 'EsPenaltyAmt', then 'AppliedToEsTaxAmt' must be equal to zero if an amount is entered.",
  ),
  rule(
    "IND-080",
    "reject",
    "math_error",
    ifThen(
      all(gt("OverpaidAmt", 0), not(notGtField("EsPenaltyAmt", "OverpaidAmt"))),
      eqDiff("OwedAmt", "EsPenaltyAmt", "OverpaidAmt"),
    ),
    "If 'OverpaidAmt' in the return is greater than zero and less than 'EsPenaltyAmt', then 'OwedAmt' must be equal to ['EsPenaltyAmt' minus (-) 'OverpaidAmt'].",
  ),
  rule(
    "IND-081",
    "reject",
    "incorrect_data",
    ifThen(
      all(hasNonZero("OwedAmt"), any(isZero("EsPenaltyAmt"), noValue("EsPenaltyAmt"))),
      not(notGtField("TotalTaxAmt", "TotalPaymentsAmt")),
    ),
    "If 'OwedAmt' in the return has a non-zero value and 'EsPenaltyAmt' has a zero value or is not provided, then 'TotalTaxAmt' must be greater than 'TotalPaymentsAmt'.",
  ),
  rule(
    "IND-082",
    "reject",
    "incorrect_data",
    ifThen(hasValue("OwedAmt"), eqField("OwedAmt", "RefundAmt")),
    "If 'OwedAmt' in the return has a value greater than zero, then 'RefundAmt' must be equal to zero if an amount is entered.",
  ),
  rule(
    "IND-083",
    "reject",
    "missing_data",
    any(
      all(hasValue("RoutingTransitNum"), hasValue("BankAccountTypeCd"), hasValue("DepositorAccountNum")),
      all(noValue("RoutingTransitNum"), noValue("BankAccountTypeCd"), noValue("DepositorAccountNum")),
    ),
    "If any of the following fields have a value in the return, then all of the other fields must have a value: 'RoutingTransitNum' and 'BankAccountTypeCd' and 'DepositorAccountNum'.",
  ),
  rule(
    "IND-084",
    "reject",
    "incorrect_data",
    ifThen(
      formPresent("form8888"),
      all(noValue("RoutingTransitNum"), noValue("BankAccountTypeCd"), noValue("DepositorAccountNum")),
    ),
    "If Form 8888 is present in the return, then the following must not have a value in the return: 'RoutingTransitNum' and 'BankAccountTypeCd' and 'DepositorAccountNum'.",
  ),
  rule(
    "IND-085-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Each 'DependentSSN' in 'DependentDetail' on the return must be within the valid range of SSN / ITIN / ATIN.",
  ),
  rule(
    "IND-086-01",
    "reject",
    "duplicate",
    allDistinct("DependentSSN"),
    "Each 'DependentSSN' in 'DependentDetail' ('QualifyingChildIdentifyingNum' in 'QualifyingChildInfoGrp' for 1040-SS) in the return must be unique among all dependent SSNs.",
  ),
  rule(
    "IND-088",
    "reject",
    "incorrect_data",
    alwaysPass,
    "For each dependent in 'DependentDetail' in the return, if 'EligibleForChildTaxCreditInd' is checked, then the corresponding 'DependentRelationshipCd' must have one of the following values: \"STEPCHILD\" or \"HALF BROTHER\" or \"HALF SISTER\" or \"STEPBROTHER\" or \"STEPSISTER\" or \"FOSTER CHILD\" or \"GRANDCHILD\" or \"BROTHER\" or \"SISTER\" or \"NEPHEW\" or \"NIECE\" or \"SON\" or \"DAUGHTER\".",
  ),
  rule(
    "IND-089-01",
    "reject",
    "incorrect_data",
    eqSum("TotalExemptionsCnt", "TotalExemptPrimaryAndSpouseCnt", "ChldWhoLivedWithYouCnt", "OtherDependentsListedCnt"),
    "'TotalExemptionsCnt' in the return must be equal to the sum of the following: 'TotalExemptPrimaryAndSpouseCnt' and 'ChldWhoLivedWithYouCnt' and 'OtherDependentsListedCnt'.",
  ),
  rule(
    "IND-091",
    "reject",
    "missing_document",
    ifThen(hasValue("Form8888Ind"), formPresent("form8888")),
    "If 'Form8888Ind' is checked in the return, then Form 8888 must be attached to 'Form8888Ind'.",
  ),
  rule(
    "IND-092",
    "reject",
    "missing_data",
    ifThen(formPresent("form8888"), hasValue("Form8888Ind")),
    "If Form 8888 is present in the return, then 'Form8888Ind' must be checked.",
  ),
  rule(
    "IND-096",
    "reject",
    "incorrect_data",
    ifThen(hasValue("CapitalDistributionInd"), hasNonZero("CapitalGainLossAmt")),
    "If 'CapitalDistributionInd' is checked in the return, then 'CapitalGainLossAmt' must have a non-zero value.",
  ),
  rule(
    "IND-098-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If 'CTCODCAmt' in the return has a non-zero value, then it must not be greater than the sum of [ (the number of dependents with 'EligibleForChildTaxCreditInd' checked multiplied by 2000) and (the number of dependents with 'EligibleForODCInd' checked multiplied by 500) ].",
  ),
  rule(
    "IND-100",
    "reject_and_stop",
    "unsupported",
    alwaysPass,
    "Prior Year Individual Returns are not being accepted by Modernized e-File (MeF) at this time. Please check the MeF web page under irs.gov for more information. The submission type filed was <type>.",
  ),
  rule(
    "IND-113",
    "reject",
    "incorrect_data",
    ifThen(hasValue("CapitalDistributionInd"), formAbsent("schedule_d")),
    "If 'CapitalDistributionInd' is checked in the return, then Schedule D (Form 1040) must not be present.",
  ),
  rule(
    "IND-114",
    "reject",
    "missing_document",
    ifThen(
      all(not(hasValue("CapitalDistributionInd")), hasNonZero("CapitalGainLossAmt")),
      formPresent("schedule_d"),
    ),
    "If 'CapitalDistributionInd' in the return is not checked and 'CapitalGainLossAmt' has a non-zero value, then Schedule D (Form 1040) must be attached to 'CapitalGainLossAmt'.",
  ),
  rule(
    "IND-116-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Each dependent in 'DependentDetail' on the return with 'EligibleForChildTaxCreditInd' checked must be under the age of 17. You may be eligible to claim the \"Credit for other dependents\" if you meet the requirements for the credit.",
  ),
  rule(
    "IND-117",
    "reject",
    "incorrect_data",
    ifThen(isZero("TotalTaxBeforeCrAndOthTaxesAmt"), isZero("CreditForChildAndDepdCareAmt")),
    "If 'TotalTaxBeforeCrAndOthTaxesAmt' in the return has a zero value or is not provided, then Form 2441, 'CreditForChildAndDepdCareAmt' must be zero if an amount is entered.",
  ),
  rule(
    "IND-122",
    "reject",
    "incorrect_data",
    ifThen(
      all(formPresent("schedule_d"), formPresent("schedule_j")),
      not(notGtField("AverageFarmIncomeTaxAmt", "TaxAmt")),
    ),
    "If Schedule D (Form 1040) and Schedule J (Form 1040) are present in the return, then 'TaxAmt' in the return must not be less than Schedule J (Form 1040), 'AverageFarmIncomeTaxAmt'.",
  ),
  rule(
    "IND-126",
    "reject",
    "incorrect_data",
    ifThen(hasValue("Form8814Ind"), hasNonZero("ChildInterestAndDividendTaxAmt")),
    "If 'Form8814Ind' in the return is checked, then 'childInterestAndDividendTaxAmt' must have a non-zero value.",
  ),
  rule(
    "IND-127",
    "reject",
    "missing_document",
    ifThen(hasValue("Form8814Ind"), formPresent("form8814")),
    "If 'Form8814Ind' in the return is checked, then Form 8814 must be attached to 'Form8814Ind'.",
  ),
  rule(
    "IND-128",
    "reject",
    "missing_data",
    ifThen(formPresent("form8814"), hasValue("Form8814Ind")),
    "If Form 8814 is present in the return, then 'Form8814Ind' in the return must be checked.",
  ),
  rule(
    "IND-129",
    "reject",
    "data_mismatch",
    eqField("ChildInterestAndDividendTaxAmt", "ChildInterestAndDividendTaxAmt"),
    "'childInterestAndDividendTaxAmt' in the return must be equal to the sum of all Forms 8814, 'ChildInterestAndDividendTaxAmt'.",
  ),
  rule(
    "IND-131",
    "reject",
    "missing_document",
    ifThen(eqStr("Form8814Cd", "FORM 8814"), formPresent("form8814")),
    "If 'Form8814Cd' in the return has the value \"FORM 8814\", then Form 8814 must be present in the return.",
  ),
  rule(
    "IND-132",
    "reject",
    "missing_document",
    ifThen(hasValue("Form4972Ind"), formPresent("form4972")),
    "If 'Form4972Ind' in the return is checked, then Form 4972 must be attached to 'Form4972Ind'.",
  ),
  rule(
    "IND-133",
    "reject",
    "missing_document",
    alwaysPass,
    "For each dependent in 'DependentDetail' in the return, if 'DiedLiteralCd' has the value \"DIED\", then a binary attachment with Description beginning with \"BirthCertificate\" or \"DeathCertificate\" or \"HospitalMedicalRecords\" must be present in the return.",
  ),
  rule(
    "IND-140",
    "reject",
    "missing_document",
    ifThen(eqStr("ScheduleQCd", "SCH Q"), formPresent("schedule_e")),
    "If 'ScheduleQCd' in the return has the value \"SCH Q\", then Schedule E (Form 1040) must be present in the return.",
  ),
  rule(
    "IND-145-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Bona fide residents of Puerto Rico with income excluded under Internal Revenue Code Section 933 should file Form 1040-PR or Form 1040-SS to claim Additional Child Tax Credit.",
  ),
  rule(
    "IND-153-01",
    "reject",
    "data_mismatch",
    ifThen(hasValue("AdditionalChildTaxCreditAmt"), eqField("AdditionalChildTaxCreditAmt", "AdditionalChildTaxCreditAmt")),
    "'AdditionalChildTaxCreditAmt' in the return must be equal to Schedule 8812 (Form 1040), 'AdditionalChildTaxCreditAmt'.",
  ),
  rule(
    "IND-154-02",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If 'CTCODCAmt' or 'AdditionalChildTaxCreditAmt' in the return has a non-zero value, then each 'DependentSSN' in 'DependentDetail' with corresponding 'EligibleForChildTaxCreditInd' checked must not be an ITIN or ATIN. You may be eligible to claim the \"Credit for other dependents\" if the child resided with you in the United States and you meet the other requirements for the credit.",
  ),
  rule(
    "IND-161",
    "reject",
    "incorrect_data",
    ifThen(hasValue("QualifyingPersonSSN"), validSSN("QualifyingPersonSSN")),
    "If 'QualifyingPersonSSN' in the return has a value, then it must be within the valid range of SSN/ITIN/ATIN.",
  ),
  rule(
    "IND-162",
    "alert",
    "information",
    alwaysPass,
    "Thank you for using e-File.",
  ),
  rule(
    "IND-164",
    "reject",
    "incorrect_data",
    alwaysPass,
    "MeF is not currently accepting Form 9465 attached to prior year returns.  Please file Form 9465 as a stand-alone using the latest 9465 schema package.",
  ),
  rule(
    "IND-165-01",
    "reject",
    "missing_document",
    alwaysPass,
    "Form 8862 must be present in the return with Child Tax Credit/Additional Child Tax Credit/Credit for Other Dependents Indicator checked. The e-File database indicates the taxpayer must file Form 8862 to claim Child Tax Credit or Other Dependent Credit or Additional Child Tax Credit after disallowance.",
  ),
  rule(
    "IND-168-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "'CTCODCAmt' and 'AdditionalChildTaxCreditAmt' in the return must be zero if an amount is entered. The e-File database indicates the taxpayer is not allowed to claim Child Tax Credit or Other Dependent Credit or Additional Child Tax Credit.",
  ),
  rule(
    "IND-180-01",
    "reject_and_stop",
    "database",
    alwaysPass,
    "Primary taxpayer's Identity Protection Personal Identification Number (IP PIN) must match the e-File database. Please double check your entry and resubmit your return with the correct number.",
  ),
  rule(
    "IND-181-01",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Primary Taxpayer did not enter a valid Identity Protection Personal Identification Number (IP PIN). Please visit www.irs.gov/getanippin for further information and resubmit your return with the correct number.",
  ),
  rule(
    "IND-182-01",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Spouse Identity Protection Personal Identification Number (IP PIN) must match the e-File database. Please double check your entry and resubmit your return with the correct number.",
  ),
  rule(
    "IND-183-01",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Spouse did not enter a valid Identity Protection Personal Identification Number (IP PIN). Please visit www.irs.gov/getanippin for further information and resubmit your return with the correct number.",
  ),
  rule(
    "IND-184",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "Prior year original returns may only be filed by [1] online filers with an Identity Protection PIN (IP PIN) for the current calendar year or [2] practitioners. If you wish to get an IP PIN and you don't already have an account on IRS.gov, then you must register to validate your identity. Separate IP PINs will be required for the primary and secondary taxpayers if filing jointly. Please visit www.irs.gov/getanippin for further information and resubmit your return with an IP PIN.",
  ),
  rule(
    "IND-189",
    "reject_and_stop",
    "missing_data",
    hasValue("AtSubmissionCreationGrpDeviceId"),
    "'DeviceId' in 'AtSubmissionCreationGrp' in 'FilingSecurityInformation' in the Return Header must have a value.",
  ),
  rule(
    "IND-190",
    "reject_and_stop",
    "missing_data",
    hasValue("AtSubmissionFilingGrpDeviceId"),
    "'DeviceId' in 'AtSubmissionFilingGrp' in 'FilingSecurityInformation' in the Return Header must have a value.",
  ),
  rule(
    "IND-191",
    "reject_and_stop",
    "missing_data",
    hasValue("AtSubmissionCreationGrpDeviceTypeCd"),
    "'DeviceTypeCd' in 'AtSubmissionCreationGrp' in 'FilingSecurityInformation' in the Return Header must have a value.",
  ),
  rule(
    "IND-192-01",
    "reject_and_stop",
    "missing_data",
    hasValue("RefundDisbursementCd"),
    "'RefundDisbursementCd' in each 'RefundDisbursementGrp' in 'AtSubmissionFilingGrp' in 'AdditionalFilerInformation' in the Return Header must have a value.",
  ),
  rule(
    "IND-193-02",
    "reject_and_stop",
    "missing_data",
    hasValue("RefundDisbursementGrpRoutingTransitNum"),
    "'RoutingTransitNum' in each 'RefundDisbursementGrp' in 'AtSubmissionFilingGrp' in 'AdditionalFilerInformation' in the Return Header must have a value.",
  ),
  rule(
    "IND-194-02",
    "reject_and_stop",
    "missing_data",
    hasValue("RefundDisbursementGrpDepositorAccountNum"),
    "'DepositorAccountNum' in each 'RefundDisbursementGrp' in 'AtSubmissionFilingGrp' in 'AdditionalFilerInformation' in the Return Header must have a value.",
  ),
  rule(
    "IND-195-01",
    "reject_and_stop",
    "missing_data",
    hasValue("AtSubmissionCreationGrpIPAddress"),
    "'IPAddress' in 'AtSubmissionCreationGrp' in 'FilingSecurityInformation' in the Return Header must have a valid value.",
  ),
  rule(
    "IND-196-01",
    "reject_and_stop",
    "missing_data",
    hasValue("AtSubmissionFilingGrpIPAddress"),
    "'IPAddress' in 'AtSubmissionFilingGrp' in 'FilingSecurityInformation' in the Return Header must have a valid value.",
  ),
  rule(
    "IND-197",
    "reject_and_stop",
    "missing_data",
    hasValue("TotActiveTimePrepSubmissionTs"),
    "'TotActiveTimePrepSubmissionTs' in 'FilingSecurityInformation' in the Return Header must have a value.",
  ),
  rule(
    "IND-198",
    "reject_and_stop",
    "missing_data",
    hasValue("RefundProductElectionInd"),
    "'RefundProductElectionInd' in 'AtSubmissionFilingGrp' in 'AdditionalFilerInformation' must have a choice of \"Yes\" or \"No\" indicated.",
  ),
  rule(
    "IND-199-02",
    "reject_and_stop",
    "missing_data",
    hasValue("AtSubmissionCreationGrpRoutingTransitNum"),
    "'RoutingTransitNum' in 'AtSubmissionCreationGrp' in 'AdditionalFilerInformation' in the Return Header must have a value.",
  ),
  rule(
    "IND-200-02",
    "reject_and_stop",
    "missing_data",
    hasValue("AtSubmissionCreationGrpDepositorAccountNum"),
    "'DepositorAccountNum' in 'AtSubmissionCreationGrp' in 'AdditionalFilerInformation' in the Return Header must have a value.",
  ),
  rule(
    "IND-201-02",
    "reject_and_stop",
    "missing_data",
    hasValue("BankAccountDataCapturedTs"),
    "'BankAccountDataCapturedTs' in 'AtSubmissionCreationGrp' in 'AdditionalFilerInformation' in the Return Header must have a value.",
  ),
  rule(
    "IND-202",
    "reject_and_stop",
    "missing_data",
    hasValue("VendorControlNum"),
    "'VendorControlNum' in 'FilingSecurityInformation' in the Return Header must have a value.",
  ),
  rule(
    "IND-203",
    "reject_and_stop",
    "missing_data",
    hasValue("AtSubmissionFilingGrpDeviceTypeCd"),
    "'DeviceTypeCd' in 'AtSubmissionFilingGrp' in 'FilingSecurityInformation' in the Return Header must have a value.",
  ),
  rule(
    "IND-234",
    "reject",
    "incorrect_data",
    ifThen(
      hasNonZero("ChildNetAdjustedIncomeAmt"),
      eqStr("OtherIncomeLitCd", "FORM 8814"),
    ),
    "If Form 8814, 'ChildNetAdjustedIncomeAmt' has a non-zero value, then 'OtherIncomeLitCd' must have the value \"FORM 8814\" in [OtherIncomeTypeStatement].",
  ),
  rule(
    "IND-241-04",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If 'AdditionalChildTaxCreditAmt' in the return has a value greater than zero, then it must not be greater than [ the number of dependents in 'DependentDetail' with 'EligibleForChildTaxCreditInd' checked multiplied by 1700 ].",
  ),
  rule(
    "IND-282-01",
    "reject",
    "missing_data",
    ifThen(
      any(hasNonZero("Form8697NetAmtOfInterestOwedAmt"), hasNonZero("Form8866NetAmtOfInterestOwedAmt")),
      hasNonZero("LookBackIntSect167gOr460bAmt"),
    ),
    "If Form 8697, 'NetAmtOfInterestOwedAmt' in 'TotLookBackRegularMethodGrp', or Form 8866, 'NetAmtOfInterestOwedAmt' has a non-zero value, then Schedule 2 (Form 1040), 'LookBackIntSect167gOr460bAmt' must have a non-zero value.",
  ),
  rule(
    "IND-288",
    "reject",
    "data_mismatch",
    ifThen(hasValue("TotalAdditionalIncomeAmt"), eqField("TotalAdditionalIncomeAmt", "TotalAdditionalIncomeAmt")),
    "'TotalAdditionalIncomeAmt' in the return must be equal to Schedule 1 (Form 1040), 'TotalAdditionalIncomeAmt'.",
  ),
  rule(
    "IND-289",
    "reject",
    "data_mismatch",
    ifThen(hasValue("TotalAdjustmentsAmt"), eqField("TotalAdjustmentsAmt", "TotalAdjustmentsAmt")),
    "'TotalAdjustmentsAmt' in the return must be equal to Schedule 1 (Form 1040), 'TotalAdjustmentsAmt'.",
  ),
  rule(
    "IND-290",
    "reject",
    "data_mismatch",
    ifThen(hasValue("TotalOtherTaxesAmt"), eqField("TotalOtherTaxesAmt", "TotalOtherTaxesAmt")),
    "'TotalOtherTaxesAmt' in the return must be equal to Schedule 2 (Form 1040), 'TotalOtherTaxesAmt'.",
  ),
  rule(
    "IND-291",
    "reject",
    "data_mismatch",
    ifThen(hasValue("TotalOtherPaymentsRfdblCrAmt"), eqField("TotalOtherPaymentsRfdblCrAmt", "TotalOtherPaymentsRfdblCrAmt")),
    "'TotalOtherPaymentsRfdblCrAmt' in the return must be equal to Schedule 3 (Form 1040), 'TotalOtherPaymentsRfdblCrAmt'.",
  ),
  rule(
    "IND-292",
    "reject",
    "math_error",
    ifThen(
      hasNonZero("TotalCreditsAmt"),
      eqSum("TotalCreditsAmt", "CTCODCAmt", "TotalNonrefundableCreditsAmt"),
    ),
    "If 'TotalCreditsAmt' in the return has a non-zero value, then it must be equal to 'CTCODCAmt' plus (+) Schedule 3 (Form 1040), 'TotalNonrefundableCreditsAmt'.",
  ),
  rule(
    "IND-298-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If 'RefundAmt' in the return has a non-zero value and the filing status of the return is married filing jointly and both 'PrimaryDeathDt' and 'SpouseDeathDt' have values, then one of the following must be true: (1) two Forms 1310 are present in the return or (2) two binary attachments with Description \"Personal Representative Court Certificate\" are present or (3) one Form 1310 is present and a binary attachment with Description \"Personal Representative Court Certificate\" is present.",
  ),
  rule(
    "IND-299",
    "reject",
    "multiple_documents",
    ifThen(
      all(hasNonZero("RefundAmt"), filingStatusNot(2), hasValue("PrimaryDeathDt")),
      formPresent("form1310"),
    ),
    "If 'RefundAmt' in the return has a non-zero value and the filing status of the return is not married filing jointly and 'PrimaryDeathDt' has a value, then no more than one Form 1310 must be present.",
  ),
  rule(
    "IND-300-01",
    "reject",
    "missing_document",
    ifThenUnless(
      all(hasNonZero("RefundAmt"), filingStatusNot(2), hasValue("PrimaryDeathDt")),
      formPresent("form1310"),
      hasValue("PersonalRepresentativeCourtCertificate"),
    ),
    "If 'RefundAmt' in the return has a non-zero value and the filing status of the return is not married filing jointly and 'PrimaryDeathDt' has a value, then [ Form 1310 must be present in the return ] unless a binary attachment with Description \"Personal Representative Court Certificate\" is present.",
  ),
  rule(
    "IND-368-01",
    "reject",
    "missing_document",
    ifThen(
      gt("NetOperatingLossDeductionAmt", 0),
      formPresent("NetOperatingLossCarryforwardDeductionStatement"),
    ),
    "If Schedule 1 (Form 1040), 'NetOperatingLossDeductionAmt' has a value greater than zero, then [NetOperatingLossCarryforwardDeductionStatement] must be present in the return.",
  ),
  rule(
    "IND-369-01",
    "reject",
    "incorrect_data",
    ifThen(
      formPresent("NetOperatingLossCarryforwardDeductionStatement"),
      gt("NetOperatingLossDeductionAmt", 0),
    ),
    "If [NetOperatingLossCarryforwardDeductionStatement] is present in the return, then Schedule 1 (Form 1040), 'NetOperatingLossDeductionAmt' must have a value greater than zero.",
  ),
  rule(
    "IND-391",
    "reject",
    "math_error",
    eqSum("TotalTaxBeforeCrAndOthTaxesAmt", "TaxAmt", "AdditionalTaxAmt"),
    "'TotalTaxBeforeCrAndOthTaxesAmt' in the return must be equal to 'TaxAmt' plus (+) Schedule 2 (Form 1040), 'AdditionalTaxAmt'.",
  ),
  rule(
    "IND-392",
    "reject",
    "missing_document",
    ifThen(hasValue("Form8854DeferredTaxGrp"), formPresent("form8854")),
    "If 'Form8854DeferredTaxGrp' has a value in the return, then Form 8854 must be present.",
  ),
  rule(
    "IND-412",
    "reject",
    "incorrect_data",
    ifThen(hasValue("RefundAmt"), eqField("RefundAmt", "OwedAmt")),
    "If 'RefundAmt' in the return has a value greater than zero, then 'OwedAmt' must be equal to zero if an amount is entered.",
  ),
  rule(
    "IND-418",
    "reject",
    "missing_data",
    ifThen(filingStatusIs(2), hasValue("SpousePINEnteredByCd")),
    "If the filing status of the return is married filing jointly, then 'SpousePINEnteredByCd' in the Return Header must have a value.",
  ),
  rule(
    "IND-424",
    "reject",
    "missing_data",
    ifThen(
      all(filingStatusIs(2), any(hasValue("PrimaryDeathDt"), hasValue("SpouseDeathDt"))),
      hasValue("SurvivingSpouseInd"),
    ),
    "If the filing status of the return is married filing jointly and either 'PrimaryDeathDt' or 'SpouseDeathDt' has a value, then 'SurvivingSpouseInd' must be checked.",
  ),
  rule(
    "IND-425",
    "reject",
    "missing_data",
    ifThen(
      all(filingStatusNot(2), hasValue("PrimaryDeathDt")),
      hasValue("PersonalRepresentativeInd"),
    ),
    "If the filing status of the return is not married filing jointly and 'PrimaryDeathDt' has a value, then 'PersonalRepresentativeInd' must be checked.",
  ),
  rule(
    "IND-426",
    "reject",
    "missing_data",
    ifThen(
      all(filingStatusIs(2), hasValue("PrimaryDeathDt"), hasValue("SpouseDeathDt")),
      hasValue("PersonalRepresentativeInd"),
    ),
    "If the filing status of the return is married filing jointly and both 'PrimaryDeathDt' and 'SpouseDeathDt' have values, then 'PersonalRepresentativeInd' must be checked.",
  ),
  rule(
    "IND-428",
    "reject",
    "incorrect_data",
    ifThen(
      all(filingStatusNot(2), hasValue("PrimaryDeathDt")),
      any(contains("NameLine1Txt", " DECD"), contains("NameLine1Txt", "<DECD")),
    ),
    "If the filing status of the return is not married filing jointly and 'PrimaryDeathDt' has a value, then 'NameLine1Txt' in the Return Header must contain \" DECD\" or \"<DECD\".",
  ),
  rule(
    "IND-429",
    "reject",
    "incorrect_data",
    ifThen(
      all(filingStatusIs(2), hasValue("PrimaryDeathDt")),
      contains("NameLine1Txt", "DECD &"),
    ),
    "If the filing status of the return is married filing jointly and 'PrimaryDeathDt' has a value, then 'NameLine1Txt' in the Return Header must contain \"DECD &\".",
  ),
  rule(
    "IND-430",
    "reject",
    "incorrect_data",
    ifThen(
      all(filingStatusIs(2), hasValue("SpouseDeathDt")),
      contains("NameLine1Txt", " DECD"),
    ),
    "If the filing status of the return is married filing jointly and 'SpouseDeathDt' has a value, then 'NameLine1Txt' in the Return Header must contain \" DECD\".",
  ),
  rule(
    "IND-433",
    "reject",
    "missing_data",
    ifThen(filingStatusNot(2), hasValue("PrimarySignaturePIN")),
    "If the filing status of the return is not married filing jointly, then 'PrimarySignaturePIN' in the Return Header must have a value.",
  ),
  rule(
    "IND-434",
    "reject",
    "missing_data",
    ifThen(filingStatusIs(2, 3), hasValue("SpouseNameControlTxt")),
    "If the filing status of the return is married filing jointly or married filing separately, then 'SpouseNameControlTxt' in the Return Header must have a value.",
  ),
  rule(
    "IND-435",
    "reject",
    "incorrect_data",
    ifThen(filingStatusIs(2), contains("NameLine1Txt", "&")),
    "If the filing status of the return is married filing jointly, then 'NameLine1Txt' in the Return Header must contain an ampersand (&).",
  ),
  rule(
    "IND-443-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Each 'DependentSSN' in 'DependentDetail' (or 'QualifyingChildIdentifyingNum' in 'QualifyingChildInfoGrp') in the return must not be the same as 'PrimarySSN' or 'SpouseSSN' in the Return Header.",
  ),
  rule(
    "IND-449",
    "reject",
    "missing_document",
    ifThen(
      all(hasValue("OtherTaxAmtInd"), eqStr("OtherTaxAmtCd", "FORM 8978")),
      formPresent("form8978"),
    ),
    "If 'OtherTaxAmtInd' is checked in the return and 'OtherTaxAmtCd' has the value \"FORM 8978\", then Form 8978 must be present.",
  ),
  rule(
    "IND-450",
    "alert",
    "incorrect_data",
    alwaysPass,
    "We do not have a record of your prior year return. If you filed a prior year paper return during the current filing season, you must file your amended, superseded, or corrected return on paper. To find a proper mailing address, go to irs.gov/file.",
  ),
  rule(
    "IND-451",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "An amended, superseded or corrected return filed after the due date of the original return cannot have filing status \"Married filing separately\" if the filing status of the original return was \"Married filing jointly\".",
  ),
  rule(
    "IND-452",
    "reject_and_stop",
    "duplicate",
    alwaysPass,
    "In an original return, the Primary SSN in the Return Header must not be the same as the TIN of a previously accepted electronic Individual return filed for the same tax period.",
  ),
  rule(
    "IND-453",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "This post-original return cannot be filed electronically. There is no record of a previously accepted return. Please submit your amended, superseded, or corrected return on paper. To find a proper mailing address, go to irs.gov/file.",
  ),
  rule(
    "IND-461-01",
    "reject",
    "data_mismatch",
    ifThen(hasValue("CTCODCAmt"), eqField("CTCODCAmt", "CTCODCAmt")),
    "'CTCODCAmt' in the return must be equal to Schedule 8812 (Form 1040), 'CTCODCAmt'.",
  ),
  rule(
    "IND-463",
    "reject_and_stop",
    "missing_document",
    ifThen(
      any(hasValue("AmendedReturnInd"), hasValue("SupersededReturnInd")),
      formPresent("form1040x"),
    ),
    "If [ 'AmendedReturnInd' or 'SupersededReturnInd' ] in the return is checked, then Form 1040-X must be present in the return.",
  ),
  rule(
    "IND-464",
    "reject_and_stop",
    "missing_data",
    ifThen(
      formPresent("form1040x"),
      any(hasValue("AmendedReturnInd"), hasValue("SupersededReturnInd")),
    ),
    "If Form 1040-X is present in the return, then [ 'AmendedReturnInd' or 'SupersededReturnInd' ] in the return must be checked.",
  ),
  rule(
    "IND-465",
    "reject_and_stop",
    "incorrect_data",
    ifThen(
      any(hasValue("AmendedReturnInd"), hasValue("SupersededReturnInd")),
      noValue("ImperfectReturnInd"),
    ),
    "If [ 'AmendedReturnInd' or 'SupersededReturnInd' ] in the return is checked, then 'ImperfectReturnInd' in the Return Header must not be checked.",
  ),
  rule(
    "IND-466",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "You have exceeded the limit of post-original returns that can be filed electronically. Please submit your amended, superseded, or corrected return on paper. To find a proper mailing address, go to irs.gov/file.",
  ),
  rule(
    "IND-468",
    "reject",
    "data_mismatch",
    ifThen(hasValue("TaxableBenefitsAmt"), eqField("TaxableBenefitsAmt", "TaxableBenefitsAmt")),
    "'TaxableBenefitsAmt' in the return must be equal to Form 2441, 'TaxableBenefitsAmt'.",
  ),
  rule(
    "IND-469-01",
    "reject",
    "data_mismatch",
    ifThen(hasValue("TaxableBenefitsForm8839Amt"), eqField("TaxableBenefitsForm8839Amt", "TaxableBenefitsForm8839Amt")),
    "'TaxableBenefitsForm8839Amt' in the return must be equal to Form 8839, 'TaxableBenefitsForm8839Amt'.",
  ),
  rule(
    "IND-470",
    "reject",
    "data_mismatch",
    eqField("TotalWagesWithNoWithholdingAmt", "TotalWagesWithNoWithholdingAmt"),
    "'TotalWagesWithNoWithholdingAmt' in the return must be equal to the sum of all Form 8919, 'TotalWagesWithNoWithholdingAmt'.",
  ),
  rule(
    "IND-471",
    "reject",
    "math_error",
    eqSum(
      "WagesSalariesAndTipsAmt",
      "WagesAmt",
      "HouseholdEmployeeWagesAmt",
      "TipIncomeAmt",
      "MedicaidWaiverPymtNotRptW2Amt",
      "TaxableBenefitsAmt",
      "TaxableBenefitsForm8839Amt",
      "TotalWagesWithNoWithholdingAmt",
      "OtherEarnedIncomeAmt",
    ),
    "'WagesSalariesAndTipsAmt' in the return must be equal to the sum of the following: 'WagesAmt' and 'HouseholdEmployeeWagesAmt' and 'TipIncomeAmt' and 'MedicaidWaiverPymtNotRptW2Amt' and 'TaxableBenefitsAmt' and 'TaxableBenefitsForm8839Amt' and 'TotalWagesWithNoWithholdingAmt' and 'OtherEarnedIncomeAmt'.",
  ),
  rule(
    "IND-472",
    "reject",
    "missing_document",
    alwaysPass,
    "For each instance of Form 8332 present in the return, there must be a corresponding binary attachment with description \"8332 Signature Document\" present.",
  ),
  rule(
    "IND-507-01",
    "reject",
    "duplicate",
    alwaysPass,
    "'DependentSSN' in 'DependentDetail' on the return was used as a Dependent SSN on a previously accepted return for the same tax period. Visit www.irs.gov/identity-theft-fraud-scams/identity-theft-dependents for additional information. To electronically file with this duplicate condition, an Identity Protection Personal Identification Number (IP PIN) will be required. If you wish to get an IP PIN and you don't already have an account on IRS.gov, then you must register to validate your identity. Please visit www.irs.gov/getanippin for further information and resubmit your return with an IP PIN.",
  ),
  rule(
    "IND-508-01",
    "reject",
    "database",
    alwaysPass,
    "The Primary SSN in the Return Header must not be the same as the Spouse SSN on another return for the same tax year with filing status Married filing jointly.",
  ),
  rule(
    "IND-510-02",
    "reject",
    "duplicate",
    alwaysPass,
    "The Spouse SSN in the return must not be the same as the Primary SSN on another return filed for the same tax year.",
  ),
  rule(
    "IND-511-01",
    "reject",
    "database",
    alwaysPass,
    "For the filing status selected in the return, the Primary SSN in the Return Header must not be the same as the Spouse SSN on another return for the same tax year with filing status Married filing separately.",
  ),
  rule(
    "IND-513-01",
    "reject",
    "duplicate",
    alwaysPass,
    "The Spouse SSN in the return must not be the same as the Spouse SSN in another return filed for the same tax year.",
  ),
  rule(
    "IND-515-01",
    "reject",
    "duplicate",
    alwaysPass,
    "The Primary SSN in the Return Header must not be the same as the Primary SSN in another return filed for the same tax year.",
  ),
  rule(
    "IND-517-02",
    "reject",
    "incorrect_data",
    alwaysPass,
    "'DependentSSN' in the return must not be the same as Primary or Spouse SSN on another return where Primary or Spouse have not indicated that they could be claimed as a dependent on someone else's return. Visit www.irs.gov/identity-theft-fraud-scams/identity-theft-dependents for additional information. To electronically file with this duplicate condition, an Identity Protection Personal Identification Number (IP PIN) will be required. If you wish to get an IP PIN and you don't already have an account on IRS.gov, then you must register to validate your identity. Please visit www.irs.gov/getanippin for further information and resubmit your return with an IP PIN.",
  ),
  rule(
    "IND-521-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "The Year of Birth of the Primary SSN must not be greater than the 'TaxYr' in the Return Header.",
  ),
  rule(
    "IND-524",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "If 'PINTypeCd' in the Return Header has the value \"Self-Select On-Line\" and the filing status of the return is not married filing jointly, then 'PrimaryBirthDt' in the Return Header must match the e-File database.",
  ),
  rule(
    "IND-531-01",
    "reject",
    "database",
    alwaysPass,
    "If Primary Date of Death has a value in the e-File database, then it must not be prior to the 'TaxYr' in the Return Header.",
  ),
  rule(
    "IND-532-01",
    "reject",
    "database",
    alwaysPass,
    "If Spouse Date of Death has a value in the e-File database, then it must not be prior to the 'TaxYr' in the Return Header.",
  ),
  rule(
    "IND-544-01",
    "reject",
    "database",
    alwaysPass,
    "If there are dependents provided on the return, then 'PrimarySSN' in the Return Header must not be the same as a Dependent SSN on a previously accepted return for the same tax period. Visit www.irs.gov/identity-theft-fraud-scams/identity-theft-dependents for additional information. To electronically file with this duplicate condition, an Identity Protection Personal Identification Number (IP PIN) will be required. If you wish to get an IP PIN and you don't already have an account on IRS.gov, then you must register to validate your identity. Please visit www.irs.gov/getanippin for further information and resubmit your return with an IP PIN.",
  ),
  rule(
    "IND-563-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "For each dependent in the return with 'EligibleForChildTaxCreditInd' checked, the corresponding 'DependentSSN' must not be the same as a Dependent SSN on another return. Visit www.irs.gov/identity-theft-fraud-scams/identity-theft-dependents for additional information. To electronically file with this duplicate condition, an Identity Protection Personal Identification Number (IP PIN) will be required. If you wish to get an IP PIN and you don't already have an account on IRS.gov, then you must register to validate your identity. Please visit www.irs.gov/getanippin for further information and resubmit your return with an IP PIN.",
  ),
  rule(
    "IND-570-01",
    "reject",
    "database",
    alwaysPass,
    "The Year of Birth of the Spouse SSN must not be greater than the 'TaxYr' in the Return Header.",
  ),
  rule(
    "IND-607",
    "alert",
    "information",
    alwaysPass,
    "A dependent claimed on the return was previously claimed as a dependent on another accepted return for the same tax year. Visit www.irs.gov/identity-theft-fraud-scams/identity-theft-dependents for additional information.",
  ),
  rule(
    "IND-617",
    "alert",
    "information",
    alwaysPass,
    "A dependent claimed on the return was previously claimed as a primary or spouse filer on another accepted return for the same tax year. Visit www.irs.gov/identity-theft-fraud-scams/identity-theft-dependents for additional information.",
  ),
  rule(
    "IND-644",
    "alert",
    "information",
    alwaysPass,
    "The primary filer on the return was previously claimed as a dependent on another accepted return for the same tax year. Visit www.irs.gov/identity-theft-fraud-scams/identity-theft-dependents for additional information.",
  ),
  rule(
    "IND-663",
    "alert",
    "information",
    alwaysPass,
    "A dependent claimed on the return for the Child Tax Credit was previously claimed as a dependent on another accepted return claiming Child Tax Credit for the same tax year. Visit www.irs.gov/identity-theft-fraud-scams/identity-theft-dependents for additional information.",
  ),
  rule(
    "IND-664-02",
    "reject",
    "database",
    alwaysPass,
    "If the Primary SSN in the Return Header appears more than once in the e-File database, then 'PINTypeCd' must not have the value \"Self-Select On-Line\".",
  ),
  rule(
    "IND-665-02",
    "reject",
    "database",
    alwaysPass,
    "If the Primary SSN in the Return Header appears more than once in the e-File database, then 'PINTypeCd' must not have the value \"Self-Select Practitioner\".",
  ),
  rule(
    "IND-666-02",
    "reject",
    "database",
    alwaysPass,
    "If the Spouse SSN in the Return Header appears more than once in the e-File database, then 'PINTypeCd' must not have the value \"Self-Select On-Line\".",
  ),
  rule(
    "IND-667-02",
    "reject",
    "database",
    alwaysPass,
    "If the Spouse SSN in the Return Header appears more than once in the e-File database, then 'PINTypeCd' must not have the value \"Self-Select Practitioner\".",
  ),
  rule(
    "IND-672-01",
    "reject",
    "missing_data",
    ifThen(
      any(eqStr("PINTypeCd", "Practitioner"), eqStr("PINTypeCd", "Self-Select Practitioner")),
      hasValue("PractitionerPINGrp"),
    ),
    "In the Return Header, if 'PINTypeCd' has the value \"Practitioner\" or \"Self-Select Practitioner\", then 'PractitionerPINGrp' must have a value.",
  ),
  rule(
    "IND-673-01",
    "reject",
    "missing_data",
    ifThen(
      eqStr("PINTypeCd", "Self-Select On-Line"),
      noValue("PractitionerPINGrp"),
    ),
    "In the Return Header, if 'PINTypeCd' has the value \"Self-Select On-Line\", then 'PractitionerPINGrp' must not have a value.",
  ),
  rule(
    "IND-674-01",
    "reject",
    "database",
    alwaysPass,
    "If the Primary Taxpayer  is under the age of 16 and has never filed a tax return, then 'PINTypeCd' in the Return Header must not have the value \"Self-Select On-Line\".",
  ),
  rule(
    "IND-675-01",
    "reject",
    "database",
    alwaysPass,
    "If the Primary Taxpayer  is under the age of 16 and has never filed a tax return, then 'PINTypeCd' in the Return Header must not have the value \"Self-Select Practitioner\".",
  ),
  rule(
    "IND-679-01",
    "reject",
    "database",
    alwaysPass,
    "If the Spouse SSN in the Return Header is under the age of 16 and did not file a tax return in the previous year, then the 'PINTypeCd' must not have the value \"Self-Select On-Line\".",
  ),
  rule(
    "IND-680-01",
    "reject",
    "database",
    alwaysPass,
    "If the Spouse SSN in the Return Header is under the age of 16 and did not file a tax return in the previous year, then the 'PINTypeCd' must not have the value \"Self-Select Practitioner\".",
  ),
  rule(
    "IND-689-01",
    "reject",
    "missing_document",
    alwaysPass,
    "The year of the 'PrimarySignatureDt' in the Return Header must be equal to the processing year.",
  ),
  rule(
    "IND-694-01",
    "reject",
    "incorrect_data",
    ifThen(
      eqStr("PINTypeCd", "Self-Select Practitioner"),
      eqStr("JuratDisclosureCd", "Self Select PIN By ERO"),
    ),
    "If 'PINTypeCd' in the Return Header has the value \"Self-Select Practitioner\", then 'JuratDisclosureCd' must have the value \"Self Select PIN By ERO\".",
  ),
  rule(
    "IND-695-01",
    "reject",
    "incorrect_data",
    ifThen(
      eqStr("PINTypeCd", "Practitioner"),
      eqStr("JuratDisclosureCd", "Practitioner PIN"),
    ),
    "If 'PINTypeCd' in the Return Header has the value \"Practitioner\", then 'JuratDisclosureCd' must have the value \"Practitioner PIN\".",
  ),
  rule(
    "IND-696-01",
    "reject",
    "incorrect_data",
    ifThen(
      eqStr("PINTypeCd", "Self-Select On-Line"),
      eqStr("JuratDisclosureCd", "Online Self Select PIN"),
    ),
    "If 'PINTypeCd' in the Return Header has the value \"Self-Select On-Line\", then 'JuratDisclosureCd' must have the value \"Online Self Select PIN\".",
  ),
  rule(
    "IND-699-02",
    "reject",
    "incorrect_data",
    ifThen(
      eqStr("PINTypeCd", "Practitioner"),
      all(
        noValue("PrimaryPriorYearAGIAmt"),
        noValue("PrimaryPriorYearPIN"),
        noValue("SpousePriorYearAGIAmt"),
        noValue("SpousePriorYearPIN"),
      ),
    ),
    "If 'PINTypeCd' in the Return Header has the value \"Practitioner\", then the following must not have a value: 'PrimaryPriorYearAGIAmt' and 'PrimaryPriorYearPIN' and 'SpousePriorYearAGIAmt' and 'SpousePriorYearPIN'.",
  ),
  rule(
    "IND-769",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "Identity Protection PIN must be numeric digits.",
  ),
  rule(
    "IND-901",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Primary SSN in the Return Header has been locked because Social Security Administration records indicate the number belongs to a deceased individual.",
  ),
  rule(
    "IND-902",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Primary SSN in the Return Header has been locked.  The account was locked per the taxpayer's request.",
  ),
  rule(
    "IND-904",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Primary SSN in the Return Header has been locked.  Social Security Administration records indicate the SSN belongs to a minor.  The account was locked per the request of the minor's parent or guardian.",
  ),
  rule(
    "IND-905",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Primary SSN in the Return Header has been systemically locked because the IRS does not accept a replaced SSN as valid for tax filing.",
  ),
  rule(
    "IND-906",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Spouse SSN in the Return Header has been systemically locked because the IRS does not accept a replaced SSN as valid for tax filing.",
  ),
  rule(
    "IND-907",
    "reject_and_stop",
    "database",
    alwaysPass,
    "A Dependent SSN (or Qualifying Child Identifying Number) in the return has been systemically locked because the IRS does not accept a replaced SSN as valid for tax filing.",
  ),
  rule(
    "IND-908",
    "reject_and_stop",
    "database",
    alwaysPass,
    "A Qualifying Person SSN on Form 2441 has been systemically locked because the IRS does not accept a replaced SSN as valid for tax filing.",
  ),
  rule(
    "IND-931-01",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Dependent SSN (or Qualifying Child Identifying Number on Form 1040-SS) has been locked because Social Security Administration records indicate the number belongs to a deceased individual.",
  ),
  rule(
    "IND-932-01",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Dependent SSN (or Qualifying Child Identifying Number on Form 1040-SS) claimed on your return has been locked. The account was locked per the taxpayer's request.",
  ),
  rule(
    "IND-934-01",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Dependent SSN (or Qualifying Child Identifying Number on Form 1040-SS) claimed on your return has been locked. The account was locked per the request of the dependent's parent or guardian.",
  ),
  rule(
    "IND-941-01",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Spouse SSN in the return has been locked because Social Security Administration records indicate the number belongs to a deceased individual.",
  ),
  rule(
    "IND-942-01",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Spouse SSN in the return has been locked.  The account was locked per the taxpayer's request.",
  ),
  rule(
    "IND-943-01",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Spouse SSN in the return has been systemically locked based on IRS information which indicates there is not a filing requirement for this SSN.",
  ),
  rule(
    "IND-944-01",
    "reject_and_stop",
    "database",
    alwaysPass,
    "The Spouse SSN in the return has been locked.  Social Security Administration records indicate the SSN belongs to a minor.  The account was locked per the request of the minor's parent or guardian.",
  ),
  rule(
    "IND-995",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "The Dependent/Qualifying Person Identity Protection Personal Identification Number (IP PIN) must match the e-File database. Please double check your entry and resubmit your return with the correct number.",
  ),
  rule(
    "IND-996",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "The Dependent/Qualifying Person Identity Protection Personal Identification Number (IP PIN) provided on the return is not valid. Please visit www.irs.gov/getanippin for further information and resubmit your return with the correct number.",
  ),
  rule(
    "IND-997",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "The Identity Protection PIN (IP PIN) entered for the primary taxpayer on a prior year online filer return must match the e-File database. Please double-check your entry and resubmit your return with the correct IP PIN.",
  ),
  rule(
    "IND-998",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "The Identity Protection PIN (IP PIN) entered for the secondary taxpayer on a prior year online filer return must match the e-File database. Please double-check your entry and resubmit your return with the correct IP PIN.",
  ),
];
