/**
 * MeF Business Rules: S2
 * Auto-generated from 1040_Business_Rules_2025v3.0.csv
 * 35 rules (32 implemented, 3 stubs)
 */

import type { RuleDef } from "../../../../core/validation/types.ts";
import { rule, alwaysPass, eqField, eqSum, hasValue, hasNonZero, gt, ifThen, isZero, noValue, not, any, all, formPresent, sumOfAll, } from "../../../../core/validation/mod.ts";

export const S2_RULES: readonly RuleDef[] = [
  rule(
    "S2-F1040-001",
    "reject",
    "missing_document",
    ifThen(gt("UncollSSMedcrRRTAGrpInsTxAmt", 0), formPresent("w2")),
    "If Schedule 2 (Form 1040), 'UncollSSMedcrRRTAGrpInsTxAmt' has a value greater than zero, then Form W-2 must be present in the return.",
  ),
  rule(
    "S2-F1040-002",
    "reject",
    "missing_document",
    ifThen(gt("HSADistriAddnlPercentTaxAmt", 0), formPresent("form8889")),
    "If Schedule 2 (F1040) 'HSADistriAddnlPercentTaxAmt' has a value greater than zero, then Form 8889 must be attached to 'HSADistriAddnlPercentTaxAmt'.",
  ),
  rule(
    "S2-F1040-003",
    "reject",
    "missing_document",
    ifThen(gt("HDHPCoverageAddnlTaxAmt", 0), formPresent("form8889")),
    "If Schedule 2 (F1040) 'HDHPCoverageAddnlTaxAmt' has a value greater than zero, then the Form 8889 must be attached to 'HDHPCoverageAddnlTaxAmt'.",
  ),
  rule(
    "S2-F1040-004",
    "reject",
    "math_error",
    eqSum("TotalOtherAdditionalTaxesAmt", "TotalRecaptureOtherCreditsAmt", "MortgSbsdyRecaptureTaxAmt", "HSADistriAddnlPercentTaxAmt", "HDHPCoverageAddnlTaxAmt", "ArcherMSAAddnlDistriTaxAmt", "MedicareMSAAddnlDistriTaxAmt", "RecaptureChrtblContriDedAmt", "IncmNonqlfyDefrdCompPlanAmt", "CompNonqlfyDefrdCompPlanAmt", "Sect72m5ExcessBenefitsTaxAmt", "ExcessParachutePaymentAmt", "PartialTaxOnAccumDistriAmt", "InsiderStockCompExciseTaxAmt", "LookBackIntSect167gOr460bAmt", "IncomeNotUSBusinessTaxAmt", "InterestOnEachNetIncrInTaxAmt", "AccruedInterestDueThisRetAmt", "TotalAnyOtherTaxesAmt"),
    "Schedule 2 (Form 1040), 'TotalOtherAdditionalTaxesAmt' must be equal to the sum of the following: 'TotalRecaptureOtherCreditsAmt' and 'MortgSbsdyRecaptureTaxAmt' and 'HSADistriAddnlPercentTaxAmt' and 'HDHPCoverageAddnlTaxAmt' and 'ArcherMSAAddnlDistriTaxAmt' and 'MedicareMSAAddnlDistriTaxAmt' and 'RecaptureChrtblContriDedAmt' and 'IncmNonqlfyDefrdCompPlanAmt' and 'CompNonqlfyDefrdCompPlanAmt' and 'Sect72m5ExcessBenefitsTaxAmt' and 'ExcessParachutePaymentAmt' and 'PartialTaxOnAccumDistriAmt' and 'InsiderStockCompExciseTaxAmt' and 'LookBackIntSect167gOr460bAmt' and 'IncomeNotUSBusinessTaxAmt' and 'InterestOnEachNetIncrInTaxAmt' and 'AccruedInterestDueThisRetAmt' and 'TotalAnyOtherTaxesAmt'.",
  ),
  rule(
    "S2-F1040-005",
    "reject",
    "data_mismatch",
    ifThen(hasValue("IndivNetInvstIncomeTaxAmt"), eqField("IndivNetInvstIncomeTaxAmt", "IndivNetInvstIncomeTaxAmt")),
    "Schedule 2 (Form 1040), 'IndivNetInvstIncomeTaxAmt' must be equal to Form 8960, 'IndivNetInvstIncomeTaxAmt'.",
  ),
  rule(
    "S2-F1040-006",
    "reject",
    "data_mismatch",
    sumOfAll("InterestOnEachNetIncrInTaxAmt", "InterestOnEachNetIncrInTaxAmt"),
    "Schedule 2 (Form 1040), 'InterestOnEachNetIncrInTaxAmt' must be equal to the sum of all Forms 8621, 'InterestOnEachNetIncrInTaxAmt'.",
  ),
  rule(
    "S2-F1040-007",
    "reject",
    "missing_data",
    ifThen(hasValue("AccruedInterestDueThisRetAmt"), hasValue("AccruedInterestDueThisRetAmt")),
    "If Schedule 2 (Form 1040), 'AccruedInterestDueThisRetAmt' has a value greater than zero, then Form 8621, 'AccruedInterestDueThisRetAmt' must have a value greater than zero.",
  ),
  rule(
    "S2-F1040-008",
    "reject",
    "missing_document",
    ifThen(gt("PartialTaxOnAccumDistriAmt", 0), formPresent("form4970")),
    "If Schedule 2 (Form 1040), 'PartialTaxOnAccumDistriAmt' has a value greater than zero, then Form 4970 must be present in the return.",
  ),
  rule(
    "S2-F1040-009",
    "reject",
    "data_mismatch",
    ifThen(hasValue("TotalAMRRTTaxAmt"), eqField("TotalAMRRTTaxAmt", "TotalAMRRTTaxAmt")),
    "Schedule 2 (Form 1040), 'TotalAMRRTTaxAmt' must be equal to Form 8959, 'TotalAMRRTTaxAmt'.",
  ),
  rule(
    "S2-F1040-010",
    "reject",
    "data_mismatch",
    ifThen(hasValue("MedicareMSAAddnlDistriTaxAmt"), eqField("MedicareMSAAddnlDistriTaxAmt", "MedicareMSAAddnlDistriTaxAmt")),
    "Schedule 2 (Form 1040), 'MedicareMSAAddnlDistriTaxAmt' must be equal to Form 8853, 'MedicareMSAAddnlDistriTaxAmt'.",
  ),
  rule(
    "S2-F1040-011",
    "reject",
    "data_mismatch",
    ifThen(hasValue("MortgSbsdyRecaptureTaxAmt"), eqField("MortgSbsdyRecaptureTaxAmt", "MortgSbsdyRecaptureTaxAmt")),
    "Schedule 2 (Form 1040), 'MortgSbsdyRecaptureTaxAmt' must be equal to Form 8828, 'MortgSbsdyRecaptureTaxAmt'.",
  ),
  rule(
    "S2-F1040-014",
    "reject",
    "math_error",
    sumOfAll("TotalRecaptureOtherCreditsAmt", "OtherCreditsAmt"),
    "Schedule 2 (Form 1040), 'TotalRecaptureOtherCreditsAmt' must be equal to the sum of all 'OtherCreditsAmt' in 'RecaptureOtherCreditsGrp'.",
  ),
  rule(
    "S2-F1040-016",
    "reject",
    "missing_document",
    ifThen(gt("ExPymt100CrAmt", 0), formPresent("form4255")),
    "If Schedule 2 (Form 1040), 'ExPymt100CrAmt' in 'ExcessivePymtFrom4255Grp' has a value greater than zero, then Form 4255 must be present in the return.",
  ),
  rule(
    "S2-F1040-017",
    "reject",
    "missing_document",
    ifThen(gt("TotEx20PrvlWgAprntcshpPnltyAmt", 0), formPresent("form4255")),
    "If Schedule 2 (Form 1040), 'TotEx20PrvlWgAprntcshpPnltyAmt' in 'IncreaseChapter1TaxFrom4255Grp' has a value greater than zero, then Form 4255 must be present in the return.",
  ),
  rule(
    "S2-F1040-018",
    "reject",
    "missing_document",
    ifThen(gt("CrTrnsfrDlrSaleAmt", 0), all(formPresent("form8936"), formPresent("schedule_a_form8936"))),
    "If Schedule 2(Form 1040), 'CrTrnsfrDlrSaleAmt' has a value greater than zero, then Form 8936 and Schedule A (Form 8936) must be present in the return.",
  ),
  rule(
    "S2-F1040-019",
    "reject",
    "missing_document",
    ifThen(gt("PrevOwnCrTrnsfrDlrSaleAmt", 0), all(formPresent("form8936"), formPresent("schedule_a_form8936"))),
    "If Schedule 2(Form 1040), 'PrevOwnCrTrnsfrDlrSaleAmt' has a value greater than zero, then Form 8936 and Schedule A (Form 8936) must be present in the return.",
  ),
  rule(
    "S2-F1040-020",
    "reject",
    "missing_data",
    ifThen(gt("ExPymt100CrAmt", 0), any(hasValue("ApplicableCheckboxiInd"), hasValue("ApplicableCheckboxiiInd"), hasValue("ApplicableCheckboxiiiInd"), hasValue("ApplicableCheckboxivInd"))),
    "In 'ExcessivePymtFrom4255Grp' on Schedule 2(Form 1040), if 'ExPymt100CrAmt' has a value greater than zero, then at least one of the following checkboxes must be checked: 'ApplicableCheckboxiInd', 'ApplicableCheckboxiiInd', 'ApplicableCheckboxiiiInd', 'ApplicableCheckboxivInd'.",
  ),
  rule(
    "S2-F1040-021",
    "reject",
    "missing_data",
    ifThen(gt("TotEx20PrvlWgAprntcshpPnltyAmt", 0), any(hasValue("ApplicableCheckboxiInd"), hasValue("ApplicableCheckboxiiInd"), hasValue("ApplicableCheckboxiiiInd"), hasValue("ApplicableCheckboxivInd"))),
    "In 'IncreaseChapter1TaxFrom4255Grp' on Schedule 2(Form 1040), if 'TotEx20PrvlWgAprntcshpPnltyAmt' has a value greater than zero, then at least one of the following checkboxes must be checked: 'ApplicableCheckboxiInd', 'ApplicableCheckboxiiInd', 'ApplicableCheckboxiiiInd', 'ApplicableCheckboxivInd'.",
  ),
  rule(
    "S2-F1040-022",
    "reject",
    "missing_data",
    ifThen(hasValue("ExemptSETaxLiteralInd"), hasValue("ExemptSETaxLiteralCd")),
    "If Schedule 2(Form 1040), 'ExemptSETaxLiteralInd' is checked, then 'ExemptSETaxLiteralCd' must have a value.",
  ),
  rule(
    "S2-F1040-099-01",
    "reject",
    "missing_data",
    ifThen(hasValue("form5329NotRequiredInd"), gt("TaxOnIRAsAmt", 0)),
    "If Schedule 2 (Form 1040), 'form5329NotRequiredInd' is checked, then 'TaxOnIRAsAmt' must have a value greater than zero.",
  ),
  rule(
    "S2-F1040-109",
    "reject",
    "missing_document",
    ifThen(hasNonZero("UnrprtdSocSecAndMedcrTaxAmt"), any(formPresent("form4137"), formPresent("form8919"))),
    "If Schedule 2 (Form 1040), 'UnrprtdSocSecAndMedcrTaxAmt' has a non-zero value, then Form 4137 or Form 8919 must be present in the return.",
  ),
  rule(
    "S2-F1040-110",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("SocSecMedicareTaxUnrptdTipAmt"), hasNonZero("UnrprtdSocSecAndMedcrTaxAmt")),
    "If Form 4137, 'SocSecMedicareTaxUnrptdTipAmt' has a non-zero value, then Schedule 2 (Form 1040), 'UnrprtdSocSecAndMedcrTaxAmt' must have a non-zero value.",
  ),
  rule(
    "S2-F1040-111-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("UncollectedSocSecMedTaxAmt"), hasValue("UncollectedSocSecMedTaxAmt")),
    "If Form 8919, 'UncollectedSocSecMedTaxAmt' has a value greater than zero, then Schedule 2 (Form 1040), 'UncollectedSocSecMedTaxAmt' must have a value greater than zero.",
  ),
  rule(
    "S2-F1040-121",
    "reject",
    "data_mismatch",
    ifThen(hasValue("AlternativeMinimumTaxAmt"), eqField("AlternativeMinimumTaxAmt", "AlternativeMinimumTaxAmt")),
    "Schedule 2 (Form 1040), 'AlternativeMinimumTaxAmt' must be equal to Form 6251, 'AlternativeMinimumTaxAmt'.",
  ),
  rule(
    "S2-F1040-123-01",
    "reject",
    "math_error",
    alwaysPass, // requires summing fields across variable number of Form 5329 instances — cross-instance aggregation
    "If Schedule 2 (Form 1040), 'TaxOnIRAsAmt' has a non-zero value and 'form5329NotRequiredInd' is not checked, then 'TaxOnIRAsAmt' must be equal to the sum of the following on all Forms 5329: 'IRAEarlyDistributionsTaxAmt' and 'EducIRADistributionsTaxAmt' and 'IRAExcessContribTaxAmt' and 'RothIRAExcessContribTaxAmt' and 'EducIRAExcessContribTaxAmt' and 'MSAExcessContribTaxAmt' and 'HSAExcessContribTaxAmt' and 'ABLEExcessContribTaxAmt' and 'RtmntAnntyExcessContribTaxAmt'.",
  ),
  rule(
    "S2-F1040-135-01",
    "reject",
    "missing_document",
    ifThen(gt("SocSecMedicareTaxUnrptdTipAmt", 0), formPresent("form4137")),
    "If Schedule 2 (Form 1040), 'SocSecMedicareTaxUnrptdTipAmt' has a value greater than zero, then Form 4137 must be attached to 'SocSecMedicareTaxUnrptdTipAmt'.",
  ),
  rule(
    "S2-F1040-143-01",
    "reject",
    "missing_document",
    ifThen(gt("UncollectedSocSecMedTaxAmt", 0), formPresent("form8919")),
    "If Schedule 2 (Form 1040), 'UncollectedSocSecMedTaxAmt' has a value greater than zero, then Form 8919 must be attached to 'UncollectedSocSecMedTaxAmt'.",
  ),
  rule(
    "S2-F1040-146-02",
    "reject",
    "math_error",
    alwaysPass, // requires conditional aggregation across variable number of Schedule H instances — cross-instance check
    "Schedule 2 (Form 1040), 'HouseholdEmploymentTaxAmt' must be equal to the sum of all Schedule H (Form 1040), [ 'TotSocSecMedcrAndFedIncmTaxAmt' plus (+) 'CombinedFUTATaxPlusNetTaxesAmt' ]. If in any Schedule H (Form 1040), both 'TotSocSecMedcrAndFedIncmTaxAmt' and 'CombinedFUTATaxPlusNetTaxesAmt' have non-zero values, include only 'CombinedFUTATaxPlusNetTaxesAmt' in the sum.",
  ),
  rule(
    "S2-F1040-180-01",
    "reject",
    "data_mismatch",
    sumOfAll("SelfEmploymentTaxAmt", "SelfEmploymentTaxAmt"),
    "Schedule 2 (Form 1040), 'SelfEmploymentTaxAmt' must be equal to the sum of all Schedule SE (Form 1040), 'SelfEmploymentTaxAmt'.",
  ),
  rule(
    "S2-F1040-251",
    "reject",
    "data_mismatch",
    ifThen(hasValue("ArcherMSAAddnlDistriTaxAmt"), eqField("ArcherMSAAddnlDistriTaxAmt", "ArcherMSAAddnlDistriTaxAmt")),
    "Schedule 2 (Form 1040), 'ArcherMSAAddnlDistriTaxAmt' must be equal to Form 8853, 'ArcherMSAAddnlDistriTaxAmt'.",
  ),
  rule(
    "S2-F1040-287",
    "reject",
    "missing_document",
    ifThen(gt("RecaptureTaxAmt", 0), formPresent("form8611")),
    "If Schedule 2 (Form 1040), 'RecaptureTaxAmt' has a value greater than zero, then Form 8611 must be present in the return.",
  ),
  rule(
    "S2-F1040-303",
    "reject",
    "missing_document",
    ifThen(gt("HSADistriAddnlPercentTaxAmt", 0), formPresent("form8889")),
    "If Schedule 2 (Form 1040) 'HSADistriAddnlPercentTaxAmt' has a value greater than zero, then Form 8889 must be present in the return.",
  ),
  rule(
    "S2-F1040-437",
    "reject",
    "missing_document",
    ifThen(gt("Section965TaxInstallmentAmt", 0), formPresent("form965a")),
    "If Schedule 2 (Form 1040), 'Section965TaxInstallmentAmt' has a value greater than zero, then Form 965-A must be present in the return.",
  ),
  rule(
    "S2-F1040-801",
    "reject",
    "data_mismatch",
    ifThen(hasValue("PremiumTaxCreditTaxLiabAmt"), eqField("PremiumTaxCreditTaxLiabAmt", "PremiumTaxCreditTaxLiabAmt")),
    "Schedule 2 (Form 1040), 'PremiumTaxCreditTaxLiabAmt' must be equal to Form 8962, 'PremiumTaxCreditTaxLiabAmt'.",
  ),
  rule(
    "S2-F1040-803",
    "reject",
    "missing_document",
    ifThen(hasNonZero("PremiumTaxCreditTaxLiabAmt"), formPresent("form8962")),
    "If Schedule 2 (Form 1040), 'PremiumTaxCreditTaxLiabAmt' has a non-zero value, then Form 8962 must be present in the return.",
  ),
];
