/**
 * MeF Business Rules: S3
 * Auto-generated from 1040_Business_Rules_2025v3.0.csv
 * 36 rules (31 implemented, 5 stubs)
 */

import type { RuleDef } from "../../../../core/validation/types.ts";
import { rule, alwaysPass, eqField, eqSum, hasValue, hasNonZero, gt, ifThen, isZero, noValue, not, any, all, formPresent, formCountAtMost, notGtNum, filingStatusIs, filingStatusNot, sumOfAll, } from "../../../../core/validation/mod.ts";

export const S3_RULES: readonly RuleDef[] = [
  rule(
    "S3-F1040-002",
    "reject",
    "missing_document",
    ifThen(gt("TaxPaidByRICOrREITAmt", 0), formPresent("form2439")),
    "If Schedule 3 (Form 1040), 'TaxPaidByRICOrREITAmt' has a value greater than zero, then Form 2439 must be present in the return.",
  ),
  rule(
    "S3-F1040-013-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("OtherCreditsAmt"), any(hasNonZero("CurrentYearCreditAllowedAmt"), hasNonZero("MinAMTCrAmt"), hasNonZero("AdoptionCreditAmt"), hasNonZero("CreditForElderlyOrDisabledAmt"), hasNonZero("PersonalUsePartOfCreditAmt"), hasNonZero("CleanVehPrsnlUsePartCrAmt"), hasNonZero("MortgageInterestCreditAmt"), hasNonZero("DCHmByrCurrentYearCreditAmt"), hasNonZero("QlfyElecMotorVehCrAmt"), hasNonZero("TotalPersonalUsePartOfCrAmt"), hasNonZero("CurrentYearAllowableCreditAmt"), hasNonZero("TotRptgYrTxIncreaseDecreaseAmt"), hasNonZero("MaxPrevOwnedCleanVehCrAmt"), hasNonZero("TotOthNonrefundableCreditsAmt"))),
    "If Schedule 3 (Form 1040), 'OtherCreditsAmt' has a non-zero value, then at least one of the following must have a non-zero value: 'CurrentYearCreditAllowedAmt' or 'MinAMTCrAmt' or 'AdoptionCreditAmt' or 'CreditForElderlyOrDisabledAmt' or 'PersonalUsePartOfCreditAmt' or 'CleanVehPrsnlUsePartCrAmt' or 'MortgageInterestCreditAmt' or 'DCHmByrCurrentYearCreditAmt' or 'QlfyElecMotorVehCrAmt' or 'TotalPersonalUsePartOfCrAmt' or 'CurrentYearAllowableCreditAmt' or 'TotRptgYrTxIncreaseDecreaseAmt' or 'MaxPrevOwnedCleanVehCrAmt' or 'TotOthNonrefundableCreditsAmt'.",
  ),
  rule(
    "S3-F1040-016",
    "reject",
    "math_error",
    ifThen(hasNonZero("TotOthNonrefundableCreditsAmt"), sumOfAll("TotOthNonrefundableCreditsAmt", "OtherNonrefundableCreditsAmt")),
    "If Schedule 3 (Form 1040), 'TotOthNonrefundableCreditsAmt' has a value greater than zero, then it must be equal to the sum of all 'OtherNonrefundableCreditsAmt' in 'OtherNonrefundableCreditsGrp'.",
  ),
  rule(
    "S3-F1040-017-01",
    "reject",
    "math_error",
    ifThen(hasNonZero("TotalOtherRefundableCreditsAmt"), sumOfAll("TotalOtherRefundableCreditsAmt", "OtherRefundableCreditsAmt")),
    "If Schedule 3 (Form 1040), 'TotalOtherRefundableCreditsAmt' has a value greater than zero, then it must be equal to the sum of all 'OtherRefundableCreditsAmt' in 'OtherRefundableCreditsGrp'.",
  ),
  rule(
    "S3-F1040-021",
    "reject",
    "incorrect_data",
    alwaysPass, // requires cross-form aggregation: sum of all Forms 8978 TotRptgYrTxIncreaseDecreaseAmt with conditional sign-flip logic
    "Schedule 3 (Form 1040), 'TotRptgYrTxIncreaseDecreaseAmt' must be equal to 'TotalTaxBeforeCrAndOthTaxesAmt' in the return when (1) the sum of all Forms 8978, 'TotRptgYrTxIncreaseDecreaseAmt' is less than zero and (2) 'TotalTaxBeforeCrAndOthTaxesAmt' minus (-) [ the sum multiplied by negative 1 ] is less than zero.",
  ),
  rule(
    "S3-F1040-024",
    "reject",
    "math_error",
    ifThen(hasValue("EgyEffcntHmImprvCrAmt"), eqField("EgyEffcntHmImprvCrAmt", "EgyEffcntHmImprvCrAmt")),
    "If Schedule 3 (Form 1040), 'EgyEffcntHmImprvCrAmt' has a value greater than zero, then it must be equal to Form 5695, 'EgyEffcntHmImprvCrAmt'.",
  ),
  rule(
    "S3-F1040-026-01",
    "reject",
    "missing_document",
    ifThen(gt("NetElectivePymtElectionAmt", 0), formPresent("form3800")),
    "If Schedule 3 (Form 1040), 'NetElectivePymtElectionAmt' has a value greater than zero, then Form 3800 must be present in the return.",
  ),
  rule(
    "S3-F1040-031",
    "reject",
    "incorrect_data",
    alwaysPass, // requires cross-instance form lookup: two instances of Form 5695 with specific AdjustedCreditLimitCd value
    "If Schedule 3 (Form 1040), 'EgyEffcntHmImprvCrAmt' has a value greater than zero and there are two instances of Form 5695 present in the return, then Schedule 3 (Form 1040), 'EgyEffcntHmImprvCrAmt' must be equal to [ 'EgyEffcntHmImprvCrAmt' in 'EgyEffcntHmImprvCrGrp' ] from the instance of Form 5695 with 'AdjustedCreditLimitCd' having the value \"MORE THAN ONE MAIN HOME\".",
  ),
  rule(
    "S3-F1040-056-01",
    "reject",
    "missing_data",
    ifThen(all(hasNonZero("CreditForElderlyOrDisabledAmt"), noValue("Primary65OrOlderInd"), noValue("Spouse65OrOlderInd")), any(hasValue("Und65RtdPermnntTotDsbltyInd"), hasValue("BothUnder65OneRtdDsbltyInd"), hasValue("BothUnder65BothRtdDsbltyInd"), hasValue("Under65DidNotLiveTogetherInd"))),
    "If Schedule 3 (Form 1040), 'CreditForElderlyOrDisabledAmt' has a non-zero value and Form 1040, 'Primary65OrOlderInd' and 'Spouse65OrOlderInd' are not checked, then one of the following on Schedule R (Form 1040) must be checked: 'Und65RtdPermnntTotDsbltyInd' or 'BothUnder65OneRtdDsbltyInd' or 'BothUnder65BothRtdDsbltyInd' or 'Under65DidNotLiveTogetherInd'.",
  ),
  rule(
    "S3-F1040-097",
    "reject",
    "missing_document",
    ifThen(hasNonZero("RtrSavingsContributionsCrAmt"), formPresent("form8880")),
    "If Schedule 3 (Form 1040), 'RtrSavingsContributionsCrAmt' has a non-zero value, then Form 8880 must be attached to 'RtrSavingsContributionsCrAmt'.",
  ),
  rule(
    "S3-F1040-101-01",
    "reject",
    "math_error",
    sumOfAll("QlfyElecMotorVehCrAmt", "QlfyElecMotorVehCrAmt"),
    "Schedule 3 (Form 1040), 'QlfyElecMotorVehCrAmt' must be equal to the sum of all Forms 8834, 'QlfyElecMotorVehCrAmt'.",
  ),
  rule(
    "S3-F1040-102-01",
    "reject",
    "data_mismatch",
    ifThen(hasValue("AdoptionCreditAmt"), eqField("AdoptionCreditAmt", "AdoptionCreditAmt")),
    "Schedule 3 (Form 1040), 'AdoptionCreditAmt' must be equal to Form 8839, 'AdoptionCreditAmt'.",
  ),
  rule(
    "S3-F1040-104-01",
    "reject",
    "math_error",
    sumOfAll("TotalPersonalUsePartOfCrAmt", "TotalPersonalUsePartOfCrAmt"),
    "Schedule 3 (Form 1040), 'TotalPersonalUsePartOfCrAmt' must be equal to the sum of all Forms 8911, 'TotalPersonalUsePartOfCrAmt'.",
  ),
  rule(
    "S3-F1040-105-01",
    "reject",
    "math_error",
    sumOfAll("CurrentYearAllowableCreditAmt", "CurrentYearAllowableCreditAmt"),
    "Schedule 3 (Form 1040), 'CurrentYearAllowableCreditAmt' must be equal to the sum of all Forms 8912, 'CurrentYearAllowableCreditAmt'.",
  ),
  rule(
    "S3-F1040-106-02",
    "reject",
    "data_mismatch",
    ifThen(hasValue("CleanVehPrsnlUsePartCrAmt"), eqField("CleanVehPrsnlUsePartCrAmt", "CleanVehPrsnlUsePartCrAmt")),
    "Schedule 3 (Form 1040), 'CleanVehPrsnlUsePartCrAmt' must be equal to Form 8936, 'CleanVehPrsnlUsePartCrAmt'.",
  ),
  rule(
    "S3-F1040-107-01",
    "reject",
    "data_mismatch",
    ifThen(hasValue("MortgageInterestCreditAmt"), eqField("MortgageInterestCreditAmt", "MortgageInterestCreditAmt")),
    "Schedule 3 (Form 1040), 'MortgageInterestCreditAmt' must be equal to Form 8396, 'MortgageInterestCreditAmt'.",
  ),
  rule(
    "S3-F1040-108-01",
    "reject",
    "data_mismatch",
    ifThen(hasValue("DCHmByrCurrentYearCreditAmt"), eqField("DCHmByrCurrentYearCreditAmt", "DCHmByrCurrentYearCreditAmt")),
    "Schedule 3 (Form 1040), 'DCHmByrCurrentYearCreditAmt' must be equal to Form 8859, 'DCHmByrCurrentYearCreditAmt'.",
  ),
  rule(
    "S3-F1040-109-01",
    "reject",
    "incorrect_data",
    alwaysPass, // requires cross-form aggregation: sum of all Forms 8978 TotRptgYrTxIncreaseDecreaseAmt with sign-flip conditional
    "Schedule 3 (Form 1040), 'TotRptgYrTxIncreaseDecreaseAmt' must be equal to [ the sum of all Forms 8978, 'TotRptgYrTxIncreaseDecreaseAmt' ] multiplied by negative 1 when (1) the sum is less than zero and (2) 'TotalTaxBeforeCrAndOthTaxesAmt' in the return minus (-) [ the sum multiplied by negative 1 ] is greater than or equal to zero.",
  ),
  rule(
    "S3-F1040-110",
    "reject",
    "data_mismatch",
    ifThen(hasValue("MaxPrevOwnedCleanVehCrAmt"), eqField("MaxPrevOwnedCleanVehCrAmt", "MaxPrevOwnedCleanVehCrAmt")),
    "Schedule 3 (Form 1040), 'MaxPrevOwnedCleanVehCrAmt' must be equal to Form 8936, 'MaxPrevOwnedCleanVehCrAmt'.",
  ),
  rule(
    "S3-F1040-112",
    "reject",
    "data_mismatch",
    ifThen(hasValue("CreditForChildAndDepdCareAmt"), eqField("CreditForChildAndDepdCareAmt", "CreditForChildAndDepdCareAmt")),
    "Schedule 3 (Form 1040), 'CreditForChildAndDepdCareAmt' must be equal to Form 2441, 'CreditForChildAndDepdCareAmt.",
  ),
  rule(
    "S3-F1040-125-01",
    "reject",
    "data_mismatch",
    ifThen(hasValue("CurrentYearCreditAllowedAmt"), eqField("CurrentYearCreditAllowedAmt", "CurrentYearCreditAllowedAmt")),
    "Schedule 3 (Form 1040), 'CurrentYearCreditAllowedAmt' must be equal to Form 3800, 'CurrentYearCreditAllowedAmt'.",
  ),
  rule(
    "S3-F1040-134-01",
    "reject",
    "data_mismatch",
    ifThen(hasValue("CreditForElderlyOrDisabledAmt"), eqField("CreditForElderlyOrDisabledAmt", "CreditForElderlyOrDisabledAmt")),
    "Schedule 3 (Form 1040), 'CreditForElderlyOrDisabledAmt' must be equal to Schedule R (Form 1040), 'CreditForElderlyOrDisabledAmt'.",
  ),
  rule(
    "S3-F1040-137-01",
    "reject",
    "data_mismatch",
    ifThen(hasValue("MinAMTCrAmt"), eqField("MinAMTCrAmt", "MinAMTCrAmt")),
    "Schedule 3 (Form 1040), 'MinAMTCrAmt' must be equal to Form 8801, 'MinAMTCrAmt'.",
  ),
  rule(
    "S3-F1040-138-06",
    "reject",
    "missing_data",
    ifThen(hasNonZero("OtherPaymentsAmt"), any(hasNonZero("TaxPaidByRICOrREITAmt"), hasNonZero("CreditForRepaymentAmt"), hasNonZero("NetElectivePymtElectionAmt"), hasNonZero("NetSection965TaxLiabilityAmt"), hasNonZero("TotalOtherRefundableCreditsAmt"))),
    "If Schedule 3 (Form 1040), 'OtherPaymentsAmt' has a non-zero value, then at least one of the following must have a non-zero value: 'TaxPaidByRICOrREITAmt' or 'CreditForRepaymentAmt' or 'NetElectivePymtElectionAmt' or 'NetSection965TaxLiabilityAmt' or 'TotalOtherRefundableCreditsAmt'.",
  ),
  rule(
    "S3-F1040-144",
    "reject",
    "missing_document",
    alwaysPass, // requires cross-instance check: at least two Form W-2s with the same EmployeeSSN present in the return
    "If Schedule 3 (Form 1040), 'ExcessSocSecAndTier1RRTATaxAmt' has a non-zero value, then at least two Form W-2s with the same 'EmployeeSSN' must be present in the return.",
  ),
  rule(
    "S3-F1040-152-02",
    "reject",
    "math_error",
    ifThen(hasNonZero("ResidentialCleanEnergyCrAmt"), sumOfAll("ResidentialCleanEnergyCrAmt", "ResidentialCleanEnergyCrAmt")),
    "If Schedule 3 (Form 1040), 'ResidentialCleanEnergyCrAmt' has a non-zero value, then it must be equal to the sum of all Forms 5695, 'ResidentialCleanEnergyCrAmt'.",
  ),
  rule(
    "S3-F1040-155",
    "reject",
    "data_mismatch",
    ifThen(hasValue("TotalFuelTaxCreditAmt"), eqField("TotalFuelTaxCreditAmt", "TotalFuelTaxCreditAmt")),
    "Schedule 3 (Form 1040), 'TotalFuelTaxCreditAmt' must be equal to Form 4136, 'TotalFuelTaxCreditAmt'.",
  ),
  rule(
    "S3-F1040-156",
    "reject",
    "incorrect_data",
    isZero("PersonalUsePartOfCreditAmt"),
    "Schedule 3 (Form 1040), 'PersonalUsePartOfCreditAmt' must be zero if an amount is entered.",
  ),
  rule(
    "S3-F1040-208",
    "reject",
    "incorrect_data",
    notGtNum("RtrSavingsContributionsCrAmt", 1000),
    "If the filing status of the return is single or married filing separately or head of household or Qualifying Surviving Spouse, then Schedule 3 (Form 1040), 'RtrSavingsContributionsCrAmt' must not be greater than 1000.",
  ),
  rule(
    "S3-F1040-209",
    "reject",
    "incorrect_data",
    notGtNum("RtrSavingsContributionsCrAmt", 2000),
    "If the filing status of the return is married filing jointly, then Schedule 3 (Form 1040), 'RtrSavingsContributionsCrAmt' must not be greater than 2000.",
  ),
  rule(
    "S3-F1040-370-06",
    "reject",
    "incorrect_data",
    notGtNum("RtrSavingsContributionsCrAmt", 39500),
    "If Schedule 3 (Form 1040), 'RtrSavingsContributionsCrAmt' has a non-zero value and the filing status of the return is single or married filing separately or Qualifying Surviving Spouse, then 'AdjustedGrossIncomeAmt' in the return must not be greater than 39500.",
  ),
  rule(
    "S3-F1040-371-06",
    "reject",
    "incorrect_data",
    notGtNum("RtrSavingsContributionsCrAmt", 59250),
    "If Schedule 3 (Form 1040), 'RtrSavingsContributionsCrAmt' has a non-zero value and the filing status of the return is head of household, then Form 1040, 'AdjustedGrossIncomeAmt' must not be greater than 59250.",
  ),
  rule(
    "S3-F1040-372-06",
    "reject",
    "incorrect_data",
    notGtNum("RtrSavingsContributionsCrAmt", 79000),
    "If Schedule 3 (Form 1040), 'RtrSavingsContributionsCrAmt' has a non-zero value and the filing status of the return is married filing jointly, then Form 1040, 'AdjustedGrossIncomeAmt' must not be greater than 79000.",
  ),
  rule(
    "S3-F1040-373",
    "reject",
    "incorrect_data",
    noValue("OtherRefundableCrTxt"),
    "Schedule 3 (Form 1040), 'OtherRefundableCrTxt' must not have a value.",
  ),
  rule(
    "S3-F1040-422",
    "reject",
    "data_mismatch",
    ifThen(hasValue("EducationCreditAmt"), eqField("EducationCreditAmt", "NonrefundableEducationCrAmt")),
    "Schedule 3 (Form 1040), 'EducationCreditAmt' must be equal to Form 8863, 'NonrefundableEducationCrAmt'.",
  ),
  rule(
    "S3-F1040-800",
    "reject",
    "data_mismatch",
    ifThen(hasValue("ReconciledPremiumTaxCreditAmt"), eqField("ReconciledPremiumTaxCreditAmt", "ReconciledPremiumTaxCreditAmt")),
    "Schedule 3 (Form 1040), 'ReconciledPremiumTaxCreditAmt' must be equal to Form 8962, 'ReconciledPremiumTaxCreditAmt'.",
  ),
];
