/**
 * MeF Business Rules: SA
 * Auto-generated from 1040_Business_Rules_2025v3.0.csv
 * 61 rules (52 implemented, 9 stubs)
 */

import type { RuleDef } from "../../../../core/validation/types.ts";
import { rule, alwaysPass, dateGteField, dateLteField, decimalPlacesEq, eqField, eqMin, eqMinNum, eqNum, eqProduct, eqStr, eqSum, hasValue, hasNonZero, gt, gte, ifThen, isZero, lt, noValue, not, notGtField, notGtNum, notLtSum, strLenEq, any, all, formPresent, filingStatusIs, filingStatusNot, sumOfAll, } from "../../../../core/validation/mod.ts";

export const SA_RULES: readonly RuleDef[] = [
  rule(
    "SA-F1040-001-02",
    "reject",
    "missing_data",
    ifThen(hasNonZero("TotalInterestPaidAmt"), any(hasNonZero("RptHomeMortgIntAndPointsAmt"), hasNonZero("Form1098HomeMortgIntNotRptAmt"), hasNonZero("Form1098PointsNotReportedAmt"), hasNonZero("MortgageInsurancePremiumsAmt"), hasNonZero("InvestmentInterestAmt"))),
    "If Schedule A (Form 1040), 'TotalInterestPaidAmt' has a non-zero value, then one of the following must have a non-zero value: 'RptHomeMortgIntAndPointsAmt', 'Form1098HomeMortgIntNotRptAmt', 'Form1098PointsNotReportedAmt', 'MortgageInsurancePremiumsAmt' or 'InvestmentInterestAmt'.",
  ),
  rule(
    "SA-F1040-002",
    "reject",
    "missing_document",
    ifThen(gt("OtherThanByCashOrCheckAmt", 500), formPresent("form8283")),
    "If Schedule A (Form 1040), 'OtherThanByCashOrCheckAmt' is greater than 500, then Form 8283 must be attached.",
  ),
  rule(
    "SA-F1040-003-02",
    "reject",
    "missing_document",
    alwaysPass, // requires binary attachment check: Art Appraisal attachment or Form8283PaperDocumentInd in Return Header
    "If Schedule A (Form 1040), 'OtherThanByCashOrCheckAmt' is greater than or equal to 20000 and Form 8283, Section B, Part 1, 'ArtWorthAtLeast20000DollarsInd' is checked, then a binary attachment with Description beginning with \"Art Appraisal\" must be attached to Form 8283 or 'Form8283PaperDocumentInd' in the Return Header must be checked.",
  ),
  rule(
    "SA-F1040-007-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("MiscellaneousDeductionAmt"), hasNonZero("OtherMiscellaneousDedAmt")),
    "If 'MiscellaneousDeductionAmt' in [OtherMiscellaneousDeductionsStatement] has a non-zero value, then Schedule A (Form 1040), 'OtherMiscellaneousDedAmt' must have a non-zero value.",
  ),
  rule(
    "SA-F1040-011-03",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusNot(3), gt("AdjustedGrossIncomeAmt", 109000)), isZero("MortgageInsurancePremiumsAmt")),
    "If the filing status of the return is single or married filing jointly or head of household or Qualifying Surviving Spouse and Form 1040, 'AdjustedGrossIncomeAmt' has a value greater than 109000, then Schedule A (Form 1040), 'MortgageInsurancePremiumsAmt' must have a zero value if an amount is entered.",
  ),
  rule(
    "SA-F1040-012-02",
    "reject",
    "incorrect_data",
    ifThen(all(filingStatusIs(3), gt("AdjustedGrossIncomeAmt", 54500)), isZero("MortgageInsurancePremiumsAmt")),
    "If Form 1040, \"Married filing separately\" is checked and Form 1040, 'AdjustedGrossIncomeAmt' has a value greater than 54500, then Schedule A (Form 1040), 'MortgageInsurancePremiumsAmt' must have a zero value if an amount is entered.",
  ),
  rule(
    "SA-F1040-014-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("CalcAdjGroIncmMnsTotNetLossAmt"), formPresent("form4684")),
    "If Schedule A (Form 1040), 'CalcAdjGroIncmMnsTotNetLossAmt' has a non-zero value, then Form 4684 must be attached to Schedule A (Form 1040), 'CalcAdjGroIncmMnsTotNetLossAmt'.",
  ),
  rule(
    "SA-F1040-015-02",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("CalcAdjGroIncmMnsTotNetLossAmt"), sumOfAll("CalcAdjGroIncmMnsTotNetLossAmt", "CalcAdjGroIncmMnsTotNetLossAmt")),
    "If Schedule A (Form 1040), 'CalcAdjGroIncmMnsTotNetLossAmt' has a non-zero value, then it must be equal to the sum of all Forms 4684, 'CalcAdjGroIncmMnsTotNetLossAmt'.",
  ),
  rule(
    "SA-F1040-018",
    "reject",
    "incorrect_data",
    isZero("MortgageInsurancePremiumsAmt"),
    "Schedule A (Form 1040), 'MortgageInsurancePremiumsAmt' must be equal to zero if an amount is entered.",
  ),
  rule(
    "SA-F1040-022",
    "reject",
    "incorrect_data",
    ifThen(hasValue("CalculatedMedicalAllowanceAmt"), eqField("CalculatedMedicalAllowanceAmt", "TaxReturnAGIAmt")),
    "Schedule A (Form 1040), 'CalculatedMedicalAllowanceAmt' must be equal to 7.5% (0.075) of 'TaxReturnAGIAmt'.",
  ),
  rule(
    "SA-F1040-023-01",
    "reject",
    "missing_document",
    alwaysPass, // requires string value check in repeating group: MiscellaneousDeductionTypeDesc matching specific values
    "If Schedule A (Form 1040), 'OtherMiscellaneousDedAmt' has a non-zero value and 'MiscellaneousDeductionTypeDesc' in [OtherMiscellaneousDeductionsStatement] has the value [\"NET QUALIFIED DISASTER LOSS\" or \"STANDARD DEDUCTION CLAIMED WITH QUALIFIED DISASTER LOSS\"], then Form 4684 must be present in the return.",
  ),
  rule(
    "SA-F1040-024",
    "reject",
    "incorrect_data",
    notGtNum("StateAndLocalTaxLimitationAmt", 10000),
    "If Schedule A (Form 1040), 'StateAndLocalTaxLimitationAmt' has a non-zero value, then it must not be greater than 10000 or 5000 if married filing separate.",
  ),
  rule(
    "SA-F1040-025-01",
    "reject",
    "incorrect_data",
    alwaysPass, // requires cross-form comparison with repeating group value filtered by MiscellaneousDeductionTypeDesc = "GAMBLING LOSSES"
    "If Schedule A (Form 1040), 'OtherMiscellaneousDedAmt' has a non-zero value, then Schedule 1 (Form 1040), 'GamblingReportableWinningAmt' must be greater than or equal to 'MiscellaneousDeductionAmt' in [OtherMiscDeductionsStmt] with corresponding 'MiscellaneousDeductionTypeDesc' having the value \"GAMBLING LOSSES\".",
  ),
  rule(
    "SA-F1040-026",
    "reject",
    "incorrect_data",
    ifThen(all(hasNonZero("MedicalAndDentalExpensesAmt"), not(notGtField("CalculatedMedicalAllowanceAmt", "MedicalAndDentalExpensesAmt"))), isZero("TotalMedicalAndDentalExpnssAmt")),
    "If Schedule A (Form 1040), 'MedicalAndDentalExpensesAmt' has a non-zero value, and 'CalculatedMedicalAllowanceAmt' is greater than 'MedicalAndDentalExpensesAmt', then 'TotalMedicalAndDentalExpnssAmt' must be equal to zero if an amount is entered.",
  ),
  rule(
    "SA-F1040-027",
    "reject",
    "incorrect_data",
    eqSum("TotalCharitableContriAmt", "GiftsByCashOrCheckAmt", "OtherThanByCashOrCheckAmt", "CarryoverFromPriorYearAmt"),
    "Schedule A (Form 1040), 'TotalCharitableContriAmt' must be equal to the sum of the following: 'GiftsByCashOrCheckAmt' and 'OtherThanByCashOrCheckAmt' and 'CarryoverFromPriorYearAmt'.",
  ),
  rule(
    "SA-F8936-001",
    "reject",
    "incorrect_data",
    ifThen(hasValue("VehiclePlacedInServiceDt"), all(dateGteField("VehiclePlacedInServiceDt", "TaxPeriodBeginDt"), dateLteField("VehiclePlacedInServiceDt", "TaxPeriodEndDt"))),
    "Schedule A (Form 8936), 'VehiclePlacedInServiceDt' must be between [ 'TaxPeriodBeginDt' and 'TaxPeriodEndDt' ] in the Return Header.",
  ),
  rule(
    "SA-F8936-010-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("AcqVehUseOrLeaseNotResaleInd", "No"), all(noValue("BusinessInvestmentUseAmt"), noValue("PrsnlUseNewCleanVehicleCrAmt"))),
    "In 'NewCleanVehicleGrp' on Schedule A (Form 8936), if 'AcqVehUseOrLeaseNotResaleInd' has a choice of \"No\" indicated, then both [ 'BusinessInvestmentUseAmt' and 'PrsnlUseNewCleanVehicleCrAmt' ] must not have a value.",
  ),
  rule(
    "SA-F8936-011-01",
    "reject",
    "incorrect_data",
    notGtNum("TentativeCreditAmt", 7500),
    "Schedule A (Form 8936), [ 'TentativeCreditAmt' in 'NewCleanVehicleGrp' ] must not have a value greater than 7500.",
  ),
  rule(
    "SA-F8936-012-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("BusinessInvestmentUsePct", "100"), isZero("PrsnlUseNewCleanVehicleCrAmt")),
    "In 'NewCleanVehicleGrp' on Schedule A (Form 8936), if 'BusinessInvestmentUsePct' is 100%, then 'PrsnlUseNewCleanVehicleCrAmt' must be zero if an amount is entered.",
  ),
  rule(
    "SA-F8936-013-01",
    "reject",
    "incorrect_data",
    notGtNum("BusinessInvestmentUseAmt", 7500),
    "Schedule A (Form 8936), [ 'BusinessInvestmentUseAmt' in 'NewCleanVehicleGrp' ] must not have a value greater than 7500.",
  ),
  rule(
    "SA-F8936-014-01",
    "reject",
    "incorrect_data",
    notGtField("PrsnlUseNewCleanVehicleCrAmt", "TentativeCreditAmt"),
    "In 'NewCleanVehicleGrp' on Schedule A (Form 8936), 'PrsnlUseNewCleanVehicleCrAmt' must not be greater than 'TentativeCreditAmt'.",
  ),
  rule(
    "SA-F8936-015-01",
    "reject",
    "incorrect_data",
    notGtNum("PrsnlUseNewCleanVehicleCrAmt", 7500),
    "Schedule A (Form 8936), [ 'PrsnlUseNewCleanVehicleCrAmt' in 'NewCleanVehicleGrp' ] must not have a value greater than 7500.",
  ),
  rule(
    "SA-F8936-016-01",
    "reject",
    "incorrect_data",
    notGtNum("NewCleanVehicleGrp", 7500),
    "In 'NewCleanVehicleGrp' on Schedule A (Form 8936), [ 'BusinessInvestmentUseAmt' plus (+) 'PrsnlUseNewCleanVehicleCrAmt' ] must not be greater than 7500.",
  ),
  rule(
    "SA-F8936-017-01",
    "reject",
    "incorrect_data",
    notLtSum("TentativeCreditAmt", "BusinessInvestmentUseAmt", "PrsnlUseNewCleanVehicleCrAmt"),
    "In 'NewCleanVehicleGrp' on Schedule A (Form 8936), [ 'BusinessInvestmentUseAmt' plus (+) 'PrsnlUseNewCleanVehicleCrAmt' ] must not be greater than 'TentativeCreditAmt'.",
  ),
  rule(
    "SA-F8936-018-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("ClnVehSalePriceMoreSpcfdAmtInd", "Yes"), noValue("PrevOwnedCleanVehCreditAmt")),
    "In 'PrevOwnCleanVehicleGrp' on Schedule A (Form 8936), if 'ClnVehSalePriceMoreSpcfdAmtInd' has a choice of \"Yes\" indicated, then 'PrevOwnedCleanVehCreditAmt' must not have a value.",
  ),
  rule(
    "SA-F8936-019-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("AcqPrevOwnVehUseNotResaleInd", "No"), noValue("PrevOwnedCleanVehCreditAmt")),
    "In 'PrevOwnCleanVehicleGrp' on Schedule A (Form 8936), if 'AcqPrevOwnVehUseNotResaleInd' has a choice of \"No\" indicated, then 'PrevOwnedCleanVehCreditAmt' must not have a value.",
  ),
  rule(
    "SA-F8936-020-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("ClaimedAsDependentInd", "Yes"), noValue("PrevOwnedCleanVehCreditAmt")),
    "In 'PrevOwnCleanVehicleGrp' on Schedule A (Form 8936), if 'ClaimedAsDependentInd' has a choice of \"Yes\" indicated, then 'PrevOwnedCleanVehCreditAmt' must not have a value.",
  ),
  rule(
    "SA-F8936-021-01",
    "reject",
    "incorrect_data",
    ifThen(gt("SalePriceAmt", 25000), isZero("PrevOwnedCleanVehCreditAmt")),
    "In 'PrevOwnCleanVehicleGrp' on Schedule A (Form 8936), if 'SalePriceAmt' has a value greater than 25000, then 'PrevOwnedCleanVehCreditAmt' must be zero if an amount is entered.",
  ),
  rule(
    "SA-F8936-022-01",
    "reject",
    "incorrect_data",
    notGtNum("PrevOwnedCleanVehCreditAmt", 4000),
    "Schedule A (Form 8936), [ 'PrevOwnedCleanVehCreditAmt' in 'PrevOwnCleanVehicleGrp' ] must not be greater than 4000.",
  ),
  rule(
    "SA-F8936-023-01",
    "reject",
    "incorrect_data",
    ifThen(gt("PrevOwnedCleanVehCreditAmt", 0), eqMinNum("PrevOwnedCleanVehCreditAmt", "SalePriceBySpecifiedPctAmt", 4000)),
    "In 'PrevOwnCleanVehicleGrp' on Schedule A (Form 8936), if 'PrevOwnedCleanVehCreditAmt' has a value greater than zero, then it must be equal to the lesser of [ 'SalePriceBySpecifiedPctAmt' and 4000 ].",
  ),
  rule(
    "SA-F8936-024-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("VehOfCharSubjToAllwncDeprecInd", "No"), noValue("QlfyCmrclCleanVehicleCrAmt")),
    "In 'QlfyCmrclCleanVehicleYesGrp' on Schedule A (Form 8936), if 'VehOfCharSubjToAllwncDeprecInd' has a choice of \"No\" indicated, then 'QlfyCmrclCleanVehicleCrAmt' must not have a value.",
  ),
  rule(
    "SA-F8936-025-01",
    "reject",
    "incorrect_data",
    ifThen(eqStr("AcqCmrclClnVehUseNotResaleInd", "No"), noValue("QlfyCmrclCleanVehicleCrAmt")),
    "In 'QlfyCmrclCleanVehicleYesGrp' on Schedule A (Form 8936), if 'AcqCmrclClnVehUseNotResaleInd' has a choice of \"No\" indicated, then 'QlfyCmrclCleanVehicleCrAmt' must not have a value.",
  ),
  rule(
    "SA-F8936-026-01",
    "reject",
    "incorrect_data",
    notGtNum("QlfyCmrclCleanVehicleCrAmt", 40000),
    "Schedule A (Form 8936), [ 'QlfyCmrclCleanVehicleCrAmt' in 'QlfyCmrclCleanVehicleYesGrp' ] must not be greater than 40000.",
  ),
  rule(
    "SA-F8936-027-01",
    "reject",
    "incorrect_data",
    ifThen(gt("QlfyCmrclCleanVehicleCrAmt", 0), eqMin("QlfyCmrclCleanVehicleCrAmt", "TentQlfyCmrclCleanVehicleCrAmt", "MaxQlfyCmrclCleanVehCrAmt")),
    "In 'QlfyCmrclCleanVehicleYesGrp' on Schedule A (Form 8936), if 'QlfyCmrclCleanVehicleCrAmt' has a value greater than zero, then it must be equal to the lesser of  [ 'TentQlfyCmrclCleanVehicleCrAmt' and 'MaxQlfyCmrclCleanVehCrAmt' ].",
  ),
  rule(
    "SA-F8936-028-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("MaxQlfyCmrclCleanVehCrAmt"), any(all(lt("GrossVehicleWeightRatingNum", 14000), eqNum("MaxQlfyCmrclCleanVehCrAmt", 7500)), all(gte("GrossVehicleWeightRatingNum", 14000), eqNum("MaxQlfyCmrclCleanVehCrAmt", 40000)))),
    "In 'QlfyCmrclCleanVehicleYesGrp' on Schedule A (Form 8936), if 'MaxQlfyCmrclCleanVehCrAmt' has a value, then it must be [7500, if 'GrossVehicleWeightRatingNum' is less than 14000] or [40000, if 'GrossVehicleWeightRatingNum' is greater than or equal to 14000].",
  ),
  rule(
    "SA-F8936-029",
    "reject",
    "incorrect_data",
    ifThen(hasValue("VIN"), strLenEq("VIN", 17)),
    "Schedule A (Form 8936), 'VIN' must be exactly 17 characters in length.",
  ),
  rule(
    "SA-F8936-030-01",
    "reject",
    "incorrect_data",
    alwaysPass, // requires e-File database lookup: VIN validation against IRS vehicle database
    "Schedule A (Form 8936), 'VIN' does not match the e-File database. Please resubmit the return using the correct VIN. If the VIN originally entered is correct, then a binary attachment or [GeneralDependencySmall] with description beginning with \"Substantiate VIN\" must be present in the return.",
  ),
  rule(
    "SA-F8936-031-01",
    "reject",
    "incorrect_data",
    alwaysPass, // requires cross-instance check: same VIN must not appear on two or more instances of Schedule A (Form 8936)
    "The same 'VIN' must not appear on two or more instances of Schedule A (Form 8936).",
  ),
  rule(
    "SA-F8936-032",
    "reject",
    "incorrect_data",
    ifThen(eqStr("CrTrnsfrDlrSaleInd", "Yes"), gt("CrTrnsfrDlrSaleAmt", 0)),
    "If Schedule A (Form 8936), 'CrTrnsfrDlrSaleInd' has a choice of \"Yes\" indicated, then 'CrTrnsfrDlrSaleAmt' must have a value greater than zero.",
  ),
  rule(
    "SA-F8936-033",
    "reject",
    "incorrect_data",
    ifThen(hasValue("NotAllowedClaimClnVehCrInd"), all(noValue("BusinessInvestmentUseAmt"), noValue("PrsnlUseNewCleanVehicleCrAmt"), noValue("PrevOwnedCleanVehCreditAmt"))),
    "If Schedule A (Form 8936), 'NotAllowedClaimClnVehCrInd' is checked, then each of the following must not have a value: [ 'BusinessInvestmentUseAmt' and 'PrsnlUseNewCleanVehicleCrAmt' in 'NewCleanVehicleGrp' ] and [ 'PrevOwnedCleanVehCreditAmt' in 'PrevOwnCleanVehicleGrp' ].",
  ),
  rule(
    "SA-F8936-034",
    "reject",
    "incorrect_data",
    ifThen(eqStr("ResellClnVeh30DaysInd", "Yes"), all(noValue("BusinessInvestmentUseAmt"), noValue("PrsnlUseNewCleanVehicleCrAmt"))),
    "In 'NewCleanVehicleGrp' on Schedule A (Form 8936), if 'ResellClnVeh30DaysInd' has a choice of \"Yes\" indicated, then 'BusinessInvestmentUseAmt' and 'PrsnlUseNewCleanVehicleCrAmt' must not have values.",
  ),
  rule(
    "SA-F8936-035",
    "reject",
    "incorrect_data",
    ifThen(all(eqStr("CrTrnsfrDlrSaleInd", "Yes"), eqStr("ResellClnVeh30DaysInd", "Yes")), hasValue("NotAllowedClaimClnVehCrInd")),
    "On Schedule A (Form 8936), if both 'CrTrnsfrDlrSaleInd' and [ 'ResellClnVeh30DaysInd' in 'NewCleanVehicleGrp' ] have a choice of \"Yes\" indicated, then 'NotAllowedClaimClnVehCrInd' must be checked.",
  ),
  rule(
    "SA-F8936-036",
    "reject",
    "incorrect_data",
    ifThen(eqStr("AmtGrtrThanPYFSLimitInd", "Yes"), all(noValue("BusinessInvestmentUseAmt"), noValue("PrsnlUseNewCleanVehicleCrAmt"))),
    "In 'NewCleanVehicleGrp' on Schedule A (Form 8936), if 'AmtGrtrThanPYFSLimitInd' has a choice of \"Yes\" indicated, then 'BusinessInvestmentUseAmt' and 'PrsnlUseNewCleanVehicleCrAmt' must not have values.",
  ),
  rule(
    "SA-F8936-037",
    "reject",
    "incorrect_data",
    ifThen(eqStr("PrevOwnResellClnVeh30DaysInd", "Yes"), noValue("PrevOwnedCleanVehCreditAmt")),
    "If in 'PrevOwnCleanVehicleGrp' on Schedule A (Form 8936), 'PrevOwnResellClnVeh30DaysInd' has a choice of \"Yes\" indicated, then 'PrevOwnedCleanVehCreditAmt' must not have a value.",
  ),
  rule(
    "SA-F8936-038",
    "reject",
    "incorrect_data",
    ifThen(eqStr("ClmPrevOwnClnVeh3YrPeriodInd", "Yes"), noValue("PrevOwnedCleanVehCreditAmt")),
    "In 'PrevOwnCleanVehicleGrp' on Schedule A (Form 8936), if 'ClmPrevOwnClnVeh3YrPeriodInd' has a choice of \"Yes\" indicated, then 'PrevOwnedCleanVehCreditAmt' must not have a value.",
  ),
  rule(
    "SA-F8936-039",
    "reject",
    "incorrect_data",
    ifThen(all(eqStr("VehOfCharSubjToAllwncDeprecInd", "Yes"), eqStr("AcqCmrclClnVehUseNotResaleInd", "Yes")), hasNonZero("GrossVehicleWeightRatingNum")),
    "In 'QlfyCmrclCleanVehicleYesGrp' on Schedule A (Form 8936), if both [ 'VehOfCharSubjToAllwncDeprecInd' and 'AcqCmrclClnVehUseNotResaleInd' ] have a choice of \"Yes\" indicated, then 'GrossVehicleWeightRatingNum' must have a value greater than zero.",
  ),
  rule(
    "SA-F8936-040",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("SalePriceBySpecifiedPctAmt"), eqProduct("SalePriceBySpecifiedPctAmt", "SalePriceAmt", 0.30)),
    "In 'PrevOwnCleanVehicleGrp' on Schedule A (Form 8936), if 'SalePriceBySpecifiedPctAmt' has a non-zero value, then it must be equal to 'SalePriceAmt' multiplied by 30% (0.30).",
  ),
  rule(
    "SA-F8936-041",
    "reject",
    "incorrect_data",
    notGtNum("SalePriceAmt", 25000),
    "Schedule A (Form 8936), [ 'SalePriceAmt' in 'PrevOwnCleanVehicleGrp' ] must not have a value greater than 25000.",
  ),
  rule(
    "SA-F8936-042",
    "reject",
    "incorrect_data",
    ifThen(all(eqStr("CrTrnsfrDlrSaleInd", "Yes"), eqStr("AmtGrtrThanPYFSLimitInd", "Yes")), hasValue("NotAllowedClaimClnVehCrInd")),
    "On Schedule A (Form 8936), if both 'CrTrnsfrDlrSaleInd' and [ 'AmtGrtrThanPYFSLimitInd' in 'NewCleanVehicleGrp' ] have a choice of \"Yes\" indicated, then 'NotAllowedClaimClnVehCrInd' must be checked.",
  ),
  rule(
    "SA-F8936-043",
    "reject",
    "incorrect_data",
    ifThen(all(eqStr("CrTrnsfrDlrSaleInd", "Yes"), eqStr("PrevOwnResellClnVeh30DaysInd", "Yes")), hasValue("NotAllowedClaimClnVehCrInd")),
    "On Schedule A (Form 8936), if both 'CrTrnsfrDlrSaleInd' and [ 'PrevOwnResellClnVeh30DaysInd' in 'PrevOwnCleanVehicleGrp' ] have a choice of \"Yes\" indicated, then 'NotAllowedClaimClnVehCrInd' must be checked.",
  ),
  rule(
    "SA-F8936-044",
    "reject",
    "incorrect_data",
    ifThen(all(eqStr("CrTrnsfrDlrSaleInd", "Yes"), eqStr("PrevOwnAmtGrtrThanPYFSLimitInd", "Yes")), hasValue("NotAllowedClaimClnVehCrInd")),
    "On Schedule A (Form 8936), if both 'CrTrnsfrDlrSaleInd' and [ 'PrevOwnAmtGrtrThanPYFSLimitInd' in 'PrevOwnCleanVehicleGrp' ] have a choice of \"Yes\" indicated, then 'NotAllowedClaimClnVehCrInd' must be checked.",
  ),
  rule(
    "SA-F8936-045",
    "reject",
    "incorrect_data",
    ifThen(eqStr("PrevOwnAmtGrtrThanPYFSLimitInd", "Yes"), noValue("PrevOwnedCleanVehCreditAmt")),
    "In 'PrevOwnCleanVehicleGrp' on Schedule A (Form 8936), if 'PrevOwnAmtGrtrThanPYFSLimitInd' has a choice of \"Yes\" indicated, then 'PrevOwnedCleanVehCreditAmt' must not have a value.",
  ),
  rule(
    "SA-F8936-046",
    "reject",
    "incorrect_data",
    alwaysPass, // requires e-File database lookup: TIN/VIN cross-reference validation against IRS Time of Sale database
    "Schedule A (Form 8936), 'TIN' does not match 'VIN' shown in the e-File database. Please refer to your Time of Sale report and resubmit your return.",
  ),
  rule(
    "SA-F8936-047",
    "reject",
    "incorrect_data",
    alwaysPass, // requires e-File database lookup: credit type validation against IRS vehicle credit database
    "Schedule A (Form 8936) credit amount does not match the type of credit reported in e-File database.",
  ),
  rule(
    "SA-F8936-048",
    "reject",
    "incorrect_data",
    alwaysPass, // requires e-File database lookup: vehicle purchase date validation against IRS Time of Sale database
    "The e-File database indicates this vehicle was not purchased during the tax period of the return.",
  ),
  rule(
    "SA-F8992-001",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("TotalGILTIAllocationRt"), eqNum("TotalGILTIAllocationRt", 1)),
    "If Schedule A (Form 8992), 'TotalGILTIAllocationRt' has a non-zero value, then it must be equal to 1.0000.",
  ),
  rule(
    "SA-F8992-003",
    "reject",
    "missing_data",
    any(hasValue("EIN"), hasValue("ForeignEntityReferenceIdNum")),
    "Schedule A (Form 8992), [ 'EIN' or 'ForeignEntityReferenceIdNum' ] in 'USShrCalcGILTIGrp' must have a value.",
  ),
  rule(
    "SA-F8995A-001",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("PhaseInPct"), decimalPlacesEq("PhaseInPct", 5)),
    "If Schedule A (Form 8995-A), 'PhaseInPct' has a non-zero value, then it must have exactly five decimal places.",
  ),
  rule(
    "SA-F8995A-002",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("ApplicablePct"), decimalPlacesEq("ApplicablePct", 5)),
    "If Schedule A (Form 8995-A), 'ApplicablePct' has a non-zero value, then it must have exactly five decimal places.",
  ),
  rule(
    "SA-F8995A-003-05",
    "reject",
    "incorrect_data",
    ifThen(hasValue("FilingStatusThresholdCd"), any(all(filingStatusIs(2), eqStr("FilingStatusThresholdCd", "383900")), all(filingStatusNot(2), eqStr("FilingStatusThresholdCd", "191950")))),
    "If Schedule A (Form 8995-A), 'FilingStatusThresholdCd' has a value, then it must be one of the following based on the filing status of the return: (1) \"383900\" if married filing jointly or (2) \"191950\" for all other filing status.",
  ),
  rule(
    "SA-F8995A-006",
    "reject",
    "incorrect_data",
    ifThen(hasValue("FilingStatusPhaseInRangeCd"), any(all(filingStatusIs(2), eqStr("FilingStatusPhaseInRangeCd", "100000")), all(filingStatusNot(2), eqStr("FilingStatusPhaseInRangeCd", "50000")))),
    "If Schedule A (Form 8995-A), 'FilingStatusPhaseInRangeCd' has a value, then it must be one of the following based on the filing status of the return: (1) \"100000\", if married filing jointly or (2) \"50000\" for all other filing status.",
  ),
];
